//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "TableViewController.h"

#import "RKServiceConnectorUIDelegate-Protocol.h"

@class NSArray, NSString, RKService, RKServiceConnector;
@protocol AccountServiceSelectionViewControllerDelegate;

@interface AccountServiceSelectionViewController : TableViewController <RKServiceConnectorUIDelegate>
{
    NSArray *__services;
    RKService *__selectedService;
    RKServiceConnector *__connector;
    id <AccountServiceSelectionViewControllerDelegate> __accountDelegate;
    int __sectionExperimental;
    int __sectionNews;
    int __sectionReadLater;
    int __sectionSelfHosted;
    int __sectionOpmlExistingAccount;
    int __sectionOpmlNewAccount;
    NSArray *_opmlItems;
}

@property(copy, nonatomic) NSArray *opmlItems; // @synthesize opmlItems=_opmlItems;
@property(nonatomic) __weak id <AccountServiceSelectionViewControllerDelegate> accountDelegate; // @synthesize accountDelegate=__accountDelegate;
- (void).cxx_destruct;
- (void)serviceConnectorDidEndModalSession:(id)arg1 withError:(id)arg2;
- (void)serviceConnectorWillStartModalSession:(id)arg1;
- (_Bool)serviceConnector:(id)arg1 shouldOpenUrl:(id)arg2;
- (_Bool)serviceConnectorWillSaveNewUser:(id)arg1;
- (void)__failedAuthorization_delayed;
- (void)__failedAuthorization;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)importOPML:(id)arg1;
- (void)done:(id)arg1;
- (id)tableView:(id)arg1 titleForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (_Bool)shouldAutorotateToInterfaceOrientation:(long long)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)pop:(id)arg1;
- (void)cancel:(id)arg1;
@property(readonly, nonatomic) NSArray *services;
- (void)didReceiveMemoryWarning;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

