//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class AccountServiceSelectionViewController, RKUser;

@protocol AccountServiceSelectionViewControllerDelegate <NSObject>
- (void)accountController:(AccountServiceSelectionViewController *)arg1 didImportOPML:(RKUser *)arg2;
- (void)accountController:(AccountServiceSelectionViewController *)arg1 didCreateUser:(RKUser *)arg2;
@end

