//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "AccountServiceSelectionTableViewCell.h"

@class RKUser;

@interface AccountServiceUserSelectionTableViewCell : AccountServiceSelectionTableViewCell
{
    RKUser *_user;
}

@property(retain, nonatomic) RKUser *user; // @synthesize user=_user;
- (void).cxx_destruct;
- (id)text;
- (id)title;
- (id)service;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

