//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "FormViewController.h"

#import "RSFormDelegate-Protocol.h"

@class NSMutableArray, NSString, TableViewCell, UITextField;

@interface AddSubscriptionSearchViewController : FormViewController <RSFormDelegate>
{
    NSMutableArray *__results;
    TableViewCell *__button;
    UITextField *__searchField;
}

- (void).cxx_destruct;
- (void)go:(id)arg1 animated:(_Bool)arg2;
- (void)go;
- (void)goWithUrlString:(id)arg1;
- (void)formDidSubmit:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 titleForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
@property(readonly, nonatomic) _Bool valid;
- (void)formDidChange:(id)arg1;
- (void)cancel:(id)arg1;
- (void)viewDidUnload;
- (void)pop:(id)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (_Bool)hasNavigationHeaderViewOnly;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

