//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "TableViewCell.h"

@class NSDictionary;

@interface AddSubscriptionSelectionFeedCell : TableViewCell
{
    NSDictionary *__feed;
}

@property(copy, nonatomic) NSDictionary *feed; // @synthesize feed=__feed;
- (void).cxx_destruct;
- (void)drawContentView:(id)arg1 rect:(struct CGRect)arg2;
@property(nonatomic) _Bool on;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

