//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "TableViewController.h"

@class NSArray, NSMutableArray, NSString, RKStream, RKUser;

@interface AddSubscriptionSelectionViewController : TableViewController
{
    NSArray *__feeds;
    NSString *__url;
    NSArray *__folders;
    long long __sectionFeeds;
    long long __sectionFolders;
    RKUser *__user;
    RKStream *__folder;
    NSMutableArray *__selectedFolders;
}

@property(retain, nonatomic) RKStream *folder; // @synthesize folder=__folder;
@property(retain, nonatomic) RKUser *user; // @synthesize user=__user;
@property(readonly, nonatomic) NSArray *feeds; // @synthesize feeds=__feeds;
- (void).cxx_destruct;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 titleForHeaderInSection:(long long)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)done:(id)arg1;
- (void)cancel:(id)arg1;
- (id)fetch;
- (void)validate;
- (void)setFeeds:(id)arg1;
- (void)viewDidUnload;
- (void)pop:(id)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)createFolder:(id)arg1;
- (void)addFolder:(id)arg1;
- (void)fetchFolders;
- (void)viewDidLoad;
- (_Bool)hasNavigationHeaderViewOnly;
- (id)initWithFeeds:(id)arg1;
- (id)initWithUrl:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

