//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UINavigationController.h>

@class RKStream, RKUser;

@interface AddSubscriptionViewController : UINavigationController
{
    RKUser *__user;
    RKStream *__folder;
}

@property(retain, nonatomic) RKStream *folder; // @synthesize folder=__folder;
@property(retain, nonatomic) RKUser *user; // @synthesize user=__user;
- (void).cxx_destruct;
- (_Bool)shouldAutorotateToInterfaceOrientation:(long long)arg1;
- (void)viewDidUnload;
- (void)viewDidLoad;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

