//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <QuartzCore/CATextLayer.h>

@interface AltTextLayer : CATextLayer
{
}

- (id)actionForKey:(id)arg1;

@end

