//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class AltTextContentView, NSString;

@interface AltTextView : UIView
{
    NSString *_text;
    UIView *_parentView;
    id _delegate;
    AltTextContentView *_contentView;
}

+ (void)presentText:(id)arg1 inView:(id)arg2 delegate:(id)arg3;
@property(retain, nonatomic) AltTextContentView *contentView; // @synthesize contentView=_contentView;
@property(nonatomic) __weak id delegate; // @synthesize delegate=_delegate;
@property(nonatomic) __weak UIView *parentView; // @synthesize parentView=_parentView;
@property(copy, nonatomic) NSString *text; // @synthesize text=_text;
- (void).cxx_destruct;
- (void)tap:(id)arg1;
- (void)hide;
- (void)show;
- (id)initWithFrame:(struct CGRect)arg1;

@end

