//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class AltTextView;

@interface AltTextContentView : UIView
{
    AltTextView *_container;
}

@property(nonatomic) __weak AltTextView *container; // @synthesize container=_container;
- (void).cxx_destruct;
- (void)drawRect:(struct CGRect)arg1;
- (id)initWithContainer:(id)arg1;

@end

