//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIResponder.h>

#import "RKIssuesManagerDelegate-Protocol.h"
#import "UIApplicationDelegate-Protocol.h"

@class NSDate, NSString, Reachability, RootViewController, UIWindow;

@interface AppDelegate : UIResponder <UIApplicationDelegate, RKIssuesManagerDelegate>
{
    NSDate *__enterBackgroundDate;
    Reachability *__reachability;
    _Bool __initialized;
    UIWindow *_window;
    RootViewController *_viewController;
}

@property(retain, nonatomic) RootViewController *viewController; // @synthesize viewController=_viewController;
@property(retain, nonatomic) UIWindow *window; // @synthesize window=_window;
- (void).cxx_destruct;
- (void)stopReachability;
- (void)startReachability;
- (void)resolveIssues:(id)arg1;
- (void)issuesManager:(id)arg1 didReceiveNewIssue:(id)arg2;
- (void)importOPML:(id)arg1;
- (void)applicationDidReceiveMemoryWarning:(id)arg1;
- (_Bool)application:(id)arg1 openURL:(id)arg2 sourceApplication:(id)arg3 annotation:(id)arg4;
- (void)applicationWillTerminate:(id)arg1;
- (void)application:(id)arg1 performFetchWithCompletionHandler:(CDUnknownBlockType)arg2;
- (void)applicationDidBecomeActive:(id)arg1;
- (void)applicationWillEnterForeground:(id)arg1;
- (void)applicationDidEnterBackground:(id)arg1;
- (void)applicationWillResignActive:(id)arg1;
- (void)initialSync;
- (void)initializeApplication:(id)arg1 withOptions:(id)arg2;
- (void)updateMinimumBackgroundFetchIntervalWithUsers:(id)arg1;
- (void)updateMinimumBackgroundFetchInterval:(id)arg1;
- (_Bool)application:(id)arg1 didFinishLaunchingWithOptions:(id)arg2;
- (void)checkSettingKeys;
- (void)addCustomSharers;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

