//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIApplication.h>

@class UITouch;

@interface Application : UIApplication
{
    long long __state;
    double __timeRemaining;
    UITouch *_currentTouch;
}

@property(retain, nonatomic) UITouch *currentTouch; // @synthesize currentTouch=_currentTouch;
- (void).cxx_destruct;
- (double)backgroundTimeRemaining;
- (long long)applicationState;
- (void)sendEvent:(id)arg1;
- (void)appStateDidChange:(id)arg1;
- (void)dealloc;
- (id)init;

@end

