//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "BaseWebView.h"

#import "UIWebViewDelegate-Protocol.h"

@class ArticleViewStyle, CALayer, CoreAnimator, NSString, RSDataObjectID, UIColor;
@protocol ArticleViewDelegate;

@interface ArticleView : BaseWebView <UIWebViewDelegate>
{
    RSDataObjectID *__currentItemID;
    _Bool __loading;
    CALayer *__articleAnimationLayer;
    double __animatorDiffY;
    CoreAnimator *__animator;
    _Bool __ignoreOnClick;
    _Bool _superRespondsToDidScroll;
    double __lastWidth;
    _Bool _isAnimatingScroll;
    id <ArticleViewDelegate> _articleDelegate;
    ArticleViewStyle *_style;
}

+ (id)prefFontKey;
+ (id)prefGrayscaleImagesKey;
+ (id)prefLineHeightKey;
+ (id)prefFontSizeKey;
+ (id)prefTitleAligmentKey;
+ (id)prefTitleFontSizeKey;
@property(nonatomic) _Bool isAnimatingScroll; // @synthesize isAnimatingScroll=_isAnimatingScroll;
@property(retain, nonatomic) ArticleViewStyle *style; // @synthesize style=_style;
@property(nonatomic) __weak id <ArticleViewDelegate> articleDelegate; // @synthesize articleDelegate=_articleDelegate;
- (void).cxx_destruct;
- (void)setItem:(id)arg1 withContentOffset:(struct CGPoint)arg2;
- (void)setItem:(id)arg1;
- (void)setContentOffset:(struct CGPoint)arg1;
- (void)forceArticleLayout;
- (void)scrollViewDidEndScrollingAnimation:(id)arg1;
- (void)scrollRectToVisible:(struct CGRect)arg1 animated:(_Bool)arg2;
- (void)scrollViewWillBeginDecelerating:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)sizeDidChange:(id)arg1;
- (void)didMoveToWindow;
- (void)setFrame:(struct CGRect)arg1;
- (_Bool)webView:(id)arg1 shouldStartLoadWithRequest:(id)arg2 navigationType:(long long)arg3;
- (void)webView:(id)arg1 resource:(id)arg2 didFinishLoadingFromDataSource:(id)arg3;
- (void)uiWebView:(id)arg1 resource:(id)arg2 didFinishLoadingFromDataSource:(id)arg3;
- (void)webViewDidFinishLoad:(id)arg1;
- (void)webView:(id)arg1 shareSelectionWithSender:(id)arg2;
- (void)webView:(id)arg1 presentCallOutForUrl:(id)arg2;
- (void)load;
- (id)styleBase64;
- (void)loadStyle;
- (void)painterDidChange;
@property(readonly, nonatomic) UIColor *articleBackgroundColor;
- (void)titleAlignLeft;
- (void)titleAlignCenter;
- (void)decTitleSize;
- (void)incTitleSize;
- (void)decLineHeight;
- (void)incLineHeight;
- (void)decFontSize;
- (void)incFontSize;
- (void)setFontName:(id)arg1;
@property(readonly, nonatomic, getter=isReady) _Bool ready;
- (_Bool)isLoading;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

