//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "CoreCollectionViewCell.h"

@class ThemeSwitcher;

@interface ArticleStyleThemesCell : CoreCollectionViewCell
{
    ThemeSwitcher *__switcher;
}

- (void).cxx_destruct;
- (void)layoutSubviews;
- (id)initWithReuseIdentifier:(id)arg1;

@end

