//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSDictionary, NSString, UIColor;

@interface ArticleViewStyle : NSObject
{
    float _titleSizeEM;
    UIColor *_backgroundColor;
    NSArray *_fonts;
    NSDictionary *_textFont;
    NSDictionary *_titleFont;
    NSString *_font;
    long long _fontSizePX;
    UIColor *_fontColor;
    UIColor *_tapHighlightColor;
    UIColor *_linkUnderscoreColor;
    NSString *_titleTextAlign;
    NSString *_hrStyle;
    UIColor *_hrColor;
    UIColor *_hrColorShadow;
    double _hrGradientAlphaOut;
    double _lineHeight;
    UIColor *_blockquoteBorderColor;
    UIColor *_frameLinkBackgroundColor;
}

+ (id)titleFontNameForFont:(id)arg1;
+ (id)textFontNameForFont:(id)arg1;
+ (id)fonts;
+ (void)initialize;
@property(retain, nonatomic) UIColor *frameLinkBackgroundColor; // @synthesize frameLinkBackgroundColor=_frameLinkBackgroundColor;
@property(retain, nonatomic) UIColor *blockquoteBorderColor; // @synthesize blockquoteBorderColor=_blockquoteBorderColor;
@property(nonatomic) double lineHeight; // @synthesize lineHeight=_lineHeight;
@property(nonatomic) double hrGradientAlphaOut; // @synthesize hrGradientAlphaOut=_hrGradientAlphaOut;
@property(retain, nonatomic) UIColor *hrColorShadow; // @synthesize hrColorShadow=_hrColorShadow;
@property(retain, nonatomic) UIColor *hrColor; // @synthesize hrColor=_hrColor;
@property(copy, nonatomic) NSString *hrStyle; // @synthesize hrStyle=_hrStyle;
@property(copy, nonatomic) NSString *titleTextAlign; // @synthesize titleTextAlign=_titleTextAlign;
@property(nonatomic) float titleSizeEM; // @synthesize titleSizeEM=_titleSizeEM;
@property(retain, nonatomic) UIColor *linkUnderscoreColor; // @synthesize linkUnderscoreColor=_linkUnderscoreColor;
@property(retain, nonatomic) UIColor *tapHighlightColor; // @synthesize tapHighlightColor=_tapHighlightColor;
@property(retain, nonatomic) UIColor *fontColor; // @synthesize fontColor=_fontColor;
@property(nonatomic) long long fontSizePX; // @synthesize fontSizePX=_fontSizePX;
@property(copy, nonatomic) NSString *font; // @synthesize font=_font;
@property(readonly, nonatomic) NSDictionary *titleFont; // @synthesize titleFont=_titleFont;
@property(readonly, nonatomic) NSDictionary *textFont; // @synthesize textFont=_textFont;
@property(readonly, nonatomic) NSArray *fonts; // @synthesize fonts=_fonts;
@property(retain, nonatomic) UIColor *backgroundColor; // @synthesize backgroundColor=_backgroundColor;
- (void).cxx_destruct;
@property(readonly, nonatomic) NSString *boldFontFamiliy;
@property(readonly, nonatomic) NSString *fontFamiliy;
- (id)init;

@end

