//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class ArticleView, CAShapeLayer, RKItem;

@interface ArticlePullView : UIView
{
    _Bool _trigger;
    int _edge;
    RKItem *_item;
    double _offset;
    CAShapeLayer *_arrow;
    ArticleView *_articleView;
}

@property(nonatomic) __weak ArticleView *articleView; // @synthesize articleView=_articleView;
@property(retain, nonatomic) CAShapeLayer *arrow; // @synthesize arrow=_arrow;
@property(readonly, nonatomic) _Bool trigger; // @synthesize trigger=_trigger;
@property(nonatomic) double offset; // @synthesize offset=_offset;
@property(nonatomic) int edge; // @synthesize edge=_edge;
@property(retain, nonatomic) RKItem *item; // @synthesize item=_item;
- (void).cxx_destruct;
- (void)reset;
- (void)drawRect:(struct CGRect)arg1;
- (void)layoutSubviews;
@property(readonly, nonatomic) double height;
- (void)painterDidChange;
- (id)initWithArticleView:(id)arg1;

@end

