//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "CoreViewController.h"

#import "ArticleViewDelegate-Protocol.h"
#import "ImageViewerDelegate-Protocol.h"
#import "UIGestureRecognizerDelegate-Protocol.h"
#import "UIViewControllerPreviewingDelegate-Protocol.h"
#import "WindowTapDelegate-Protocol.h"

@class ArticleNavigationBar, ArticlePullView, ArticleView, ImageViewer, NSString, PinchMobilizerView, RKItem, ShareController, Toolbar, ToolbarItem, UILongPressGestureRecognizer, UIPinchGestureRecognizer, UIView;

@interface ArticleViewController : CoreViewController <ArticleViewDelegate, WindowTapDelegate, ImageViewerDelegate, UIGestureRecognizerDelegate, UIViewControllerPreviewingDelegate>
{
    ToolbarItem *__unreadButtonItem;
    ToolbarItem *__starButtonItem;
    ToolbarItem *__prevButtonItem;
    ToolbarItem *__nextButtonItem;
    ToolbarItem *__actionButtonItem;
    ToolbarItem *__toggleLayoutButtonItem;
    UIPinchGestureRecognizer *__pinch;
    ImageViewer *__pinchImageViewer;
    struct CGRect __pinchImageRect;
    struct CGPoint __pinchImageCenter;
    struct CGRect __pinchImageTargetFrame;
    double __pinchImageLastScale;
    _Bool __pinchImageTrigger;
    RKItem *__itemToLoad;
    NSString *_readabilityContent;
    int __loadDirection;
    PinchMobilizerView *__mobilizerView;
    UIView *__themeOverlay;
    struct CGSize __lastViewFrameSize;
    _Bool _peakLoad;
    ArticleNavigationBar *_navigationBar;
    RKItem *_item;
    Toolbar *_toolbar;
    ShareController *_shareController;
    UILongPressGestureRecognizer *_longPress;
    NSString *_backButtonImage;
    ArticlePullView *_pullView;
    UIView *_barView;
    UIView *_barSeparatorView;
}

@property(readonly, nonatomic) UIView *barSeparatorView; // @synthesize barSeparatorView=_barSeparatorView;
@property(readonly, nonatomic) UIView *barView; // @synthesize barView=_barView;
@property(retain, nonatomic) ArticlePullView *pullView; // @synthesize pullView=_pullView;
@property(nonatomic) _Bool peakLoad; // @synthesize peakLoad=_peakLoad;
@property(copy, nonatomic) NSString *backButtonImage; // @synthesize backButtonImage=_backButtonImage;
@property(readonly, nonatomic) UILongPressGestureRecognizer *longPress; // @synthesize longPress=_longPress;
@property(readonly, nonatomic) __weak ShareController *shareController; // @synthesize shareController=_shareController;
@property(readonly, nonatomic) Toolbar *toolbar; // @synthesize toolbar=_toolbar;
@property(retain, nonatomic) RKItem *item; // @synthesize item=_item;
@property(readonly, nonatomic) ArticleNavigationBar *navigationBar; // @synthesize navigationBar=_navigationBar;
@property(readonly, nonatomic) NSString *readabilityContent; // @synthesize readabilityContent=_readabilityContent;
- (void).cxx_destruct;
- (void)toggleReadability:(id)arg1;
@property(readonly, nonatomic) _Bool isReadabilityLoaded;
@property(readonly, nonatomic) _Bool isReadabilityActive;
- (void)handleImagePinch:(id)arg1;
- (void)handleMobilizerPinch:(id)arg1;
- (void)handlePinch:(id)arg1;
- (void)sharePan:(id)arg1;
- (void)share:(id)arg1;
- (void)articleView:(id)arg1 shareSelectionWithSender:(id)arg2;
- (void)articleView:(id)arg1 presentCallOutForUrl:(id)arg2;
- (_Bool)loadPrev:(id)arg1 mark:(_Bool)arg2;
- (_Bool)loadPrev:(id)arg1;
- (_Bool)loadNext:(id)arg1 mark:(_Bool)arg2;
- (_Bool)loadNext:(id)arg1;
- (_Bool)scrollUp:(id)arg1 isARepeat:(_Bool)arg2;
- (_Bool)scrollDown:(id)arg1 isARepeat:(_Bool)arg2;
- (void)toggleStarred:(id)arg1;
- (void)btnToggleStarred:(id)arg1;
- (void)toggleUnread:(id)arg1;
- (void)btnToggleUnread:(id)arg1;
- (void)btnMobilizer:(id)arg1;
- (void)btnStyle:(id)arg1;
- (struct CGRect)imageViewer:(id)arg1 rectForImage:(id)arg2 withSrc:(id)arg3;
- (struct CGRect)rectForCurrentImageInView:(id)arg1;
- (CDUnknownBlockType)imageViewerWillClose:(id)arg1 animated:(_Bool)arg2;
- (CDUnknownBlockType)imageViewerWillOpen:(id)arg1 animated:(_Bool)arg2;
- (void)showToolbar:(id)arg1 animated:(_Bool)arg2;
- (void)hideToolbar:(id)arg1 animated:(_Bool)arg2;
- (void)shareObjectShouldPresentAltText:(id)arg1;
- (void)shareObjectShouldPresentImage:(id)arg1;
- (id)shareObject:(id)arg1 customContentForService:(id)arg2;
- (void)openWithBrowser:(id)arg1 externalIfNeeded:(_Bool)arg2;
- (void)shareObjectShouldOpenLink:(id)arg1;
- (void)setOverlayOpacity:(double)arg1;
- (void)barOpacity;
- (void)articleViewDidTapImage:(id)arg1;
- (_Bool)articleView:(id)arg1 shouldStartLoadWithRequest:(id)arg2;
- (void)loadArticleLinkInBrowser;
- (void)articleViewDidLoad:(id)arg1;
- (void)articleView:(id)arg1 didScroll:(id)arg2;
- (void)articleView:(id)arg1 scrollViewWillBeginDecelerating:(id)arg2;
- (void)pop:(id)arg1;
- (void)popOrPushToSelf:(id)arg1;
- (void)slidingController:(id)arg1 didSnapToViewController:(id)arg2;
- (void)slidingController:(id)arg1 willSnapToViewController:(id)arg2;
- (void)handleCustomRightPan:(id)arg1;
- (id)slidingController:(id)arg1 handlerForRightPan:(id)arg2;
- (void)longPress:(id)arg1;
- (void)animate:(int)arg1 withImage:(id)arg2 imageFrame:(struct CGRect)arg3;
- (void)markReadAfterKeyUp;
- (void)setItem:(id)arg1 mark:(_Bool)arg2;
- (_Bool)canSnapForInterfaceOrientation:(long long)arg1;
- (void)viewWillLayoutSubviews;
- (double)widthForInterfaceOrientation:(long long)arg1;
- (id)coloredImage:(id)arg1;
@property(readonly, nonatomic) ArticleView *articleView;
- (void)didReceiveMemoryWarning;
- (void)willRotateToInterfaceOrientation:(long long)arg1 duration:(double)arg2;
- (void)validate;
- (void)handleNavigationPan:(id)arg1;
- (_Bool)gestureRecognizerShouldBegin:(id)arg1;
- (void)painterDidChange:(id)arg1;
- (void)toggleLayout:(id)arg1;
- (void)didMoveToParentViewController:(id)arg1;
- (void)updateLayoutToggable;
- (void)viewDidLoad;
- (void)viewDidLayoutSubviews;
- (void)updatePadding;
- (void)window:(id)arg1 didReceiveTap:(id)arg2;
- (void)articleView:(id)arg1 didMoveToWindow:(id)arg2;
- (id)loadContentView;
- (void)didDeleteUser:(id)arg1;
- (void)restore;
- (void)validateMobilizerButton;
- (void)validateMobilizerButtonVisibility;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)dealloc;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic, getter=isReadabilityActive) _Bool readabilityActive;
@property(readonly, nonatomic, getter=isReadabilityLoaded) _Bool readabilityLoaded;
@property(readonly) Class superclass;

@end

