//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIWebView.h>

#import "UIGestureRecognizerDelegate-Protocol.h"

@class NSString, UILongPressGestureRecognizer;

@interface BaseWebView : UIWebView <UIGestureRecognizerDelegate>
{
    _Bool __notificationAdded;
    id __cache;
    UILongPressGestureRecognizer *__calloutLongPress;
}

+ (id)shareMenuItem;
- (void).cxx_destruct;
- (id)toENML:(id)arg1;
- (void)__panel:(id)arg1;
- (void)__popover:(id)arg1;
- (void)__sheet8_delayed:(id)arg1;
- (void)__sheet8:(id)arg1;
- (void)dumpSubviews:(id)arg1 pre:(id)arg2;
- (void)didMoveToWindow;
- (id)hrefAtLocation:(struct CGPoint)arg1;
- (_Bool)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (void)callout:(id)arg1;
- (id)titleForLink:(id)arg1;
- (id)imageWithSrc:(id)arg1;
- (void)useCache:(id)arg1;
- (_Bool)canPerformAction:(SEL)arg1 withSender:(id)arg2;
- (id)selectedHTML;
- (id)selectedText;
- (void)shareSelection:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

