//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSString, UIImage;

@interface Bezel : UIView
{
    double __imageWidth;
    NSString *_title;
    UIImage *_image;
}

+ (void)flashWithTitle:(id)arg1 image:(id)arg2 inView:(id)arg3;
@property(readonly, nonatomic) UIImage *image; // @synthesize image=_image;
@property(readonly, nonatomic) NSString *title; // @synthesize title=_title;
- (void).cxx_destruct;
- (void)__closeFrom:(struct CGPoint)arg1 to:(struct CGPoint)arg2;
- (void)flashInView:(id)arg1;
- (void)drawRect:(struct CGRect)arg1;
- (id)initWithTitle:(id)arg1 image:(id)arg2;

@end

