//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "CoreViewController.h"

#import "SFSafariViewControllerDelegate-Protocol.h"

@class NSString, RKSafariViewController, UIView;

@interface BrowserViewController : CoreViewController <SFSafariViewControllerDelegate>
{
    UIView *__leftPanView;
    NSString *__userUrl;
    RKSafariViewController *__safariViewController;
    _Bool _hasWebView;
}

@property(nonatomic) _Bool hasWebView; // @synthesize hasWebView=_hasWebView;
- (void).cxx_destruct;
- (void)slidingController:(id)arg1 willSnapToViewController:(id)arg2;
- (void)slidingController:(id)arg1 didSnapToViewController:(id)arg2;
- (void)safariViewControllerDidFinish:(id)arg1;
- (double)widthForInterfaceOrientation:(long long)arg1;
- (int)loadArticleRequest:(id)arg1 mobilized:(_Bool)arg2 externalIfNeeded:(_Bool)arg3;
- (int)loadArticleRequest:(id)arg1 mobilized:(_Bool)arg2;
- (int)loadArticleRequest:(id)arg1;
- (void)loadRequest:(id)arg1 mobilzed:(_Bool)arg2;
- (void)loadRequest:(id)arg1;
- (void)loadURL:(id)arg1;
- (void)loadUrl:(id)arg1;
- (void)articleDidChange:(id)arg1;
- (void)openLinksSettingDidChange:(id)arg1;
- (void)discardWebView;
- (void)rootDidLayout;
- (void)viewDidLayoutSubviews;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;
- (void)dealloc;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

