//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "WebViewNavigationBar.h"

@class BrowserMobilizerButton, UIButton;

@interface BrowserViewNavigationBar : WebViewNavigationBar
{
    UIButton *_backButton;
    UIButton *_actionButton;
    UIButton *_reloadButton;
    UIButton *_dragHandle;
    BrowserMobilizerButton *_mobilizerButton;
}

@property(readonly, nonatomic) BrowserMobilizerButton *mobilizerButton; // @synthesize mobilizerButton=_mobilizerButton;
@property(readonly, nonatomic) UIButton *dragHandle; // @synthesize dragHandle=_dragHandle;
@property(readonly, nonatomic) UIButton *reloadButton; // @synthesize reloadButton=_reloadButton;
@property(readonly, nonatomic) UIButton *actionButton; // @synthesize actionButton=_actionButton;
@property(readonly, nonatomic) UIButton *backButton; // @synthesize backButton=_backButton;
- (void).cxx_destruct;
- (id)initWithFrameView:(id)arg1;

@end

