//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "MobilizerButton.h"

@interface BrowserMobilizerButton : MobilizerButton
{
}

- (id)painter;

@end

