//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#pragma mark Blocks

typedef void (^CDUnknownBlockType)(void); // return type and parameters are unknown

#pragma mark Named Structures

struct CGPoint {
    double x;
    double y;
};

struct CGRect {
    struct CGPoint origin;
    struct CGSize size;
};

struct CGSize {
    double width;
    double height;
};

struct UIEdgeInsets {
    double top;
    double left;
    double bottom;
    double right;
};

struct _NSRange {
    unsigned long long _field1;
    unsigned long long _field2;
};

struct in_addr {
    unsigned int _field1;
};

struct selBlockPair {
    SEL _field1;
    CDUnknownBlockType _field2;
};

struct sockaddr_in {
    unsigned char _field1;
    unsigned char _field2;
    unsigned short _field3;
    struct in_addr _field4;
    char _field5[8];
};

#pragma mark Typedef'd Structures

typedef struct {
    _Bool hasCustomItemHeights;
    _Bool hasCustomItemHeights_delegate;
    _Bool hasCustomItemHeights_object;
} CDStruct_6398ef64;

typedef struct {
    long long numberOfColumns;
} CDStruct_a3deaebe;

typedef struct {
    struct CGPoint start;
    struct CGPoint target;
    struct CGPoint current;
    struct CGPoint undamped;
} CDStruct_848f5a37;

