//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "CoreCollectionViewCell.h"

@interface CollectionViewCell : CoreCollectionViewCell
{
}

- (_Bool)insetsFrameFromSafeArea;
- (void)didDrawContentViewRect:(struct CGRect)arg1;

@end

