//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "CoreCollectionViewController.h"

#import "ScrollHeaderViewDelegate-Protocol.h"

@class CollectionViewHeader, NSString, Toolbar;

@interface CollectionViewController : CoreCollectionViewController <ScrollHeaderViewDelegate>
{
    CollectionViewHeader *_headerView;
    Toolbar *_toolbar;
}

@property(readonly, nonatomic) Toolbar *toolbar; // @synthesize toolbar=_toolbar;
@property(readonly, nonatomic) CollectionViewHeader *headerView; // @synthesize headerView=_headerView;
- (void).cxx_destruct;
- (void)setOverlayOpacity:(double)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)updateBarContentOpacity;
- (void)scrollHeaderViewDidTriggerPull:(id)arg1;
- (id)scrollHeaderViewScrollView:(id)arg1;
- (id)scrollHeaderViewPullTitle:(id)arg1;
- (_Bool)scrollHeaderViewCanPull:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)layoutHeader;
- (void)viewDidLoad;
@property(readonly, nonatomic) _Bool hasToolbar;
@property(readonly, nonatomic) _Bool hasNavigationHeaderViewOnly;
@property(readonly, nonatomic) _Bool hasHeaderView;
- (void)painterDidChange:(id)arg1;
- (void)__painterDidChange:(id)arg1;
- (Class)headerViewClass;
- (void)didReceiveMemoryWarning;
- (void)dealloc;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

