//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "ScrollHeaderView.h"

@interface CollectionViewHeader : ScrollHeaderView
{
}

- (void)setOriginY:(double)arg1;
- (double)originY;

@end

