//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface CoreCollectionViewLayout : NSObject
{
    double _sectionSpacing;
    struct CGSize _itemSize;
    struct CGSize _itemSpacing;
}

+ (id)gridLayoutWithItemSize:(struct CGSize)arg1 itemSpacing:(struct CGSize)arg2;
+ (id)listLayoutWithRowHeight:(double)arg1 rowSpacing:(double)arg2;
@property(nonatomic) double sectionSpacing; // @synthesize sectionSpacing=_sectionSpacing;
@property(nonatomic) struct CGSize itemSpacing; // @synthesize itemSpacing=_itemSpacing;
@property(nonatomic) struct CGSize itemSize; // @synthesize itemSize=_itemSize;
- (id)init;

@end

