//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "UIScrollViewDelegate-Protocol.h"

@class CoreCollectionView, CoreCollectionViewCell, NSIndexPath, NSString, UIColor;

@protocol CoreCollectionViewDelegate <UIScrollViewDelegate>
- (NSString *)collectionView:(CoreCollectionView *)arg1 reuseIdentifierForCellAtIndexPath:(NSIndexPath *)arg2 representedObject:(id)arg3;

@optional
- (UIColor *)collectionView:(CoreCollectionView *)arg1 borderColorForSlider:(int)arg2 forCell:(CoreCollectionViewCell *)arg3;
- (UIColor *)collectionView:(CoreCollectionView *)arg1 backgroundColorForSlider:(int)arg2 forCell:(CoreCollectionViewCell *)arg3;
- (void)collectionView:(CoreCollectionView *)arg1 endSliderForCell:(CoreCollectionViewCell *)arg2;
- (void)collectionView:(CoreCollectionView *)arg1 cancelSliderForCell:(CoreCollectionViewCell *)arg2;
- (_Bool)collectionView:(CoreCollectionView *)arg1 commitSlider:(int)arg2 forCell:(CoreCollectionViewCell *)arg3;
- (void)collectionView:(CoreCollectionView *)arg1 beginSliderForCell:(CoreCollectionViewCell *)arg2;
- (id)collectionView:(CoreCollectionView *)arg1 imageForSlider:(int)arg2 forCell:(CoreCollectionViewCell *)arg3;
- (_Bool)collectionView:(CoreCollectionView *)arg1 shouldEnableSliderForCell:(CoreCollectionViewCell *)arg2;
- (void)collectionView:(CoreCollectionView *)arg1 touchesEnded:(id)arg2 cancelled:(_Bool)arg3;
- (void)collectionView:(CoreCollectionView *)arg1 touchesBegan:(id)arg2;
- (void)collectionView:(CoreCollectionView *)arg1 didDeselectItemWithRepresentedObject:(id)arg2 atIndexPath:(NSIndexPath *)arg3;
- (void)collectionView:(CoreCollectionView *)arg1 willDeselectItemWithRepresentedObject:(id)arg2 atIndexPath:(NSIndexPath *)arg3;
- (void)collectionView:(CoreCollectionView *)arg1 didSelectItemWithRepresentedObject:(id)arg2 atIndexPath:(NSIndexPath *)arg3;
- (void)collectionView:(CoreCollectionView *)arg1 willSelectItemWithRepresentedObject:(id)arg2 atIndexPath:(NSIndexPath *)arg3;
- (_Bool)collectionView:(CoreCollectionView *)arg1 shouldHighlightItemWithRepresentedObject:(id)arg2 atIndexPath:(NSIndexPath *)arg3;
- (double)collectionView:(CoreCollectionView *)arg1 heightForFooterInSection:(long long)arg2 representedObject:(id)arg3;
- (double)collectionView:(CoreCollectionView *)arg1 heightForHeaderInSection:(long long)arg2 representedObject:(id)arg3;
- (double)collectionView:(CoreCollectionView *)arg1 heightForItemAtIndexPath:(NSIndexPath *)arg2 representedObject:(id)arg3;
- (_Bool)collectionViewItemsRepondToHeightSelector:(CoreCollectionView *)arg1;
- (NSString *)collectionView:(CoreCollectionView *)arg1 reuseIdentifierForFooterInSection:(long long)arg2 representedObject:(id)arg3;
- (NSString *)collectionView:(CoreCollectionView *)arg1 reuseIdentifierForHeaderInSection:(long long)arg2 representedObject:(id)arg3;
- (void)collectionViewDidReload:(CoreCollectionView *)arg1;
@end

