//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIPanGestureRecognizer.h>

#import "UIGestureRecognizerDelegate-Protocol.h"

@class NSString;

@interface CoreCollectionViewCellSlideGestureRecognizer : UIPanGestureRecognizer <UIGestureRecognizerDelegate>
{
    double __tx;
    struct CGPoint __p;
    _Bool __active;
    double __diff;
    double _translationX;
}

@property(readonly, nonatomic) double translationX; // @synthesize translationX=_translationX;
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

