//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "CoreCollectionViewCell.h"

@class RSFormCell;

@interface CoreFormViewCell : CoreCollectionViewCell
{
    _Bool _highlights;
    RSFormCell *_info;
}

+ (id)cellWithInfo:(id)arg1;
@property(readonly, nonatomic) _Bool highlights; // @synthesize highlights=_highlights;
@property(readonly, nonatomic) RSFormCell *info; // @synthesize info=_info;
- (void).cxx_destruct;
- (void)drawContentViewRect:(struct CGRect)arg1;
@property(readonly, nonatomic) double labelWidth;
@property(readonly, nonatomic) id input;
- (id)initWithInfo:(id)arg1;

@end

