//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class CoreCollectionViewDataSource, CoreCollectionViewLayout;

@interface CoreCollectionViewLayoutUpdate : NSObject
{
    _Bool _animated;
    _Bool _useFolderAnimation;
    int _clear;
    int _appear;
    CoreCollectionViewLayout *_layout;
    CoreCollectionViewDataSource *_dataSource;
}

@property(nonatomic) _Bool useFolderAnimation; // @synthesize useFolderAnimation=_useFolderAnimation;
@property(nonatomic) int appear; // @synthesize appear=_appear;
@property(nonatomic) int clear; // @synthesize clear=_clear;
@property(retain, nonatomic) CoreCollectionViewDataSource *dataSource; // @synthesize dataSource=_dataSource;
@property(retain, nonatomic) CoreCollectionViewLayout *layout; // @synthesize layout=_layout;
@property(nonatomic) _Bool animated; // @synthesize animated=_animated;
- (void).cxx_destruct;
@property(readonly, nonatomic) _Bool appearingHorizontal;
@property(readonly, nonatomic) _Bool appearing;
@property(readonly, nonatomic) _Bool clearingHorizontal;
@property(readonly, nonatomic) _Bool clearing;
- (id)init;

@end

