//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class CoreCollectionView, CoreCollectionViewLayoutCache, CoreCollectionViewLayoutUpdate, NSMutableArray, UIView;

@interface CoreCollectionViewLayoutUpdater : NSObject
{
    int __updateCount;
    UIView *__dummyView;
    double __previousAnimationDelay;
    _Bool _needsDisplay;
    _Bool _waitingForSetupCompletion;
    CoreCollectionView *_collectionView;
    double _defaultRotationAnimationDuration;
    CoreCollectionViewLayoutCache *_cache;
    CoreCollectionViewLayoutCache *_oldCache;
    double _minAnimationDelayStep;
    NSMutableArray *_updates;
    UIView *_dummyView;
    CoreCollectionViewLayoutUpdate *_currentUpdate;
}

@property(readonly, nonatomic) CoreCollectionViewLayoutUpdate *currentUpdate; // @synthesize currentUpdate=_currentUpdate;
@property(readonly, nonatomic) __weak UIView *dummyView; // @synthesize dummyView=_dummyView;
@property(readonly, nonatomic) _Bool waitingForSetupCompletion; // @synthesize waitingForSetupCompletion=_waitingForSetupCompletion;
@property(readonly, nonatomic) _Bool needsDisplay; // @synthesize needsDisplay=_needsDisplay;
@property(readonly, nonatomic) NSMutableArray *updates; // @synthesize updates=_updates;
@property(nonatomic) double minAnimationDelayStep; // @synthesize minAnimationDelayStep=_minAnimationDelayStep;
@property(readonly, nonatomic) CoreCollectionViewLayoutCache *oldCache; // @synthesize oldCache=_oldCache;
@property(readonly, nonatomic) CoreCollectionViewLayoutCache *cache; // @synthesize cache=_cache;
@property(nonatomic) double defaultRotationAnimationDuration; // @synthesize defaultRotationAnimationDuration=_defaultRotationAnimationDuration;
@property(readonly, nonatomic) __weak CoreCollectionView *collectionView; // @synthesize collectionView=_collectionView;
- (void).cxx_destruct;
- (void)animateItem:(id)arg1 delay:(double)arg2 speed:(double)arg3;
- (void)animateItem:(id)arg1 delay:(double)arg2;
- (void)animateItem:(id)arg1;
- (void)clean:(_Bool)arg1;
- (void)clean;
- (void)updateAnimatedAppear;
- (void)updateAnimatedClear;
- (void)updateAnimated;
- (void)__deleteOrUpdate:(id)arg1 type:(int)arg2;
- (void)__insertOrUpdate:(id)arg1 type:(int)arg2;
- (void)update;
- (void)enumerateItemsWithBlock:(CDUnknownBlockType)arg1 done:(CDUnknownBlockType)arg2;
- (void)enumerateSectionsWithBlock:(CDUnknownBlockType)arg1 done:(CDUnknownBlockType)arg2;
- (void)__layout:(id)arg1;
- (void)layout:(id)arg1;
- (void)clear:(_Bool)arg1 to:(int)arg2;
- (void)addUpdate:(id)arg1;
@property(readonly, nonatomic, getter=isUpdating) _Bool updating;
- (void)setDefaultRotationAnimationDuration;
- (id)initWithCollectionView:(id)arg1;

@end

