//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "CoreCollectionReusableView.h"

@class CoreAnimator, CoreCollectionViewCellSlideGestureRecognizer, CoreCollectionViewSliderImageView, UIView;
@protocol CoreCollectionViewDelegate;

@interface CoreCollectionViewCell : CoreCollectionReusableView
{
    CoreCollectionViewCellSlideGestureRecognizer *__sliderPan;
    int __sliding;
    CoreAnimator *__slidingAnimator;
    id <CoreCollectionViewDelegate> __sliderDelegate;
    UIView *__sliderView;
    CoreCollectionViewSliderImageView *__sliderLeftView;
    CoreCollectionViewSliderImageView *__sliderRightView;
    double __sliderCommitTrigger;
    _Bool _selected;
    _Bool _highlighted;
}

@property(nonatomic, getter=isHighlighted) _Bool highlighted; // @synthesize highlighted=_highlighted;
@property(nonatomic, getter=isSelected) _Bool selected; // @synthesize selected=_selected;
- (void).cxx_destruct;
- (void)handleSlide:(id)arg1;
- (void)__sliderClean:(_Bool)arg1;
- (void)__sliderEnd;
- (void)__sliderCancel;
- (_Bool)__sliderCommit:(int)arg1;
- (void)__sliderBegin;
- (id)__sliderImageFor:(int)arg1;
- (_Bool)__sliderEnabled;
- (void)cancelSlide;
- (void)initMobile;
@property(readonly, nonatomic) _Bool insetsFrameFromSafeArea;
- (void)didHighlightOrSelect:(_Bool)arg1;
@property(readonly, nonatomic, getter=isHightlightedOrSelected) _Bool hightlightedOrSelected;
- (void)setHighlighted:(_Bool)arg1 animated:(_Bool)arg2;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
@property(readonly, nonatomic) _Bool slidable;
- (void)prepareForReuse;
- (id)initWithReuseIdentifier:(id)arg1;
- (void)painterDidChange;

@end

