//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@interface CoreFrameView : UIView
{
    double __paddingTop;
    double __paddingBottom;
    _Bool _phoneFadesTop;
    _Bool _phoneFadesBottom;
    _Bool _logLayout;
    UIView *_contentView;
    UIView *_overlay;
    double _contentViewPaddingTop;
    double _contentViewPaddingBottom;
    UIView *_divider;
    UIView *_contentContainerView;
    UIView *_shadow;
    CoreFrameView *_nextFrameView;
}

+ (double)statusBarHeight;
@property(nonatomic) __weak CoreFrameView *nextFrameView; // @synthesize nextFrameView=_nextFrameView;
@property(nonatomic) _Bool logLayout; // @synthesize logLayout=_logLayout;
@property(nonatomic) _Bool phoneFadesBottom; // @synthesize phoneFadesBottom=_phoneFadesBottom;
@property(nonatomic) _Bool phoneFadesTop; // @synthesize phoneFadesTop=_phoneFadesTop;
@property(retain, nonatomic) UIView *shadow; // @synthesize shadow=_shadow;
@property(readonly, nonatomic) UIView *contentContainerView; // @synthesize contentContainerView=_contentContainerView;
@property(readonly, nonatomic) UIView *divider; // @synthesize divider=_divider;
@property(nonatomic) double contentViewPaddingBottom; // @synthesize contentViewPaddingBottom=_contentViewPaddingBottom;
@property(nonatomic) double contentViewPaddingTop; // @synthesize contentViewPaddingTop=_contentViewPaddingTop;
@property(readonly, nonatomic) UIView *overlay; // @synthesize overlay=_overlay;
@property(retain, nonatomic) UIView *contentView; // @synthesize contentView=_contentView;
- (void).cxx_destruct;
- (void)setOverlayOpacity:(double)arg1;
- (void)didMoveToWindow;
- (void)addSubview:(id)arg1;
- (struct CGImage *)shadowImageRef;
- (void)setPreviousFramePaddingTop:(double)arg1 bottom:(double)arg2;
- (void)setPaddingTop:(double)arg1 bottom:(double)arg2;
- (void)layoutSubviews;
- (void)setAutoresizingMask:(unsigned long long)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

