//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "CoreCollectionViewController.h"

@class NSArray, RSForm;

@interface CoreFormViewController : CoreCollectionViewController
{
    RSForm *_form;
    NSArray *_sections;
}

+ (id)controllerWithForm:(id)arg1;
@property(readonly, nonatomic) NSArray *sections; // @synthesize sections=_sections;
@property(retain, nonatomic) RSForm *form; // @synthesize form=_form;
- (void).cxx_destruct;
- (void)endModal;
- (void)startModal;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;
- (id)initWithForm:(id)arg1;

@end

