//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSMutableArray;

@interface CoreCollectionViewDataSource : NSObject
{
    _Bool _updating;
    NSMutableArray *_sections;
}

@property(readonly, nonatomic) _Bool updating; // @synthesize updating=_updating;
@property(readonly, nonatomic) NSMutableArray *sections; // @synthesize sections=_sections;
- (void).cxx_destruct;
- (void)deleteItemAtIndexPath:(id)arg1;
- (void)insertItem:(id)arg1 atIndexPath:(id)arg2;
- (void)addItem:(id)arg1;
- (void)deleteSectionAtIndex:(long long)arg1;
- (void)insertSection:(id)arg1 withObjects:(id)arg2 atIndex:(long long)arg3;
- (void)addSection:(id)arg1 withObjects:(id)arg2;
- (void)endUpdates;
- (void)beginUpdates;
@property(readonly, nonatomic) NSArray *orderedObjects;
- (long long)sectionForFooterObject:(id)arg1;
- (long long)sectionForHeaderObject:(id)arg1;
- (id)indexPathForObject:(id)arg1;
- (id)footerObjectInSection:(long long)arg1;
- (id)headerObjectInSection:(long long)arg1;
- (id)objectAtIndexPath:(id)arg1;
- (id)itemsInSection:(long long)arg1;
- (long long)numberOfItemsInSection:(long long)arg1;
@property(readonly, nonatomic) long long numberOfSections;
- (id)init;

@end

