//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class CoreAnimator, CoreCollectionReusableContentView, CoreCollectionViewLayoutUpdateItem, NSIndexPath, NSString;

@interface CoreCollectionReusableView : UIView
{
    id __representedObject;
    NSIndexPath *__previousIndexPath;
    _Bool _clearing;
    _Bool _sticky;
    _Bool _stickyBefore;
    _Bool _reusable;
    _Bool _animatingPosition;
    CoreCollectionReusableContentView *_contentView;
    NSIndexPath *_indexPath;
    NSString *_reuseIdentifier;
    long long _zPositionDefault;
    CoreAnimator *_animator;
    CoreCollectionViewLayoutUpdateItem *_animatorItem;
}

@property(nonatomic) _Bool animatingPosition; // @synthesize animatingPosition=_animatingPosition;
@property(nonatomic) __weak CoreCollectionViewLayoutUpdateItem *animatorItem; // @synthesize animatorItem=_animatorItem;
@property(nonatomic) __weak CoreAnimator *animator; // @synthesize animator=_animator;
@property(nonatomic) _Bool reusable; // @synthesize reusable=_reusable;
@property(nonatomic) long long zPositionDefault; // @synthesize zPositionDefault=_zPositionDefault;
@property(readonly, copy, nonatomic) NSString *reuseIdentifier; // @synthesize reuseIdentifier=_reuseIdentifier;
@property(nonatomic) _Bool stickyBefore; // @synthesize stickyBefore=_stickyBefore;
@property(nonatomic) _Bool sticky; // @synthesize sticky=_sticky;
@property(nonatomic) _Bool clearing; // @synthesize clearing=_clearing;
@property(copy, nonatomic) NSIndexPath *indexPath; // @synthesize indexPath=_indexPath;
@property(readonly, nonatomic) CoreCollectionReusableContentView *contentView; // @synthesize contentView=_contentView;
- (void).cxx_destruct;
- (void)setContentViewNeedsDisplay;
- (void)didDrawContentViewRect:(struct CGRect)arg1;
- (void)drawContentViewRect:(struct CGRect)arg1;
- (id)previousIndexPath;
- (void)prepareForReuse;
- (id)representedObject;
- (void)setRepresentedObject:(id)arg1;
@property(readonly, nonatomic) long long section;
- (id)initWithReuseIdentifier:(id)arg1;
- (void)painterDidChange;

@end

