//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface CorePainter : NSObject
{
}

+ (id)painter;
+ (void)setCurrentPainter:(id)arg1 notify:(_Bool)arg2;
+ (void)setCurrentPainter:(id)arg1;
+ (id)currentPainter;
@property(readonly, nonatomic) double scale;

@end

