//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class CoreCollectionReusableView;

@interface CoreCollectionViewLayoutUpdateItem : NSObject
{
    _Bool _hasSuperView;
    _Bool _hasFromFrame;
    _Bool _hasToFrame;
    _Bool _clearing;
    _Bool _appearing;
    int _type;
    CoreCollectionReusableView *_view;
    double _fromZPosition;
    double _toZPosition;
    double _fromOpacity;
    double _toOpacity;
    struct CGRect _fromFrame;
    struct CGRect _toFrame;
}

+ (id)item;
@property(nonatomic) _Bool appearing; // @synthesize appearing=_appearing;
@property(nonatomic) _Bool clearing; // @synthesize clearing=_clearing;
@property(nonatomic) int type; // @synthesize type=_type;
@property(nonatomic) _Bool hasToFrame; // @synthesize hasToFrame=_hasToFrame;
@property(nonatomic) _Bool hasFromFrame; // @synthesize hasFromFrame=_hasFromFrame;
@property(nonatomic) _Bool hasSuperView; // @synthesize hasSuperView=_hasSuperView;
@property(nonatomic) double toOpacity; // @synthesize toOpacity=_toOpacity;
@property(nonatomic) double fromOpacity; // @synthesize fromOpacity=_fromOpacity;
@property(nonatomic) double toZPosition; // @synthesize toZPosition=_toZPosition;
@property(nonatomic) double fromZPosition; // @synthesize fromZPosition=_fromZPosition;
@property(nonatomic) struct CGRect toFrame; // @synthesize toFrame=_toFrame;
@property(nonatomic) struct CGRect fromFrame; // @synthesize fromFrame=_fromFrame;
@property(retain, nonatomic) CoreCollectionReusableView *view; // @synthesize view=_view;
- (void).cxx_destruct;
@property(readonly, nonatomic) _Bool isDelete;
@property(readonly, nonatomic) _Bool isInsert;
@property(readonly, nonatomic) _Bool isUpdate;
@property(readonly, nonatomic) _Bool isCell;
- (id)init;

@end

