//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCopying-Protocol.h"

@class NSArray;

@interface CorePrimitiveArray : NSObject <NSCopying>
{
    struct __CFArray *_cf_array;
}

+ (id)arrayWithInitialCapacity:(long long)arg1;
+ (id)array;
+ (id)withNSArray:(id)arg1;
- (long long)lastValue;
- (long long)valueAtIndex:(long long)arg1;
- (void)removeLastValue;
- (void)removeAllValues;
- (void)removeValueAtIndex:(long long)arg1;
- (void)moveValueAtIndex:(long long)arg1 toIndex:(long long)arg2;
- (void)replaceValueAtIndex:(long long)arg1 withValue:(long long)arg2;
- (void)insertValue:(long long)arg1 atIndex:(long long)arg2;
- (void)addValue:(long long)arg1;
- (long long)sumFrom:(long long)arg1 includingFromIndex:(_Bool)arg2;
- (long long)sumTo:(long long)arg1 includingToIndex:(_Bool)arg2;
- (long long)sum;
@property(readonly, nonatomic) long long count;
- (id)description;
- (void)resetWithCapacity:(long long)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)dealloc;
- (id)initWithInitialCapacity:(long long)arg1;
- (id)init;
@property(readonly, nonatomic) NSArray *NSArray;

@end

