//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "CoreViewController.h"

#import "CoreCollectionViewDelegate-Protocol.h"

@class CoreCollectionView, NSString;

@interface CoreCollectionViewController : CoreViewController <CoreCollectionViewDelegate>
{
}

- (id)collectionView:(id)arg1 reuseIdentifierForCellAtIndexPath:(id)arg2 representedObject:(id)arg3;
- (void)didRotateFromInterfaceOrientation:(long long)arg1;
- (void)willAnimateRotationToInterfaceOrientation:(long long)arg1 duration:(double)arg2;
- (void)willRotateToInterfaceOrientation:(long long)arg1 duration:(double)arg2;
- (void)scrollViewDidScroll:(id)arg1;
@property(readonly, nonatomic) CoreCollectionView *collectionView;
- (void)viewDidLoad;
- (id)loadContentView;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

