//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIScrollView.h>

@class CoreCollectionViewCell, CoreCollectionViewDataSource, CoreCollectionViewLayout, CoreCollectionViewLayoutUpdater, NSArray, NSIndexPath, NSMutableDictionary, UIView;
@protocol CoreCollectionViewDelegate;

@interface CoreCollectionView : UIScrollView
{
    double __scrollStartOffsetY;
    _Bool _tryToKeepVisibleRowsOnBoundsChange;
    _Bool _tryToKeepVisibleRowsOnReload;
    int _updatesDisabled;
    UIView *_contentContainerView;
    CoreCollectionViewLayoutUpdater *_updater;
    double _horizontalTap;
    id _selectedObject;
    NSMutableDictionary *_cacheForItemWithReuseIdentifier;
    NSMutableDictionary *_cacheForSectionHeaderWithReuseIdentifier;
    NSMutableDictionary *_cacheForSectionFooterWithReuseIdentifier;
    CoreCollectionViewCell *_highlightedCell;
    struct CGPoint _horizontalTapLocation;
    struct UIEdgeInsets _contentPadding;
}

@property(readonly, nonatomic) int updatesDisabled; // @synthesize updatesDisabled=_updatesDisabled;
@property(readonly, nonatomic) CoreCollectionViewCell *highlightedCell; // @synthesize highlightedCell=_highlightedCell;
@property(readonly, nonatomic) NSMutableDictionary *cacheForSectionFooterWithReuseIdentifier; // @synthesize cacheForSectionFooterWithReuseIdentifier=_cacheForSectionFooterWithReuseIdentifier;
@property(readonly, nonatomic) NSMutableDictionary *cacheForSectionHeaderWithReuseIdentifier; // @synthesize cacheForSectionHeaderWithReuseIdentifier=_cacheForSectionHeaderWithReuseIdentifier;
@property(readonly, nonatomic) NSMutableDictionary *cacheForItemWithReuseIdentifier; // @synthesize cacheForItemWithReuseIdentifier=_cacheForItemWithReuseIdentifier;
@property(retain, nonatomic) id selectedObject; // @synthesize selectedObject=_selectedObject;
@property(readonly, nonatomic) struct CGPoint horizontalTapLocation; // @synthesize horizontalTapLocation=_horizontalTapLocation;
@property(readonly, nonatomic) double horizontalTap; // @synthesize horizontalTap=_horizontalTap;
@property(nonatomic) struct UIEdgeInsets contentPadding; // @synthesize contentPadding=_contentPadding;
@property(readonly, nonatomic) CoreCollectionViewLayoutUpdater *updater; // @synthesize updater=_updater;
@property(nonatomic) _Bool tryToKeepVisibleRowsOnReload; // @synthesize tryToKeepVisibleRowsOnReload=_tryToKeepVisibleRowsOnReload;
@property(nonatomic) _Bool tryToKeepVisibleRowsOnBoundsChange; // @synthesize tryToKeepVisibleRowsOnBoundsChange=_tryToKeepVisibleRowsOnBoundsChange;
@property(readonly, nonatomic) UIView *contentContainerView; // @synthesize contentContainerView=_contentContainerView;
- (void).cxx_destruct;
- (void)addReusableStickyView:(id)arg1;
- (void)addReusableView:(id)arg1;
- (void)queueSectionFooterForReuse:(id)arg1;
- (void)queueSectionHeaderForReuse:(id)arg1;
- (void)queueCellForReuse:(id)arg1;
- (id)dequeueReusableViewWithReuseIdentifier:(id)arg1 forFooterInSection:(long long)arg2 representedObject:(id)arg3;
- (id)dequeueReusableViewWithReuseIdentifier:(id)arg1 forHeaderInSection:(long long)arg2 representedObject:(id)arg3;
- (id)dequeueReusableCellWithReuseIdentifier:(id)arg1 forIndexPath:(id)arg2 representedObject:(id)arg3;
- (Class)classForSectionFooterWithReuseIdentifier:(id)arg1;
- (Class)classForSectionHeaderWithReuseIdentifier:(id)arg1;
- (Class)classForItemWithReuseIdentifier:(id)arg1;
- (void)registerClass:(Class)arg1 forSectionFooterWithReuseIdentifier:(id)arg2;
- (void)registerClass:(Class)arg1 forSectionHeaderWithReuseIdentifier:(id)arg2;
- (void)registerClass:(Class)arg1 forItemWithReuseIdentifier:(id)arg2;
@property(readonly, nonatomic) NSArray *allReusableViews;
@property(readonly, nonatomic) NSArray *visibleSectionFooters;
@property(readonly, nonatomic) NSArray *visibleSectionHeaders;
@property(readonly, nonatomic) NSArray *visibleCells;
- (id)cellForItemAtIndexPath:(id)arg1;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
@property(readonly, nonatomic, getter=isScrolling) _Bool scrolling;
- (void)__clearSelectedCell:(_Bool)arg1;
- (void)__clearCell:(id)arg1 notify:(_Bool)arg2;
- (void)__clearHighlightedCell:(id)arg1 notify:(_Bool)arg2;
- (void)__highlightCell:(id)arg1 notify:(_Bool)arg2;
- (void)__selectCell:(id)arg1 notify:(_Bool)arg2;
- (id)__selectedCell;
@property(readonly, nonatomic) NSIndexPath *indexPathForHighlightedObject;
@property(readonly, nonatomic) id highlightedObject;
@property(readonly, nonatomic) NSIndexPath *indexPathForSelectedObject;
- (void)presetSelectedObjectForNextReload:(id)arg1;
- (void)deselectItemAtIndexPath:(id)arg1;
- (void)selectItemAtIndexPath:(id)arg1;
- (void)clear:(_Bool)arg1 to:(int)arg2 deselect:(_Bool)arg3;
- (void)appearWithDataSource:(id)arg1 animated:(_Bool)arg2 from:(int)arg3;
- (void)setContentPadding:(struct UIEdgeInsets)arg1 animated:(_Bool)arg2;
- (void)setLayout:(id)arg1 animated:(_Bool)arg2;
@property(readonly, nonatomic) CoreCollectionViewLayout *layout;
- (void)reload:(_Bool)arg1;
- (void)reloadWithDataSource:(id)arg1 animated:(_Bool)arg2;
- (double)heightForSectionHeaderAtIndex:(long long)arg1;
- (struct CGRect)rectForItemAtIndexPath:(id)arg1;
@property(readonly, nonatomic) CoreCollectionViewDataSource *dataSource;
- (void)setBounds:(struct CGRect)arg1;
- (void)setFrame:(struct CGRect)arg1;
- (void)disableUpdates:(_Bool)arg1;
- (void)setContentSize:(struct CGSize)arg1;
- (void)__didChangeSelectedObject;
- (void)collectionViewHandlePan:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)painterDidChange;

// Remaining properties
@property(nonatomic) __weak id <CoreCollectionViewDelegate> delegate;

@end

