//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray;

@interface CoreViewAnimatorGroup : NSObject
{
    NSMutableArray *__animators;
    id __strongSelf;
    _Bool _committed;
    CDUnknownBlockType _completionBlock;
    CDUnknownBlockType _cancelBlock;
}

@property(readonly, nonatomic) _Bool committed; // @synthesize committed=_committed;
@property(copy, nonatomic) CDUnknownBlockType cancelBlock; // @synthesize cancelBlock=_cancelBlock;
@property(copy, nonatomic) CDUnknownBlockType completionBlock; // @synthesize completionBlock=_completionBlock;
- (void).cxx_destruct;
- (void)animatorDidCancel:(id)arg1;
- (void)animatorDidFinish:(id)arg1;
- (void)cancelAll;
- (void)commit;
- (void)addAnimator:(id)arg1;
- (void)dealloc;
- (id)init;

@end

