//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class CRFetchedUsersController, RSFetchedResultsChanges;

@protocol CRFetchedUsersControllerDelegate <NSObject>
- (void)controller:(CRFetchedUsersController *)arg1 didChangeContent:(RSFetchedResultsChanges *)arg2;
- (void)controllerDidPerformInitialFetch:(CRFetchedUsersController *)arg1;
@end

