//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class CRFetchedSubscriptionsController, RSFetchedResultsChanges;

@protocol CRFetchedSubscriptionsControllerDelegate <NSObject>
- (void)controller:(CRFetchedSubscriptionsController *)arg1 didChangeContent:(RSFetchedResultsChanges *)arg2;
- (void)controllerDidPerformInitialFetch:(CRFetchedSubscriptionsController *)arg1;
@end

