//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "RSFetchedResultsControllerDelegate-Protocol.h"

@class CRStream, CoreCollectionViewDataSource, NSArray, NSString, NSTimer, RKItem, RKStream, RKUser, RSFetchedResultsController;
@protocol CRFetchedItemsControllerDelegate;

@interface CRFetchedItemsController : NSObject <RSFetchedResultsControllerDelegate>
{
    RSFetchedResultsController *__fetcher;
    NSTimer *__refreshTimer;
    NSTimer *__filterRefreshTimer;
    _Bool __needsRefresh;
    CoreCollectionViewDataSource *__dataSource;
    NSArray *__allObjects;
    int __locked;
    _Bool _restoring;
    CRStream *__itemStream;
    _Bool _changingOrder;
    _Bool _ascending;
    _Bool _prioritizeNext;
    _Bool _ignoreTempStates;
    _Bool _changingFilter;
    _Bool _changingGrouping;
    _Bool _hotStream;
    _Bool _archiveStream;
    NSString *_filter;
    RKItem *_ignoreItem;
    id <CRFetchedItemsControllerDelegate> _delegate;
    Class _groupingClassDelegate;
    RKUser *_user;
    RKStream *_stream;
}

+ (double)cellLineHeight;
+ (void)setCellLineHeight:(double)arg1;
+ (double)cellAdditionalHeight;
+ (void)setCellAdditionalHeight:(double)arg1;
+ (double)cellWidth;
+ (void)setCellWidth:(double)arg1;
@property(readonly, nonatomic, getter=isArchiveStream) _Bool archiveStream; // @synthesize archiveStream=_archiveStream;
@property(readonly, nonatomic, getter=isHotStream) _Bool hotStream; // @synthesize hotStream=_hotStream;
@property(readonly, nonatomic) RKStream *stream; // @synthesize stream=_stream;
@property(readonly, nonatomic) RKUser *user; // @synthesize user=_user;
@property(readonly, nonatomic, getter=isChangingGrouping) _Bool changingGrouping; // @synthesize changingGrouping=_changingGrouping;
@property(readonly, nonatomic, getter=isChangingFilter) _Bool changingFilter; // @synthesize changingFilter=_changingFilter;
@property(nonatomic) __weak Class groupingClassDelegate; // @synthesize groupingClassDelegate=_groupingClassDelegate;
@property(nonatomic) __weak id <CRFetchedItemsControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) _Bool ignoreTempStates; // @synthesize ignoreTempStates=_ignoreTempStates;
@property(nonatomic) _Bool prioritizeNext; // @synthesize prioritizeNext=_prioritizeNext;
@property(readonly, nonatomic) _Bool ascending; // @synthesize ascending=_ascending;
@property(retain, nonatomic) RKItem *ignoreItem; // @synthesize ignoreItem=_ignoreItem;
@property(copy, nonatomic) NSString *filter; // @synthesize filter=_filter;
@property(nonatomic) _Bool needsRefresh; // @synthesize needsRefresh=__needsRefresh;
@property(readonly, nonatomic) _Bool changingOrder; // @synthesize changingOrder=_changingOrder;
@property(nonatomic) _Bool restoring; // @synthesize restoring=_restoring;
@property(readonly, nonatomic) NSArray *allObjects; // @synthesize allObjects=__allObjects;
@property(readonly, nonatomic) CoreCollectionViewDataSource *dataSource; // @synthesize dataSource=__dataSource;
- (void).cxx_destruct;
- (void)filter:(_Bool)arg1;
- (void)smart_filter:(_Bool)arg1;
- (void)hot_filter:(_Bool)arg1;
- (void)forceFilter;
- (void)controllerDidProbablyMarkAnItem:(id)arg1 changes:(id)arg2;
- (void)setStream:(id)arg1;
- (void)setUser:(id)arg1;
- (void)setUser:(id)arg1 stream:(id)arg2 hot:(_Bool)arg3 archive:(_Bool)arg4;
- (void)setItemStream:(id)arg1;
- (void)restoreUser:(id)arg1 stream:(id)arg2 hot:(_Bool)arg3 archive:(_Bool)arg4;
- (void)restoreItemStream:(id)arg1;
- (void)controller:(id)arg1 inBackground:(_Bool)arg2 willSetSectionList:(id)arg3;
- (double)heightForItem:(id)arg1;
- (void)controller:(id)arg1 didChangeContent:(id)arg2;
- (void)controllerDidChangeContent:(id)arg1;
- (void)filterIfNeeded;
@property(readonly, nonatomic) RSFetchedResultsController *fetcher;
- (id)smart_fetcher;
- (id)hot_fetcher;
@property(readonly, nonatomic) NSArray *sortDescriptors;
- (id)smart_sortDescriptors;
- (id)hot_sortDescriptors;
- (long long)initialBatch;
- (void)clearFetcher;
@property(readonly, nonatomic) NSArray *orderedObjects;
- (void)toggleGrouping;
- (void)stateDidChangeFilter:(id)arg1;
- (void)lock:(_Bool)arg1;
- (void)tick:(id)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)done;
@property(readonly, nonatomic, getter=isSmartStream) _Bool smartStream;
@property(readonly, nonatomic) _Bool loading;
@property(readonly, nonatomic) _Bool groupable;
@property(readonly, nonatomic) int grouping;
- (void)storeDidChange:(id)arg1;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

