//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class CRFetchedItemsController, RSFetchedResultsChanges;

@protocol CRFetchedItemsControllerDelegate <NSObject>
- (void)controllerDidChangeFilter:(CRFetchedItemsController *)arg1;
- (void)controllerWillChangeFilter:(CRFetchedItemsController *)arg1;
- (void)controller:(CRFetchedItemsController *)arg1 didChangeContent:(RSFetchedResultsChanges *)arg2;
- (void)controllerDidPerformInitialFetch:(CRFetchedItemsController *)arg1;
@end

