//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class RSFetchedResultsController;

@interface CRFetchedController : NSObject
{
    RSFetchedResultsController *__fetcher;
    unsigned long long _fetchFilter;
}

@property(nonatomic) unsigned long long fetchFilter; // @synthesize fetchFilter=_fetchFilter;
- (void).cxx_destruct;
@property(readonly, nonatomic) RSFetchedResultsController *fetcher;
- (id)init;

@end

