//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "CoreCollectionViewDataSource.h"

@class RSSectionList;

@interface CRFetchedDataSource : CoreCollectionViewDataSource
{
    RSSectionList *_data;
}

@property(retain, nonatomic) RSSectionList *data; // @synthesize data=_data;
- (void).cxx_destruct;
- (long long)sectionForFooterObject:(id)arg1;
- (long long)sectionForHeaderObject:(id)arg1;
- (id)indexPathForObject:(id)arg1;
- (id)footerObjectInSection:(long long)arg1;
- (id)headerObjectInSection:(long long)arg1;
- (id)objectAtIndexPath:(id)arg1;
- (id)itemsInSection:(long long)arg1;
- (long long)numberOfItemsInSection:(long long)arg1;
- (long long)numberOfSections;
- (id)orderedObjects;

@end

