//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "RSFetchedResultsControllerDelegate-Protocol.h"

@class CoreCollectionViewDataSource, NSMutableArray, NSString, NSTimer, RSFetchedResultsController;
@protocol CRFetchedUsersControllerDelegate;

@interface CRFetchedUsersController : NSObject <RSFetchedResultsControllerDelegate>
{
    RSFetchedResultsController *__fetcher;
    NSMutableArray *__objects;
    NSTimer *__refreshTimer;
    _Bool __needsRefresh;
    CoreCollectionViewDataSource *__dataSource;
    id <CRFetchedUsersControllerDelegate> _delegate;
}

@property(nonatomic) __weak id <CRFetchedUsersControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) CoreCollectionViewDataSource *dataSource; // @synthesize dataSource=__dataSource;
- (void).cxx_destruct;
- (void)filter:(_Bool)arg1;
- (void)controller:(id)arg1 didChangeContent:(id)arg2;
- (void)controllerDidChangeContent:(id)arg1;
@property(readonly, nonatomic) RSFetchedResultsController *fetcher;
- (void)clearFetcher;
- (void)stateDidChangeFilter:(id)arg1;
- (void)tick:(id)arg1;
- (void)done;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

