//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, RKFeverLink, RKItem;

@interface CRItem : NSObject
{
    unsigned long long __hash;
    RKFeverLink *_link;
    RKItem *_item;
}

+ (id)withItem:(id)arg1 fromLink:(id)arg2;
@property(readonly, nonatomic) RKItem *item; // @synthesize item=_item;
@property(readonly, nonatomic) RKFeverLink *link; // @synthesize link=_link;
- (void).cxx_destruct;
@property(readonly, nonatomic) NSString *linkedUrl;
- (_Bool)isEqual:(id)arg1;
- (unsigned long long)hash;
- (id)init;

@end

