//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "CorePainter.h"

@class CRPainterAlert, CRPainterArticle, CRPainterBack, CRPainterFloor, CRPainterForm, CRPainterFront, CRPainterModal, CRPainterRoot, CRPainterWeb, NSMutableDictionary, NSString;

@interface CRPainter : CorePainter
{
    NSMutableDictionary *__font;
    NSMutableDictionary *__root;
    NSMutableDictionary *__floor;
    NSMutableDictionary *__back;
    NSMutableDictionary *__front;
    NSMutableDictionary *__article;
    NSMutableDictionary *__web;
    NSMutableDictionary *__modal;
    NSMutableDictionary *__panel;
    NSMutableDictionary *__heightForFont;
    _Bool _roundedSelection;
    _Bool _fadeRootStatusBar;
    CRPainterRoot *_root;
    CRPainterFloor *_floor;
    CRPainterBack *_back;
    CRPainterFront *_front;
    CRPainterArticle *_article;
    CRPainterWeb *_web;
    CRPainterForm *_form;
    CRPainterModal *_modal;
    CRPainterAlert *_panel;
    NSString *_systemFontName;
    NSString *_boldSystemFontName;
}

+ (id)bezelTitleFont;
+ (id)panelButtonTitleFont;
+ (id)panelTextFont;
+ (id)panelTitleFont;
+ (id)sectionFooterFont;
+ (id)sectionHeaderFont;
+ (id)cellInfoFont;
+ (id)cellCountFont;
+ (id)cellTextFont;
+ (id)cellTitleFont;
+ (id)textFont;
+ (id)titleFont;
+ (id)boldFontXL;
+ (id)boldFontL;
+ (id)boldFontM;
+ (id)boldFontS;
+ (id)boldFontXS;
+ (id)fontXL;
+ (id)fontL;
+ (id)fontM;
+ (id)fontS;
+ (id)fontXS;
+ (double)sizeXL;
+ (double)sizeL;
+ (double)sizeM;
+ (double)sizeS;
+ (double)sizeXS;
+ (void)setInterfaceFontSize:(double)arg1;
+ (double)interfaceFontSize;
+ (id)boldSystemFontOfSize:(double)arg1;
+ (id)systemFontOfSize:(double)arg1;
+ (void)setCurrentPainter:(id)arg1 notify:(_Bool)arg2;
+ (id)secondaryColor;
+ (id)primaryColor;
+ (id)currentThemeName;
+ (void)initialize;
@property(copy, nonatomic) NSString *boldSystemFontName; // @synthesize boldSystemFontName=_boldSystemFontName;
@property(copy, nonatomic) NSString *systemFontName; // @synthesize systemFontName=_systemFontName;
@property(nonatomic) _Bool fadeRootStatusBar; // @synthesize fadeRootStatusBar=_fadeRootStatusBar;
@property(nonatomic) _Bool roundedSelection; // @synthesize roundedSelection=_roundedSelection;
@property(readonly, nonatomic) CRPainterAlert *panel; // @synthesize panel=_panel;
@property(readonly, nonatomic) CRPainterModal *modal; // @synthesize modal=_modal;
@property(readonly, nonatomic) CRPainterForm *form; // @synthesize form=_form;
@property(readonly, nonatomic) CRPainterWeb *web; // @synthesize web=_web;
@property(readonly, nonatomic) CRPainterArticle *article; // @synthesize article=_article;
@property(readonly, nonatomic) CRPainterFront *front; // @synthesize front=_front;
@property(readonly, nonatomic) CRPainterBack *back; // @synthesize back=_back;
@property(readonly, nonatomic) CRPainterFloor *floor; // @synthesize floor=_floor;
@property(readonly, nonatomic) CRPainterRoot *root; // @synthesize root=_root;
- (void).cxx_destruct;
- (void)drawSectionFooterRect:(struct CGRect)arg1 title:(id)arg2 titleColor:(id)arg3 titleFont:(id)arg4 titleAlignment:(long long)arg5 titleLineBreak:(long long)arg6;
- (void)drawSectionHeaderRect:(struct CGRect)arg1 title:(id)arg2 titleColor:(id)arg3 titleFont:(id)arg4 titleAlignment:(long long)arg5 titleLineBreak:(long long)arg6;
- (void)drawCellRect:(struct CGRect)arg1 title:(id)arg2 titleColor:(id)arg3 titleFont:(id)arg4 titleAlignment:(long long)arg5 titleLineBreak:(long long)arg6 text:(id)arg7 textColor:(id)arg8 textFont:(id)arg9 textAlignment:(long long)arg10 textLineBreak:(long long)arg11 image:(id)arg12 imageColor:(id)arg13 imageSize:(double)arg14 count:(long long)arg15 countColor:(id)arg16 countFont:(id)arg17 countBorderColor:(id)arg18 arrowColor:(id)arg19;
- (void)drawCellRect:(struct CGRect)arg1 title:(id)arg2 titleColor:(id)arg3 titleFont:(id)arg4 titleAlignment:(long long)arg5 titleLineBreak:(long long)arg6 text:(id)arg7 textColor:(id)arg8 textFont:(id)arg9 textAlignment:(long long)arg10 textLineBreak:(long long)arg11 image:(id)arg12 imageColor:(id)arg13 imageSize:(double)arg14 count:(long long)arg15 countColor:(id)arg16 countFont:(id)arg17;
- (double)drawRect:(struct CGRect)arg1 title:(id)arg2 titleColor:(id)arg3 titleFont:(id)arg4 titleAlignment:(long long)arg5 titleLineBreak:(long long)arg6 text:(id)arg7 textColor:(id)arg8 textFont:(id)arg9 textAlignment:(long long)arg10 textLineBreak:(long long)arg11;
- (id)boldSystemFontOfSize:(double)arg1;
- (id)systemFontOfSize:(double)arg1;
- (double)linespacingReductionForTitleFont:(id)arg1 textFont:(id)arg2;
- (double)heightForFont:(id)arg1;
- (double)widthOfText:(id)arg1 withFont:(id)arg2;
- (double)heightOfText:(id)arg1 withFont:(id)arg2 width:(double)arg3;
- (double)heightOfCoreText:(id)arg1 withFont:(id)arg2 width:(double)arg3;
- (void)setupStore;
- (void)didLoadDefaults;
- (void)loadDefaults;
@property(readonly, nonatomic) _Bool hasLightStatusbarText;
@property(readonly, nonatomic) long long defaultStatusBarStyle;
- (id)init;

@end

