//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "CRPainterStatefulItem.h"

@class CRPainterStatefulColorItem;

@interface CRPainterStatefulFavIconItem : CRPainterStatefulItem
{
    _Bool _bordered;
    int _blendMode;
    double _alpha;
    CRPainterStatefulColorItem *_color;
}

@property(retain, nonatomic) CRPainterStatefulColorItem *color; // @synthesize color=_color;
@property(nonatomic) double alpha; // @synthesize alpha=_alpha;
@property(nonatomic) int blendMode; // @synthesize blendMode=_blendMode;
@property(nonatomic) _Bool bordered; // @synthesize bordered=_bordered;
- (void).cxx_destruct;
- (id)init;

@end

