//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "CRPainterGroup.h"

@class CRPainterFooterGroup, CRPainterHeaderGroup, CRPainterTextItem, NSString, UIColor, UIFont;

@interface CRPainterArticle : CRPainterGroup
{
    long long _scrollerStyle;
    UIColor *_color;
    UIColor *_dividerColor;
    UIColor *_overlayColor;
    UIColor *_tapHighlightColor;
    UIColor *_linkUnderscoreColor;
    CRPainterTextItem *_text;
    CRPainterHeaderGroup *_header;
    CRPainterFooterGroup *_footer;
    UIColor *_mobilizerButtonColor;
    UIFont *_pullTitleFont;
    UIFont *_pullTextFont;
    NSString *_hrStyle;
    UIColor *_hrColor;
    UIColor *_hrColorShadow;
    double _hrGradientAlphaOut;
    UIColor *_blockquoteBorderColor;
    UIColor *_frameLinkBackgroundColor;
}

@property(retain, nonatomic) UIColor *frameLinkBackgroundColor; // @synthesize frameLinkBackgroundColor=_frameLinkBackgroundColor;
@property(retain, nonatomic) UIColor *blockquoteBorderColor; // @synthesize blockquoteBorderColor=_blockquoteBorderColor;
@property(nonatomic) double hrGradientAlphaOut; // @synthesize hrGradientAlphaOut=_hrGradientAlphaOut;
@property(retain, nonatomic) UIColor *hrColorShadow; // @synthesize hrColorShadow=_hrColorShadow;
@property(retain, nonatomic) UIColor *hrColor; // @synthesize hrColor=_hrColor;
@property(copy, nonatomic) NSString *hrStyle; // @synthesize hrStyle=_hrStyle;
@property(retain, nonatomic) UIFont *pullTextFont; // @synthesize pullTextFont=_pullTextFont;
@property(retain, nonatomic) UIFont *pullTitleFont; // @synthesize pullTitleFont=_pullTitleFont;
@property(retain, nonatomic) UIColor *mobilizerButtonColor; // @synthesize mobilizerButtonColor=_mobilizerButtonColor;
@property(retain, nonatomic) CRPainterFooterGroup *footer; // @synthesize footer=_footer;
@property(retain, nonatomic) CRPainterHeaderGroup *header; // @synthesize header=_header;
@property(retain, nonatomic) CRPainterTextItem *text; // @synthesize text=_text;
@property(retain, nonatomic) UIColor *linkUnderscoreColor; // @synthesize linkUnderscoreColor=_linkUnderscoreColor;
@property(retain, nonatomic) UIColor *tapHighlightColor; // @synthesize tapHighlightColor=_tapHighlightColor;
@property(retain, nonatomic) UIColor *overlayColor; // @synthesize overlayColor=_overlayColor;
@property(retain, nonatomic) UIColor *dividerColor; // @synthesize dividerColor=_dividerColor;
@property(retain, nonatomic) UIColor *color; // @synthesize color=_color;
@property(nonatomic) long long scrollerStyle; // @synthesize scrollerStyle=_scrollerStyle;
- (void).cxx_destruct;
- (id)init;

@end

