//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "CRPainter.h"

@interface CRPainterStyleDark : CRPainter
{
}

+ (id)secondaryColor;
+ (id)primaryColor;
- (void)loadDefaults;
- (long long)defaultStatusBarStyle;
- (id)init;

@end

