//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "CRPainterGroup.h"

@class CRPainterImageItem, CRPainterShadowItem, CRPainterStatefulButtonItem, CRPainterTextItem, UIColor;

@interface CRPainterHeaderGroup : CRPainterGroup
{
    _Bool _opaque;
    _Bool _fadeOnScroll;
    UIColor *_color;
    CRPainterStatefulButtonItem *_button;
    CRPainterImageItem *_image;
    CRPainterTextItem *_title;
    CRPainterTextItem *_text;
    CRPainterShadowItem *_shadow;
}

@property(nonatomic) _Bool fadeOnScroll; // @synthesize fadeOnScroll=_fadeOnScroll;
@property(nonatomic) _Bool opaque; // @synthesize opaque=_opaque;
@property(retain, nonatomic) CRPainterShadowItem *shadow; // @synthesize shadow=_shadow;
@property(retain, nonatomic) CRPainterTextItem *text; // @synthesize text=_text;
@property(retain, nonatomic) CRPainterTextItem *title; // @synthesize title=_title;
@property(retain, nonatomic) CRPainterImageItem *image; // @synthesize image=_image;
@property(retain, nonatomic) CRPainterStatefulButtonItem *button; // @synthesize button=_button;
@property(retain, nonatomic) UIColor *color; // @synthesize color=_color;
- (void).cxx_destruct;
- (id)init;

@end

