//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "CRPainterGroup.h"

@class CRPainterCollectionGroup, CRPainterFooterGroup, CRPainterHeaderGroup, UIColor;

@interface CRPainterList : CRPainterGroup
{
    long long _scrollerStyle;
    UIColor *_color;
    UIColor *_dividerColor;
    CRPainterHeaderGroup *_header;
    CRPainterCollectionGroup *_list;
    CRPainterFooterGroup *_footer;
}

@property(retain, nonatomic) CRPainterFooterGroup *footer; // @synthesize footer=_footer;
@property(retain, nonatomic) CRPainterCollectionGroup *list; // @synthesize list=_list;
@property(retain, nonatomic) CRPainterHeaderGroup *header; // @synthesize header=_header;
@property(retain, nonatomic) UIColor *dividerColor; // @synthesize dividerColor=_dividerColor;
@property(retain, nonatomic) UIColor *color; // @synthesize color=_color;
@property(nonatomic) long long scrollerStyle; // @synthesize scrollerStyle=_scrollerStyle;
- (void).cxx_destruct;
- (id)init;

@end

