//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "CRPainterStatefulItem.h"

@class CRPainterShadowItem;

@interface CRPainterStatefulShadowItem : CRPainterStatefulItem
{
    CRPainterShadowItem *_normal;
    CRPainterShadowItem *_highlighted;
    CRPainterShadowItem *_selected;
    CRPainterShadowItem *_disabled;
}

@property(retain, nonatomic) CRPainterShadowItem *disabled; // @synthesize disabled=_disabled;
@property(retain, nonatomic) CRPainterShadowItem *selected; // @synthesize selected=_selected;
@property(retain, nonatomic) CRPainterShadowItem *highlighted; // @synthesize highlighted=_highlighted;
@property(retain, nonatomic) CRPainterShadowItem *normal; // @synthesize normal=_normal;
- (void).cxx_destruct;
- (id)init;

@end

