//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class CRPainterCollectionCellGroup, CRPainterCollectionSectionFooterGroup, CRPainterCollectionSectionHeaderGroup, UIColor;

@interface CRPainterCollectionGroup : NSObject
{
    UIColor *_color;
    CRPainterCollectionSectionHeaderGroup *_header;
    CRPainterCollectionSectionFooterGroup *_footer;
    CRPainterCollectionCellGroup *_cell;
}

@property(retain, nonatomic) CRPainterCollectionCellGroup *cell; // @synthesize cell=_cell;
@property(retain, nonatomic) CRPainterCollectionSectionFooterGroup *footer; // @synthesize footer=_footer;
@property(retain, nonatomic) CRPainterCollectionSectionHeaderGroup *header; // @synthesize header=_header;
@property(retain, nonatomic) UIColor *color; // @synthesize color=_color;
- (void).cxx_destruct;
- (id)init;

@end

