//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "CRPainterGroup.h"

@class UIColor;

@interface CRPainterModal : CRPainterGroup
{
    UIColor *_color;
    UIColor *_activity;
}

@property(retain, nonatomic) UIColor *activity; // @synthesize activity=_activity;
@property(retain, nonatomic) UIColor *color; // @synthesize color=_color;
- (void).cxx_destruct;

@end

