//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface CRPainterItem : NSObject
{
}

@property(readonly, nonatomic, getter=isStateless) _Bool stateless;
@property(readonly, nonatomic, getter=isStateful) _Bool stateful;
- (id)init;

@end

