//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "CRPainterStatefulItem.h"

@class CRPainterStatefulColorItem;

@interface CRPainterStatefulImageItem : CRPainterStatefulItem
{
    CRPainterStatefulColorItem *_color;
}

@property(retain, nonatomic) CRPainterStatefulColorItem *color; // @synthesize color=_color;
- (void).cxx_destruct;
- (id)init;

@end

