//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "CRPainterItem.h"

@class UIColor;

@interface CRPainterShadowItem : CRPainterItem
{
    _Bool _none;
    _Bool _hasShadow;
    _Bool _hasSeparator;
    UIColor *_separator;
    UIColor *_color;
    double _blurRadius;
    UIColor *_retinaSeparator;
    UIColor *_retinaColor;
    double _retinaBlurRadius;
    struct CGSize _offset;
    struct CGSize _retinaOffset;
}

@property(nonatomic) double retinaBlurRadius; // @synthesize retinaBlurRadius=_retinaBlurRadius;
@property(nonatomic) struct CGSize retinaOffset; // @synthesize retinaOffset=_retinaOffset;
@property(retain, nonatomic) UIColor *retinaColor; // @synthesize retinaColor=_retinaColor;
@property(retain, nonatomic) UIColor *retinaSeparator; // @synthesize retinaSeparator=_retinaSeparator;
@property(nonatomic) double blurRadius; // @synthesize blurRadius=_blurRadius;
@property(nonatomic) struct CGSize offset; // @synthesize offset=_offset;
@property(retain, nonatomic) UIColor *color; // @synthesize color=_color;
@property(retain, nonatomic) UIColor *separator; // @synthesize separator=_separator;
@property(nonatomic) _Bool hasSeparator; // @synthesize hasSeparator=_hasSeparator;
@property(nonatomic) _Bool hasShadow; // @synthesize hasShadow=_hasShadow;
@property(nonatomic) _Bool none; // @synthesize none=_none;
- (void).cxx_destruct;
@property(readonly, nonatomic) _Bool hasRetinaSeparator;
- (double)setSeparatorColorForProposedScale:(double)arg1;
- (_Bool)setShadowForScale:(double)arg1 inContext:(struct CGContext *)arg2;
- (id)init;

@end

