//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "CRPainterGroup.h"

@class CRPainterImageItem, CRPainterShadowItem, CRPainterStatefulButtonItem, CRPainterTextItem, UIColor;

@interface CRPainterAlert : CRPainterGroup
{
    UIColor *_color;
    UIColor *_overlay;
    CRPainterShadowItem *_shadow;
    CRPainterTextItem *_title;
    CRPainterTextItem *_text;
    CRPainterTextItem *_bezelTitle;
    CRPainterImageItem *_bezelImage;
    CRPainterShadowItem *_bezelShadow;
    UIColor *_separator;
    CRPainterStatefulButtonItem *_button;
}

@property(retain, nonatomic) CRPainterStatefulButtonItem *button; // @synthesize button=_button;
@property(retain, nonatomic) UIColor *separator; // @synthesize separator=_separator;
@property(retain, nonatomic) CRPainterShadowItem *bezelShadow; // @synthesize bezelShadow=_bezelShadow;
@property(retain, nonatomic) CRPainterImageItem *bezelImage; // @synthesize bezelImage=_bezelImage;
@property(retain, nonatomic) CRPainterTextItem *bezelTitle; // @synthesize bezelTitle=_bezelTitle;
@property(retain, nonatomic) CRPainterTextItem *text; // @synthesize text=_text;
@property(retain, nonatomic) CRPainterTextItem *title; // @synthesize title=_title;
@property(retain, nonatomic) CRPainterShadowItem *shadow; // @synthesize shadow=_shadow;
@property(retain, nonatomic) UIColor *overlay; // @synthesize overlay=_overlay;
@property(retain, nonatomic) UIColor *color; // @synthesize color=_color;
- (void).cxx_destruct;
- (id)init;

@end

