//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "CRPainterGroup.h"

@class CRPainterShadowItem, CRPainterStatefulButtonItem, CRPainterTextItem, UIColor;

@interface CRPainterFooterGroup : CRPainterGroup
{
    _Bool _opaque;
    UIColor *_color;
    CRPainterStatefulButtonItem *_button;
    CRPainterTextItem *_text;
    CRPainterShadowItem *_shadow;
}

@property(nonatomic) _Bool opaque; // @synthesize opaque=_opaque;
@property(retain, nonatomic) CRPainterShadowItem *shadow; // @synthesize shadow=_shadow;
@property(retain, nonatomic) CRPainterTextItem *text; // @synthesize text=_text;
@property(retain, nonatomic) CRPainterStatefulButtonItem *button; // @synthesize button=_button;
@property(retain, nonatomic) UIColor *color; // @synthesize color=_color;
- (void).cxx_destruct;
- (id)init;

@end

