//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "CRPainterGroup.h"

@class CRPainterStatefulColorItem, CRPainterStatefulFavIconItem, CRPainterStatefulImageItem, CRPainterStatefulTextItem, UIColor;

@interface CRPainterCollectionCellGroup : CRPainterGroup
{
    CRPainterStatefulColorItem *_color;
    UIColor *_separator;
    CRPainterStatefulImageItem *_image;
    CRPainterStatefulFavIconItem *_favicon;
    CRPainterStatefulTextItem *_info;
    CRPainterStatefulTextItem *_title;
    CRPainterStatefulTextItem *_text;
    CRPainterStatefulTextItem *_label;
    CRPainterStatefulTextItem *_input;
    CRPainterStatefulTextItem *_count;
    CRPainterStatefulImageItem *_arrow;
}

@property(retain, nonatomic) CRPainterStatefulImageItem *arrow; // @synthesize arrow=_arrow;
@property(retain, nonatomic) CRPainterStatefulTextItem *count; // @synthesize count=_count;
@property(retain, nonatomic) CRPainterStatefulTextItem *input; // @synthesize input=_input;
@property(retain, nonatomic) CRPainterStatefulTextItem *label; // @synthesize label=_label;
@property(retain, nonatomic) CRPainterStatefulTextItem *text; // @synthesize text=_text;
@property(retain, nonatomic) CRPainterStatefulTextItem *title; // @synthesize title=_title;
@property(retain, nonatomic) CRPainterStatefulTextItem *info; // @synthesize info=_info;
@property(retain, nonatomic) CRPainterStatefulFavIconItem *favicon; // @synthesize favicon=_favicon;
@property(retain, nonatomic) CRPainterStatefulImageItem *image; // @synthesize image=_image;
@property(retain, nonatomic) UIColor *separator; // @synthesize separator=_separator;
@property(retain, nonatomic) CRPainterStatefulColorItem *color; // @synthesize color=_color;
- (void).cxx_destruct;
- (id)init;

@end

