//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "CRPainterStatefulItem.h"

@class CRPainterStatefulColorItem, CRPainterStatefulTextItem;

@interface CRPainterStatefulButtonItem : CRPainterStatefulItem
{
    CRPainterStatefulColorItem *_color;
    CRPainterStatefulTextItem *_title;
    CRPainterStatefulTextItem *_text;
}

@property(retain, nonatomic) CRPainterStatefulTextItem *text; // @synthesize text=_text;
@property(retain, nonatomic) CRPainterStatefulTextItem *title; // @synthesize title=_title;
@property(retain, nonatomic) CRPainterStatefulColorItem *color; // @synthesize color=_color;
- (void).cxx_destruct;
- (id)init;

@end

