//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "CRPainterGroup.h"

@class CRPainterTextItem, UIColor;

@interface CRPainterCollectionSectionFooterGroup : CRPainterGroup
{
    UIColor *_color;
    CRPainterTextItem *_title;
    UIColor *_separator;
}

@property(retain, nonatomic) UIColor *separator; // @synthesize separator=_separator;
@property(retain, nonatomic) CRPainterTextItem *title; // @synthesize title=_title;
@property(retain, nonatomic) UIColor *color; // @synthesize color=_color;
- (void).cxx_destruct;
- (id)init;

@end

