//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "CRPainterGroup.h"

@class CRPainterHeaderGroup, UIColor;

@interface CRPainterWeb : CRPainterGroup
{
    UIColor *_color;
    UIColor *_dividerColor;
    CRPainterHeaderGroup *_header;
    UIColor *_mobilizerButtonColor;
    double _navigationBarAlpha;
}

@property(nonatomic) double navigationBarAlpha; // @synthesize navigationBarAlpha=_navigationBarAlpha;
@property(retain, nonatomic) UIColor *mobilizerButtonColor; // @synthesize mobilizerButtonColor=_mobilizerButtonColor;
@property(retain, nonatomic) CRPainterHeaderGroup *header; // @synthesize header=_header;
@property(retain, nonatomic) UIColor *dividerColor; // @synthesize dividerColor=_dividerColor;
@property(retain, nonatomic) UIColor *color; // @synthesize color=_color;
- (void).cxx_destruct;
- (id)init;

@end

