//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface CRState : NSObject
{
    int _filter;
    int _previousFilter;
}

+ (id)app;
@property(nonatomic) int previousFilter; // @synthesize previousFilter=_previousFilter;
@property(nonatomic) int filter; // @synthesize filter=_filter;
- (void)save;
- (id)init;

@end

