//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class RKStream, RKUser;

@interface CRStream : NSObject
{
    unsigned long long __hash;
    _Bool _hotItem;
    _Bool _archiveItem;
    RKUser *_user;
    RKStream *_folder;
    RKStream *_stream;
}

+ (id)withStream:(id)arg1 inFolder:(id)arg2;
+ (id)withStream:(id)arg1;
+ (id)archiveForFolder:(id)arg1;
+ (id)archiveForUser:(id)arg1;
+ (id)allForFolder:(id)arg1;
+ (id)allForUser:(id)arg1;
+ (id)hotForUser:(id)arg1;
@property(readonly, nonatomic, getter=isArchiveItem) _Bool archiveItem; // @synthesize archiveItem=_archiveItem;
@property(readonly, nonatomic, getter=isHotItem) _Bool hotItem; // @synthesize hotItem=_hotItem;
@property(readonly, nonatomic) RKStream *stream; // @synthesize stream=_stream;
@property(readonly, nonatomic) RKStream *folder; // @synthesize folder=_folder;
@property(readonly, nonatomic) RKUser *user; // @synthesize user=_user;
- (void).cxx_destruct;
- (_Bool)isEqual:(id)arg1;
- (unsigned long long)hash;
@property(readonly, nonatomic, getter=isTopItem) _Bool topItem;
@property(readonly, nonatomic) RKStream *itemsStream;
- (id)description;
- (id)init;
@property(nonatomic, getter=isExpanded) _Bool expanded;

@end

