//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCoding-Protocol.h"

@class NSArray, NSString;

@interface EDAMexpungeSharedNotebooks_args : NSObject <NSCoding>
{
    NSString *__authenticationToken;
    NSArray *__sharedNotebookIds;
    _Bool __authenticationToken_isset;
    _Bool __sharedNotebookIds_isset;
}

- (id)description;
- (void)write:(id)arg1;
- (void)read:(id)arg1;
- (void)unsetSharedNotebookIds;
- (_Bool)sharedNotebookIdsIsSet;
@property(retain, nonatomic, getter=sharedNotebookIds, setter=setSharedNotebookIds:) NSArray *sharedNotebookIds;
- (void)unsetAuthenticationToken;
- (_Bool)authenticationTokenIsSet;
@property(retain, nonatomic, getter=authenticationToken, setter=setAuthenticationToken:) NSString *authenticationToken;
- (void)dealloc;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithAuthenticationToken:(id)arg1 sharedNotebookIds:(id)arg2;

@end

