//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCoding-Protocol.h"

@class NSArray, NSString;

@interface EDAMsendMessageToSharedNotebookMembers_args : NSObject <NSCoding>
{
    NSString *__authenticationToken;
    NSString *__notebookGuid;
    NSString *__messageText;
    NSArray *__recipients;
    _Bool __authenticationToken_isset;
    _Bool __notebookGuid_isset;
    _Bool __messageText_isset;
    _Bool __recipients_isset;
}

- (id)description;
- (void)write:(id)arg1;
- (void)read:(id)arg1;
- (void)unsetRecipients;
- (_Bool)recipientsIsSet;
@property(retain, nonatomic, getter=recipients, setter=setRecipients:) NSArray *recipients;
- (void)unsetMessageText;
- (_Bool)messageTextIsSet;
@property(retain, nonatomic, getter=messageText, setter=setMessageText:) NSString *messageText;
- (void)unsetNotebookGuid;
- (_Bool)notebookGuidIsSet;
@property(retain, nonatomic, getter=notebookGuid, setter=setNotebookGuid:) NSString *notebookGuid;
- (void)unsetAuthenticationToken;
- (_Bool)authenticationTokenIsSet;
@property(retain, nonatomic, getter=authenticationToken, setter=setAuthenticationToken:) NSString *authenticationToken;
- (void)dealloc;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithAuthenticationToken:(id)arg1 notebookGuid:(id)arg2 messageText:(id)arg3 recipients:(id)arg4;

@end

