//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class EDAMAuthenticationResult, EDAMBootstrapInfo, EDAMPremiumInfo, EDAMPublicUserInfo, EDAMUser, NSString;

@protocol EDAMUserStore <NSObject>
- (NSString *)getNoteStoreUrl:(NSString *)arg1;
- (EDAMPremiumInfo *)getPremiumInfo:(NSString *)arg1;
- (EDAMPublicUserInfo *)getPublicUserInfo:(NSString *)arg1;
- (EDAMUser *)getUser:(NSString *)arg1;
- (EDAMAuthenticationResult *)refreshAuthentication:(NSString *)arg1;
- (EDAMAuthenticationResult *)authenticate:(NSString *)arg1:(NSString *)arg2:(NSString *)arg3:(NSString *)arg4;
- (EDAMBootstrapInfo *)getBootstrapInfo:(NSString *)arg1;
- (_Bool)checkVersion:(NSString *)arg1:(short)arg2:(short)arg3;
@end

