//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCoding-Protocol.h"

@class EDAMPublishing, NSArray, NSString;

@interface EDAMNotebook : NSObject <NSCoding>
{
    NSString *__guid;
    NSString *__name;
    int __updateSequenceNum;
    _Bool __defaultNotebook;
    long long __serviceCreated;
    long long __serviceUpdated;
    EDAMPublishing *__publishing;
    _Bool __published;
    NSString *__stack;
    NSArray *__sharedNotebookIds;
    NSArray *__sharedNotebooks;
    _Bool __guid_isset;
    _Bool __name_isset;
    _Bool __updateSequenceNum_isset;
    _Bool __defaultNotebook_isset;
    _Bool __serviceCreated_isset;
    _Bool __serviceUpdated_isset;
    _Bool __publishing_isset;
    _Bool __published_isset;
    _Bool __stack_isset;
    _Bool __sharedNotebookIds_isset;
    _Bool __sharedNotebooks_isset;
}

- (id)description;
- (void)write:(id)arg1;
- (void)read:(id)arg1;
- (void)unsetSharedNotebooks;
- (_Bool)sharedNotebooksIsSet;
@property(retain, nonatomic, getter=sharedNotebooks, setter=setSharedNotebooks:) NSArray *sharedNotebooks;
- (void)unsetSharedNotebookIds;
- (_Bool)sharedNotebookIdsIsSet;
@property(retain, nonatomic, getter=sharedNotebookIds, setter=setSharedNotebookIds:) NSArray *sharedNotebookIds;
- (void)unsetStack;
- (_Bool)stackIsSet;
@property(retain, nonatomic, getter=stack, setter=setStack:) NSString *stack;
- (void)unsetPublished;
- (_Bool)publishedIsSet;
@property(nonatomic, getter=published, setter=setPublished:) _Bool published;
- (void)unsetPublishing;
- (_Bool)publishingIsSet;
@property(retain, nonatomic, getter=publishing, setter=setPublishing:) EDAMPublishing *publishing;
- (void)unsetServiceUpdated;
- (_Bool)serviceUpdatedIsSet;
@property(nonatomic, getter=serviceUpdated, setter=setServiceUpdated:) long long serviceUpdated;
- (void)unsetServiceCreated;
- (_Bool)serviceCreatedIsSet;
@property(nonatomic, getter=serviceCreated, setter=setServiceCreated:) long long serviceCreated;
- (void)unsetDefaultNotebook;
- (_Bool)defaultNotebookIsSet;
@property(nonatomic, getter=defaultNotebook, setter=setDefaultNotebook:) _Bool defaultNotebook;
- (void)unsetUpdateSequenceNum;
- (_Bool)updateSequenceNumIsSet;
@property(nonatomic, getter=updateSequenceNum, setter=setUpdateSequenceNum:) int updateSequenceNum;
- (void)unsetName;
- (_Bool)nameIsSet;
@property(retain, nonatomic, getter=name, setter=setName:) NSString *name;
- (void)unsetGuid;
- (_Bool)guidIsSet;
@property(retain, nonatomic, getter=guid, setter=setGuid:) NSString *guid;
- (void)dealloc;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithGuid:(id)arg1 name:(id)arg2 updateSequenceNum:(int)arg3 defaultNotebook:(_Bool)arg4 serviceCreated:(long long)arg5 serviceUpdated:(long long)arg6 publishing:(id)arg7 published:(_Bool)arg8 stack:(id)arg9 sharedNotebookIds:(id)arg10 sharedNotebooks:(id)arg11;

@end

