//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCoding-Protocol.h"

@class NSDictionary, NSSet;

@interface EDAMLazyMap : NSObject <NSCoding>
{
    NSSet *__keysOnly;
    NSDictionary *__fullMap;
    _Bool __keysOnly_isset;
    _Bool __fullMap_isset;
}

- (id)description;
- (void)write:(id)arg1;
- (void)read:(id)arg1;
- (void)unsetFullMap;
- (_Bool)fullMapIsSet;
@property(retain, nonatomic, getter=fullMap, setter=setFullMap:) NSDictionary *fullMap;
- (void)unsetKeysOnly;
- (_Bool)keysOnlyIsSet;
@property(retain, nonatomic, getter=keysOnly, setter=setKeysOnly:) NSSet *keysOnly;
- (void)dealloc;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithKeysOnly:(id)arg1 fullMap:(id)arg2;

@end

