//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCoding-Protocol.h"

@class EDAMNote, NSString;

@interface EDAMupdateNote_args : NSObject <NSCoding>
{
    NSString *__authenticationToken;
    EDAMNote *__note;
    _Bool __authenticationToken_isset;
    _Bool __note_isset;
}

- (id)description;
- (void)write:(id)arg1;
- (void)read:(id)arg1;
- (void)unsetNote;
- (_Bool)noteIsSet;
@property(retain, nonatomic, getter=note, setter=setNote:) EDAMNote *note;
- (void)unsetAuthenticationToken;
- (_Bool)authenticationTokenIsSet;
@property(retain, nonatomic, getter=authenticationToken, setter=setAuthenticationToken:) NSString *authenticationToken;
- (void)dealloc;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithAuthenticationToken:(id)arg1 note:(id)arg2;

@end

