//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "EDAMUserStore-Protocol.h"

@class NSString;
@protocol TProtocol;

@interface EDAMUserStoreClient : NSObject <EDAMUserStore>
{
    id <TProtocol> inProtocol;
    id <TProtocol> outProtocol;
}

- (id)getNoteStoreUrl:(id)arg1;
- (id)recv_getNoteStoreUrl;
- (void)send_getNoteStoreUrl:(id)arg1;
- (id)getPremiumInfo:(id)arg1;
- (id)recv_getPremiumInfo;
- (void)send_getPremiumInfo:(id)arg1;
- (id)getPublicUserInfo:(id)arg1;
- (id)recv_getPublicUserInfo;
- (void)send_getPublicUserInfo:(id)arg1;
- (id)getUser:(id)arg1;
- (id)recv_getUser;
- (void)send_getUser:(id)arg1;
- (id)refreshAuthentication:(id)arg1;
- (id)recv_refreshAuthentication;
- (void)send_refreshAuthentication:(id)arg1;
- (id)authenticate:(id)arg1:(id)arg2:(id)arg3:(id)arg4;
- (id)recv_authenticate;
- (void)send_authenticate:(id)arg1:(id)arg2:(id)arg3:(id)arg4;
- (id)getBootstrapInfo:(id)arg1;
- (id)recv_getBootstrapInfo;
- (void)send_getBootstrapInfo:(id)arg1;
- (_Bool)checkVersion:(id)arg1:(short)arg2:(short)arg3;
- (_Bool)recv_checkVersion;
- (void)send_checkVersion:(id)arg1:(short)arg2:(short)arg3;
- (void)dealloc;
- (id)initWithInProtocol:(id)arg1 outProtocol:(id)arg2;
- (id)initWithProtocol:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

