//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCoding-Protocol.h"

@class EDAMBootstrapSettings, NSString;

@interface EDAMBootstrapProfile : NSObject <NSCoding>
{
    NSString *__name;
    EDAMBootstrapSettings *__settings;
    _Bool __name_isset;
    _Bool __settings_isset;
}

- (id)description;
- (void)write:(id)arg1;
- (void)read:(id)arg1;
- (void)unsetSettings;
- (_Bool)settingsIsSet;
@property(retain, nonatomic, getter=settings, setter=setSettings:) EDAMBootstrapSettings *settings;
- (void)unsetName;
- (_Bool)nameIsSet;
@property(retain, nonatomic, getter=name, setter=setName:) NSString *name;
- (void)dealloc;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithName:(id)arg1 settings:(id)arg2;

@end

