//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCoding-Protocol.h"

@interface EDAMClientUsageMetrics : NSObject <NSCoding>
{
    int __sessions;
    _Bool __sessions_isset;
}

- (id)description;
- (void)write:(id)arg1;
- (void)read:(id)arg1;
- (void)unsetSessions;
- (_Bool)sessionsIsSet;
@property(nonatomic, getter=sessions, setter=setSessions:) int sessions;
- (void)dealloc;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithSessions:(int)arg1;

@end

