//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCoding-Protocol.h"

@class EDAMLinkedNotebook, NSString;

@interface EDAMgetLinkedNotebookSyncChunk_args : NSObject <NSCoding>
{
    NSString *__authenticationToken;
    EDAMLinkedNotebook *__linkedNotebook;
    int __afterUSN;
    int __maxEntries;
    _Bool __fullSyncOnly;
    _Bool __authenticationToken_isset;
    _Bool __linkedNotebook_isset;
    _Bool __afterUSN_isset;
    _Bool __maxEntries_isset;
    _Bool __fullSyncOnly_isset;
}

- (id)description;
- (void)write:(id)arg1;
- (void)read:(id)arg1;
- (void)unsetFullSyncOnly;
- (_Bool)fullSyncOnlyIsSet;
@property(nonatomic, getter=fullSyncOnly, setter=setFullSyncOnly:) _Bool fullSyncOnly;
- (void)unsetMaxEntries;
- (_Bool)maxEntriesIsSet;
@property(nonatomic, getter=maxEntries, setter=setMaxEntries:) int maxEntries;
- (void)unsetAfterUSN;
- (_Bool)afterUSNIsSet;
@property(nonatomic, getter=afterUSN, setter=setAfterUSN:) int afterUSN;
- (void)unsetLinkedNotebook;
- (_Bool)linkedNotebookIsSet;
@property(retain, nonatomic, getter=linkedNotebook, setter=setLinkedNotebook:) EDAMLinkedNotebook *linkedNotebook;
- (void)unsetAuthenticationToken;
- (_Bool)authenticationTokenIsSet;
@property(retain, nonatomic, getter=authenticationToken, setter=setAuthenticationToken:) NSString *authenticationToken;
- (void)dealloc;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithAuthenticationToken:(id)arg1 linkedNotebook:(id)arg2 afterUSN:(int)arg3 maxEntries:(int)arg4 fullSyncOnly:(_Bool)arg5;

@end

