//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSException.h>

#import "NSCoding-Protocol.h"

@class NSString;

@interface EDAMSystemException : NSException <NSCoding>
{
    int __errorCode;
    NSString *__message;
    _Bool __errorCode_isset;
    _Bool __message_isset;
}

- (id)description;
- (void)write:(id)arg1;
- (void)read:(id)arg1;
- (void)unsetMessage;
- (_Bool)messageIsSet;
@property(retain, nonatomic, getter=message, setter=setMessage:) NSString *message;
- (void)unsetErrorCode;
- (_Bool)errorCodeIsSet;
@property(nonatomic, getter=errorCode, setter=setErrorCode:) int errorCode;
- (void)dealloc;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithErrorCode:(int)arg1 message:(id)arg2;
- (id)init;

@end

