//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCoding-Protocol.h"

@class NSString;

@interface EDAMgetPublicNotebook_args : NSObject <NSCoding>
{
    int __userId;
    NSString *__publicUri;
    _Bool __userId_isset;
    _Bool __publicUri_isset;
}

- (id)description;
- (void)write:(id)arg1;
- (void)read:(id)arg1;
- (void)unsetPublicUri;
- (_Bool)publicUriIsSet;
@property(retain, nonatomic, getter=publicUri, setter=setPublicUri:) NSString *publicUri;
- (void)unsetUserId;
- (_Bool)userIdIsSet;
@property(nonatomic, getter=userId, setter=setUserId:) int userId;
- (void)dealloc;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithUserId:(int)arg1 publicUri:(id)arg2;

@end

