//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCoding-Protocol.h"

@class NSString;

@interface EDAMPremiumInfo : NSObject <NSCoding>
{
    long long __currentTime;
    _Bool __premium;
    _Bool __premiumRecurring;
    long long __premiumExpirationDate;
    _Bool __premiumExtendable;
    _Bool __premiumPending;
    _Bool __premiumCancellationPending;
    _Bool __canPurchaseUploadAllowance;
    NSString *__sponsoredGroupName;
    int __sponsoredGroupRole;
    NSString *__businessName;
    _Bool __businessAdmin;
    _Bool __currentTime_isset;
    _Bool __premium_isset;
    _Bool __premiumRecurring_isset;
    _Bool __premiumExpirationDate_isset;
    _Bool __premiumExtendable_isset;
    _Bool __premiumPending_isset;
    _Bool __premiumCancellationPending_isset;
    _Bool __canPurchaseUploadAllowance_isset;
    _Bool __sponsoredGroupName_isset;
    _Bool __sponsoredGroupRole_isset;
    _Bool __businessName_isset;
    _Bool __businessAdmin_isset;
}

- (id)description;
- (void)write:(id)arg1;
- (void)read:(id)arg1;
- (void)unsetBusinessAdmin;
- (_Bool)businessAdminIsSet;
@property(nonatomic, getter=businessAdmin, setter=setBusinessAdmin:) _Bool businessAdmin;
- (void)unsetBusinessName;
- (_Bool)businessNameIsSet;
@property(retain, nonatomic, getter=businessName, setter=setBusinessName:) NSString *businessName;
- (void)unsetSponsoredGroupRole;
- (_Bool)sponsoredGroupRoleIsSet;
@property(nonatomic, getter=sponsoredGroupRole, setter=setSponsoredGroupRole:) int sponsoredGroupRole;
- (void)unsetSponsoredGroupName;
- (_Bool)sponsoredGroupNameIsSet;
@property(retain, nonatomic, getter=sponsoredGroupName, setter=setSponsoredGroupName:) NSString *sponsoredGroupName;
- (void)unsetCanPurchaseUploadAllowance;
- (_Bool)canPurchaseUploadAllowanceIsSet;
@property(nonatomic, getter=canPurchaseUploadAllowance, setter=setCanPurchaseUploadAllowance:) _Bool canPurchaseUploadAllowance;
- (void)unsetPremiumCancellationPending;
- (_Bool)premiumCancellationPendingIsSet;
@property(nonatomic, getter=premiumCancellationPending, setter=setPremiumCancellationPending:) _Bool premiumCancellationPending;
- (void)unsetPremiumPending;
- (_Bool)premiumPendingIsSet;
@property(nonatomic, getter=premiumPending, setter=setPremiumPending:) _Bool premiumPending;
- (void)unsetPremiumExtendable;
- (_Bool)premiumExtendableIsSet;
@property(nonatomic, getter=premiumExtendable, setter=setPremiumExtendable:) _Bool premiumExtendable;
- (void)unsetPremiumExpirationDate;
- (_Bool)premiumExpirationDateIsSet;
@property(nonatomic, getter=premiumExpirationDate, setter=setPremiumExpirationDate:) long long premiumExpirationDate;
- (void)unsetPremiumRecurring;
- (_Bool)premiumRecurringIsSet;
@property(nonatomic, getter=premiumRecurring, setter=setPremiumRecurring:) _Bool premiumRecurring;
- (void)unsetPremium;
- (_Bool)premiumIsSet;
@property(nonatomic, getter=premium, setter=setPremium:) _Bool premium;
- (void)unsetCurrentTime;
- (_Bool)currentTimeIsSet;
@property(nonatomic, getter=currentTime, setter=setCurrentTime:) long long currentTime;
- (void)dealloc;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithCurrentTime:(long long)arg1 premium:(_Bool)arg2 premiumRecurring:(_Bool)arg3 premiumExpirationDate:(long long)arg4 premiumExtendable:(_Bool)arg5 premiumPending:(_Bool)arg6 premiumCancellationPending:(_Bool)arg7 canPurchaseUploadAllowance:(_Bool)arg8 sponsoredGroupName:(id)arg9 sponsoredGroupRole:(int)arg10 businessName:(id)arg11 businessAdmin:(_Bool)arg12;

@end

