//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class EDAMAd, EDAMAdParameters, EDAMAuthenticationResult, EDAMClientUsageMetrics, EDAMLazyMap, EDAMLinkedNotebook, EDAMNote, EDAMNoteCollectionCounts, EDAMNoteEmailParameters, EDAMNoteFilter, EDAMNoteList, EDAMNotebook, EDAMNotesMetadataList, EDAMNotesMetadataResultSpec, EDAMResource, EDAMResourceAttributes, EDAMSavedSearch, EDAMSharedNotebook, EDAMSyncChunk, EDAMSyncChunkFilter, EDAMSyncState, EDAMTag, NSArray, NSData, NSString;

@protocol EDAMNoteStore <NSObject>
- (EDAMAuthenticationResult *)authenticateToSharedNote:(NSString *)arg1:(NSString *)arg2;
- (void)stopSharingNote:(NSString *)arg1:(NSString *)arg2;
- (NSString *)shareNote:(NSString *)arg1:(NSString *)arg2;
- (void)emailNote:(NSString *)arg1:(EDAMNoteEmailParameters *)arg2;
- (EDAMSharedNotebook *)getSharedNotebookByAuth:(NSString *)arg1;
- (EDAMAuthenticationResult *)authenticateToSharedNotebook:(NSString *)arg1:(NSString *)arg2;
- (int)expungeLinkedNotebook:(NSString *)arg1:(NSString *)arg2;
- (NSArray *)listLinkedNotebooks:(NSString *)arg1;
- (int)updateLinkedNotebook:(NSString *)arg1:(EDAMLinkedNotebook *)arg2;
- (EDAMLinkedNotebook *)createLinkedNotebook:(NSString *)arg1:(EDAMLinkedNotebook *)arg2;
- (int)expungeSharedNotebooks:(NSString *)arg1:(NSArray *)arg2;
- (NSArray *)listSharedNotebooks:(NSString *)arg1;
- (int)sendMessageToSharedNotebookMembers:(NSString *)arg1:(NSString *)arg2:(NSString *)arg3:(NSArray *)arg4;
- (EDAMSharedNotebook *)createSharedNotebook:(NSString *)arg1:(EDAMSharedNotebook *)arg2;
- (EDAMNotebook *)getPublicNotebook:(int)arg1:(NSString *)arg2;
- (EDAMAd *)getRandomAd:(NSString *)arg1:(EDAMAdParameters *)arg2;
- (NSArray *)getAds:(NSString *)arg1:(EDAMAdParameters *)arg2;
- (long long)getAccountSize:(NSString *)arg1;
- (EDAMResourceAttributes *)getResourceAttributes:(NSString *)arg1:(NSString *)arg2;
- (NSData *)getResourceAlternateData:(NSString *)arg1:(NSString *)arg2;
- (NSData *)getResourceRecognition:(NSString *)arg1:(NSString *)arg2;
- (EDAMResource *)getResourceByHash:(NSString *)arg1:(NSString *)arg2:(NSData *)arg3:(_Bool)arg4:(_Bool)arg5:(_Bool)arg6;
- (NSData *)getResourceData:(NSString *)arg1:(NSString *)arg2;
- (int)updateResource:(NSString *)arg1:(EDAMResource *)arg2;
- (int)unsetResourceApplicationDataEntry:(NSString *)arg1:(NSString *)arg2:(NSString *)arg3;
- (int)setResourceApplicationDataEntry:(NSString *)arg1:(NSString *)arg2:(NSString *)arg3:(NSString *)arg4;
- (NSString *)getResourceApplicationDataEntry:(NSString *)arg1:(NSString *)arg2:(NSString *)arg3;
- (EDAMLazyMap *)getResourceApplicationData:(NSString *)arg1:(NSString *)arg2;
- (EDAMResource *)getResource:(NSString *)arg1:(NSString *)arg2:(_Bool)arg3:(_Bool)arg4:(_Bool)arg5:(_Bool)arg6;
- (EDAMNote *)getNoteVersion:(NSString *)arg1:(NSString *)arg2:(int)arg3:(_Bool)arg4:(_Bool)arg5:(_Bool)arg6;
- (NSArray *)listNoteVersions:(NSString *)arg1:(NSString *)arg2;
- (EDAMNote *)copyNote:(NSString *)arg1:(NSString *)arg2:(NSString *)arg3;
- (int)expungeInactiveNotes:(NSString *)arg1;
- (int)expungeNotes:(NSString *)arg1:(NSArray *)arg2;
- (int)expungeNote:(NSString *)arg1:(NSString *)arg2;
- (int)deleteNote:(NSString *)arg1:(NSString *)arg2;
- (EDAMNote *)updateNote:(NSString *)arg1:(EDAMNote *)arg2;
- (EDAMNote *)createNote:(NSString *)arg1:(EDAMNote *)arg2;
- (NSArray *)getNoteTagNames:(NSString *)arg1:(NSString *)arg2;
- (NSString *)getResourceSearchText:(NSString *)arg1:(NSString *)arg2;
- (NSString *)getNoteSearchText:(NSString *)arg1:(NSString *)arg2:(_Bool)arg3:(_Bool)arg4;
- (NSString *)getNoteContent:(NSString *)arg1:(NSString *)arg2;
- (int)unsetNoteApplicationDataEntry:(NSString *)arg1:(NSString *)arg2:(NSString *)arg3;
- (int)setNoteApplicationDataEntry:(NSString *)arg1:(NSString *)arg2:(NSString *)arg3:(NSString *)arg4;
- (NSString *)getNoteApplicationDataEntry:(NSString *)arg1:(NSString *)arg2:(NSString *)arg3;
- (EDAMLazyMap *)getNoteApplicationData:(NSString *)arg1:(NSString *)arg2;
- (EDAMNote *)getNote:(NSString *)arg1:(NSString *)arg2:(_Bool)arg3:(_Bool)arg4:(_Bool)arg5:(_Bool)arg6;
- (EDAMNoteCollectionCounts *)findNoteCounts:(NSString *)arg1:(EDAMNoteFilter *)arg2:(_Bool)arg3;
- (EDAMNotesMetadataList *)findNotesMetadata:(NSString *)arg1:(EDAMNoteFilter *)arg2:(int)arg3:(int)arg4:(EDAMNotesMetadataResultSpec *)arg5;
- (int)findNoteOffset:(NSString *)arg1:(EDAMNoteFilter *)arg2:(NSString *)arg3;
- (EDAMNoteList *)findNotes:(NSString *)arg1:(EDAMNoteFilter *)arg2:(int)arg3:(int)arg4;
- (int)expungeSearch:(NSString *)arg1:(NSString *)arg2;
- (int)updateSearch:(NSString *)arg1:(EDAMSavedSearch *)arg2;
- (EDAMSavedSearch *)createSearch:(NSString *)arg1:(EDAMSavedSearch *)arg2;
- (EDAMSavedSearch *)getSearch:(NSString *)arg1:(NSString *)arg2;
- (NSArray *)listSearches:(NSString *)arg1;
- (int)expungeTag:(NSString *)arg1:(NSString *)arg2;
- (void)untagAll:(NSString *)arg1:(NSString *)arg2;
- (int)updateTag:(NSString *)arg1:(EDAMTag *)arg2;
- (EDAMTag *)createTag:(NSString *)arg1:(EDAMTag *)arg2;
- (EDAMTag *)getTag:(NSString *)arg1:(NSString *)arg2;
- (NSArray *)listTagsByNotebook:(NSString *)arg1:(NSString *)arg2;
- (NSArray *)listTags:(NSString *)arg1;
- (int)expungeNotebook:(NSString *)arg1:(NSString *)arg2;
- (int)updateNotebook:(NSString *)arg1:(EDAMNotebook *)arg2;
- (EDAMNotebook *)createNotebook:(NSString *)arg1:(EDAMNotebook *)arg2;
- (EDAMNotebook *)getDefaultNotebook:(NSString *)arg1;
- (EDAMNotebook *)getNotebook:(NSString *)arg1:(NSString *)arg2;
- (NSArray *)listNotebooks:(NSString *)arg1;
- (EDAMSyncChunk *)getLinkedNotebookSyncChunk:(NSString *)arg1:(EDAMLinkedNotebook *)arg2:(int)arg3:(int)arg4:(_Bool)arg5;
- (EDAMSyncState *)getLinkedNotebookSyncState:(NSString *)arg1:(EDAMLinkedNotebook *)arg2;
- (EDAMSyncChunk *)getFilteredSyncChunk:(NSString *)arg1:(int)arg2:(int)arg3:(EDAMSyncChunkFilter *)arg4;
- (EDAMSyncChunk *)getSyncChunk:(NSString *)arg1:(int)arg2:(int)arg3:(_Bool)arg4;
- (EDAMSyncState *)getSyncStateWithMetrics:(NSString *)arg1:(EDAMClientUsageMetrics *)arg2;
- (EDAMSyncState *)getSyncState:(NSString *)arg1;
@end

