//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCoding-Protocol.h"

@class EDAMSavedSearch, NSString;

@interface EDAMupdateSearch_args : NSObject <NSCoding>
{
    NSString *__authenticationToken;
    EDAMSavedSearch *__search;
    _Bool __authenticationToken_isset;
    _Bool __search_isset;
}

- (id)description;
- (void)write:(id)arg1;
- (void)read:(id)arg1;
- (void)unsetSearch;
- (_Bool)searchIsSet;
@property(retain, nonatomic, getter=search, setter=setSearch:) EDAMSavedSearch *search;
- (void)unsetAuthenticationToken;
- (_Bool)authenticationTokenIsSet;
@property(retain, nonatomic, getter=authenticationToken, setter=setAuthenticationToken:) NSString *authenticationToken;
- (void)dealloc;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithAuthenticationToken:(id)arg1 search:(id)arg2;

@end

