//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCoding-Protocol.h"

@class NSArray;

@interface EDAMNotesMetadataList : NSObject <NSCoding>
{
    int __startIndex;
    int __totalNotes;
    NSArray *__notes;
    NSArray *__stoppedWords;
    NSArray *__searchedWords;
    int __updateCount;
    _Bool __startIndex_isset;
    _Bool __totalNotes_isset;
    _Bool __notes_isset;
    _Bool __stoppedWords_isset;
    _Bool __searchedWords_isset;
    _Bool __updateCount_isset;
}

- (id)description;
- (void)write:(id)arg1;
- (void)read:(id)arg1;
- (void)unsetUpdateCount;
- (_Bool)updateCountIsSet;
@property(nonatomic, getter=updateCount, setter=setUpdateCount:) int updateCount;
- (void)unsetSearchedWords;
- (_Bool)searchedWordsIsSet;
@property(retain, nonatomic, getter=searchedWords, setter=setSearchedWords:) NSArray *searchedWords;
- (void)unsetStoppedWords;
- (_Bool)stoppedWordsIsSet;
@property(retain, nonatomic, getter=stoppedWords, setter=setStoppedWords:) NSArray *stoppedWords;
- (void)unsetNotes;
- (_Bool)notesIsSet;
@property(retain, nonatomic, getter=notes, setter=setNotes:) NSArray *notes;
- (void)unsetTotalNotes;
- (_Bool)totalNotesIsSet;
@property(nonatomic, getter=totalNotes, setter=setTotalNotes:) int totalNotes;
- (void)unsetStartIndex;
- (_Bool)startIndexIsSet;
@property(nonatomic, getter=startIndex, setter=setStartIndex:) int startIndex;
- (void)dealloc;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithStartIndex:(int)arg1 totalNotes:(int)arg2 notes:(id)arg3 stoppedWords:(id)arg4 searchedWords:(id)arg5 updateCount:(int)arg6;

@end

