//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCoding-Protocol.h"

@class NSString;

@interface EDAMPublicUserInfo : NSObject <NSCoding>
{
    int __userId;
    NSString *__shardId;
    int __privilege;
    NSString *__username;
    NSString *__noteStoreUrl;
    _Bool __userId_isset;
    _Bool __shardId_isset;
    _Bool __privilege_isset;
    _Bool __username_isset;
    _Bool __noteStoreUrl_isset;
}

- (id)description;
- (void)write:(id)arg1;
- (void)read:(id)arg1;
- (void)unsetNoteStoreUrl;
- (_Bool)noteStoreUrlIsSet;
@property(retain, nonatomic, getter=noteStoreUrl, setter=setNoteStoreUrl:) NSString *noteStoreUrl;
- (void)unsetUsername;
- (_Bool)usernameIsSet;
@property(retain, nonatomic, getter=username, setter=setUsername:) NSString *username;
- (void)unsetPrivilege;
- (_Bool)privilegeIsSet;
@property(nonatomic, getter=privilege, setter=setPrivilege:) int privilege;
- (void)unsetShardId;
- (_Bool)shardIdIsSet;
@property(retain, nonatomic, getter=shardId, setter=setShardId:) NSString *shardId;
- (void)unsetUserId;
- (_Bool)userIdIsSet;
@property(nonatomic, getter=userId, setter=setUserId:) int userId;
- (void)dealloc;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithUserId:(int)arg1 shardId:(id)arg2 privilege:(int)arg3 username:(id)arg4 noteStoreUrl:(id)arg5;

@end

