//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCoding-Protocol.h"

@class NSString;

@interface EDAMgetBootstrapInfo_args : NSObject <NSCoding>
{
    NSString *__locale;
    _Bool __locale_isset;
}

- (id)description;
- (void)write:(id)arg1;
- (void)read:(id)arg1;
- (void)unsetLocale;
- (_Bool)localeIsSet;
@property(retain, nonatomic, getter=locale, setter=setLocale:) NSString *locale;
- (void)dealloc;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithLocale:(id)arg1;

@end

