//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCoding-Protocol.h"

@class NSString;

@interface EDAMSavedSearch : NSObject <NSCoding>
{
    NSString *__guid;
    NSString *__name;
    NSString *__query;
    int __format;
    int __updateSequenceNum;
    _Bool __guid_isset;
    _Bool __name_isset;
    _Bool __query_isset;
    _Bool __format_isset;
    _Bool __updateSequenceNum_isset;
}

- (id)description;
- (void)write:(id)arg1;
- (void)read:(id)arg1;
- (void)unsetUpdateSequenceNum;
- (_Bool)updateSequenceNumIsSet;
@property(nonatomic, getter=updateSequenceNum, setter=setUpdateSequenceNum:) int updateSequenceNum;
- (void)unsetFormat;
- (_Bool)formatIsSet;
@property(nonatomic, getter=format, setter=setFormat:) int format;
- (void)unsetQuery;
- (_Bool)queryIsSet;
@property(retain, nonatomic, getter=query, setter=setQuery:) NSString *query;
- (void)unsetName;
- (_Bool)nameIsSet;
@property(retain, nonatomic, getter=name, setter=setName:) NSString *name;
- (void)unsetGuid;
- (_Bool)guidIsSet;
@property(retain, nonatomic, getter=guid, setter=setGuid:) NSString *guid;
- (void)dealloc;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithGuid:(id)arg1 name:(id)arg2 query:(id)arg3 format:(int)arg4 updateSequenceNum:(int)arg5;

@end

