//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "TProcessor-Protocol.h"

@class NSDictionary, NSString;
@protocol EDAMUserStore;

@interface EDAMUserStoreProcessor : NSObject <TProcessor>
{
    id <EDAMUserStore> mService;
    NSDictionary *mMethodMap;
}

- (void)dealloc;
- (void)process_getNoteStoreUrl_withSequenceID:(int)arg1 inProtocol:(id)arg2 outProtocol:(id)arg3;
- (void)process_getPremiumInfo_withSequenceID:(int)arg1 inProtocol:(id)arg2 outProtocol:(id)arg3;
- (void)process_getPublicUserInfo_withSequenceID:(int)arg1 inProtocol:(id)arg2 outProtocol:(id)arg3;
- (void)process_getUser_withSequenceID:(int)arg1 inProtocol:(id)arg2 outProtocol:(id)arg3;
- (void)process_refreshAuthentication_withSequenceID:(int)arg1 inProtocol:(id)arg2 outProtocol:(id)arg3;
- (void)process_authenticate_withSequenceID:(int)arg1 inProtocol:(id)arg2 outProtocol:(id)arg3;
- (void)process_getBootstrapInfo_withSequenceID:(int)arg1 inProtocol:(id)arg2 outProtocol:(id)arg3;
- (void)process_checkVersion_withSequenceID:(int)arg1 inProtocol:(id)arg2 outProtocol:(id)arg3;
- (_Bool)processOnInputProtocol:(id)arg1 outputProtocol:(id)arg2;
- (id)service;
- (id)initWithUserStore:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

