//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCoding-Protocol.h"

@class NSArray;

@interface EDAMSyncChunk : NSObject <NSCoding>
{
    long long __currentTime;
    int __chunkHighUSN;
    int __updateCount;
    NSArray *__notes;
    NSArray *__notebooks;
    NSArray *__tags;
    NSArray *__searches;
    NSArray *__resources;
    NSArray *__expungedNotes;
    NSArray *__expungedNotebooks;
    NSArray *__expungedTags;
    NSArray *__expungedSearches;
    NSArray *__linkedNotebooks;
    NSArray *__expungedLinkedNotebooks;
    _Bool __currentTime_isset;
    _Bool __chunkHighUSN_isset;
    _Bool __updateCount_isset;
    _Bool __notes_isset;
    _Bool __notebooks_isset;
    _Bool __tags_isset;
    _Bool __searches_isset;
    _Bool __resources_isset;
    _Bool __expungedNotes_isset;
    _Bool __expungedNotebooks_isset;
    _Bool __expungedTags_isset;
    _Bool __expungedSearches_isset;
    _Bool __linkedNotebooks_isset;
    _Bool __expungedLinkedNotebooks_isset;
}

- (id)description;
- (void)write:(id)arg1;
- (void)read:(id)arg1;
- (void)unsetExpungedLinkedNotebooks;
- (_Bool)expungedLinkedNotebooksIsSet;
@property(retain, nonatomic, getter=expungedLinkedNotebooks, setter=setExpungedLinkedNotebooks:) NSArray *expungedLinkedNotebooks;
- (void)unsetLinkedNotebooks;
- (_Bool)linkedNotebooksIsSet;
@property(retain, nonatomic, getter=linkedNotebooks, setter=setLinkedNotebooks:) NSArray *linkedNotebooks;
- (void)unsetExpungedSearches;
- (_Bool)expungedSearchesIsSet;
@property(retain, nonatomic, getter=expungedSearches, setter=setExpungedSearches:) NSArray *expungedSearches;
- (void)unsetExpungedTags;
- (_Bool)expungedTagsIsSet;
@property(retain, nonatomic, getter=expungedTags, setter=setExpungedTags:) NSArray *expungedTags;
- (void)unsetExpungedNotebooks;
- (_Bool)expungedNotebooksIsSet;
@property(retain, nonatomic, getter=expungedNotebooks, setter=setExpungedNotebooks:) NSArray *expungedNotebooks;
- (void)unsetExpungedNotes;
- (_Bool)expungedNotesIsSet;
@property(retain, nonatomic, getter=expungedNotes, setter=setExpungedNotes:) NSArray *expungedNotes;
- (void)unsetResources;
- (_Bool)resourcesIsSet;
@property(retain, nonatomic, getter=resources, setter=setResources:) NSArray *resources;
- (void)unsetSearches;
- (_Bool)searchesIsSet;
@property(retain, nonatomic, getter=searches, setter=setSearches:) NSArray *searches;
- (void)unsetTags;
- (_Bool)tagsIsSet;
@property(retain, nonatomic, getter=tags, setter=setTags:) NSArray *tags;
- (void)unsetNotebooks;
- (_Bool)notebooksIsSet;
@property(retain, nonatomic, getter=notebooks, setter=setNotebooks:) NSArray *notebooks;
- (void)unsetNotes;
- (_Bool)notesIsSet;
@property(retain, nonatomic, getter=notes, setter=setNotes:) NSArray *notes;
- (void)unsetUpdateCount;
- (_Bool)updateCountIsSet;
@property(nonatomic, getter=updateCount, setter=setUpdateCount:) int updateCount;
- (void)unsetChunkHighUSN;
- (_Bool)chunkHighUSNIsSet;
@property(nonatomic, getter=chunkHighUSN, setter=setChunkHighUSN:) int chunkHighUSN;
- (void)unsetCurrentTime;
- (_Bool)currentTimeIsSet;
@property(nonatomic, getter=currentTime, setter=setCurrentTime:) long long currentTime;
- (void)dealloc;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithCurrentTime:(long long)arg1 chunkHighUSN:(int)arg2 updateCount:(int)arg3 notes:(id)arg4 notebooks:(id)arg5 tags:(id)arg6 searches:(id)arg7 resources:(id)arg8 expungedNotes:(id)arg9 expungedNotebooks:(id)arg10 expungedTags:(id)arg11 expungedSearches:(id)arg12 linkedNotebooks:(id)arg13 expungedLinkedNotebooks:(id)arg14;

@end

