//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCoding-Protocol.h"

@class NSString;

@interface EDAMSharedNotebook : NSObject <NSCoding>
{
    long long __id;
    int __userId;
    NSString *__notebookGuid;
    NSString *__email;
    _Bool __notebookModifiable;
    _Bool __requireLogin;
    long long __serviceCreated;
    long long __serviceUpdated;
    NSString *__shareKey;
    NSString *__username;
    _Bool __id_isset;
    _Bool __userId_isset;
    _Bool __notebookGuid_isset;
    _Bool __email_isset;
    _Bool __notebookModifiable_isset;
    _Bool __requireLogin_isset;
    _Bool __serviceCreated_isset;
    _Bool __serviceUpdated_isset;
    _Bool __shareKey_isset;
    _Bool __username_isset;
}

- (id)description;
- (void)write:(id)arg1;
- (void)read:(id)arg1;
- (void)unsetUsername;
- (_Bool)usernameIsSet;
@property(retain, nonatomic, getter=username, setter=setUsername:) NSString *username;
- (void)unsetShareKey;
- (_Bool)shareKeyIsSet;
@property(retain, nonatomic, getter=shareKey, setter=setShareKey:) NSString *shareKey;
- (void)unsetServiceUpdated;
- (_Bool)serviceUpdatedIsSet;
@property(nonatomic, getter=serviceUpdated, setter=setServiceUpdated:) long long serviceUpdated;
- (void)unsetServiceCreated;
- (_Bool)serviceCreatedIsSet;
@property(nonatomic, getter=serviceCreated, setter=setServiceCreated:) long long serviceCreated;
- (void)unsetRequireLogin;
- (_Bool)requireLoginIsSet;
@property(nonatomic, getter=requireLogin, setter=setRequireLogin:) _Bool requireLogin;
- (void)unsetNotebookModifiable;
- (_Bool)notebookModifiableIsSet;
@property(nonatomic, getter=notebookModifiable, setter=setNotebookModifiable:) _Bool notebookModifiable;
- (void)unsetEmail;
- (_Bool)emailIsSet;
@property(retain, nonatomic, getter=email, setter=setEmail:) NSString *email;
- (void)unsetNotebookGuid;
- (_Bool)notebookGuidIsSet;
@property(retain, nonatomic, getter=notebookGuid, setter=setNotebookGuid:) NSString *notebookGuid;
- (void)unsetUserId;
- (_Bool)userIdIsSet;
@property(nonatomic, getter=userId, setter=setUserId:) int userId;
- (void)unsetId;
- (_Bool)idIsSet;
@property(nonatomic, getter=id, setter=setId:) long long id;
- (void)dealloc;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithId:(long long)arg1 userId:(int)arg2 notebookGuid:(id)arg3 email:(id)arg4 notebookModifiable:(_Bool)arg5 requireLogin:(_Bool)arg6 serviceCreated:(long long)arg7 serviceUpdated:(long long)arg8 shareKey:(id)arg9 username:(id)arg10;

@end

