//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCoding-Protocol.h"

@class NSArray;

@interface EDAMBootstrapInfo : NSObject <NSCoding>
{
    NSArray *__profiles;
    _Bool __profiles_isset;
}

- (id)description;
- (void)write:(id)arg1;
- (void)read:(id)arg1;
- (void)unsetProfiles;
- (_Bool)profilesIsSet;
@property(retain, nonatomic, getter=profiles, setter=setProfiles:) NSArray *profiles;
- (void)dealloc;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithProfiles:(id)arg1;

@end

