//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCoding-Protocol.h"

@class NSString;

@interface EDAMgetNoteSearchText_args : NSObject <NSCoding>
{
    NSString *__authenticationToken;
    NSString *__guid;
    _Bool __noteOnly;
    _Bool __tokenizeForIndexing;
    _Bool __authenticationToken_isset;
    _Bool __guid_isset;
    _Bool __noteOnly_isset;
    _Bool __tokenizeForIndexing_isset;
}

- (id)description;
- (void)write:(id)arg1;
- (void)read:(id)arg1;
- (void)unsetTokenizeForIndexing;
- (_Bool)tokenizeForIndexingIsSet;
@property(nonatomic, getter=tokenizeForIndexing, setter=setTokenizeForIndexing:) _Bool tokenizeForIndexing;
- (void)unsetNoteOnly;
- (_Bool)noteOnlyIsSet;
@property(nonatomic, getter=noteOnly, setter=setNoteOnly:) _Bool noteOnly;
- (void)unsetGuid;
- (_Bool)guidIsSet;
@property(retain, nonatomic, getter=guid, setter=setGuid:) NSString *guid;
- (void)unsetAuthenticationToken;
- (_Bool)authenticationTokenIsSet;
@property(retain, nonatomic, getter=authenticationToken, setter=setAuthenticationToken:) NSString *authenticationToken;
- (void)dealloc;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithAuthenticationToken:(id)arg1 guid:(id)arg2 noteOnly:(_Bool)arg3 tokenizeForIndexing:(_Bool)arg4;

@end

