//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface EDAMTypesConstants : NSObject
{
}

+ (id)EDAM_NOTE_SOURCE_MAIL_SMTP_GATEWAY;
+ (id)EDAM_NOTE_SOURCE_MAIL_CLIP;
+ (id)EDAM_NOTE_SOURCE_WEB_CLIP;
+ (void)initialize;

@end

