//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCoding-Protocol.h"

@class NSData, NSString;

@interface EDAMAd : NSObject <NSCoding>
{
    int __id;
    short __width;
    short __height;
    NSString *__advertiserName;
    NSString *__imageUrl;
    NSString *__destinationUrl;
    short __displaySeconds;
    double __score;
    NSData *__image;
    NSString *__imageMime;
    NSString *__html;
    double __displayFrequency;
    _Bool __openInTrunk;
    _Bool __id_isset;
    _Bool __width_isset;
    _Bool __height_isset;
    _Bool __advertiserName_isset;
    _Bool __imageUrl_isset;
    _Bool __destinationUrl_isset;
    _Bool __displaySeconds_isset;
    _Bool __score_isset;
    _Bool __image_isset;
    _Bool __imageMime_isset;
    _Bool __html_isset;
    _Bool __displayFrequency_isset;
    _Bool __openInTrunk_isset;
}

- (id)description;
- (void)write:(id)arg1;
- (void)read:(id)arg1;
- (void)unsetOpenInTrunk;
- (_Bool)openInTrunkIsSet;
@property(nonatomic, getter=openInTrunk, setter=setOpenInTrunk:) _Bool openInTrunk;
- (void)unsetDisplayFrequency;
- (_Bool)displayFrequencyIsSet;
@property(nonatomic, getter=displayFrequency, setter=setDisplayFrequency:) double displayFrequency;
- (void)unsetHtml;
- (_Bool)htmlIsSet;
@property(retain, nonatomic, getter=html, setter=setHtml:) NSString *html;
- (void)unsetImageMime;
- (_Bool)imageMimeIsSet;
@property(retain, nonatomic, getter=imageMime, setter=setImageMime:) NSString *imageMime;
- (void)unsetImage;
- (_Bool)imageIsSet;
@property(retain, nonatomic, getter=image, setter=setImage:) NSData *image;
- (void)unsetScore;
- (_Bool)scoreIsSet;
@property(nonatomic, getter=score, setter=setScore:) double score;
- (void)unsetDisplaySeconds;
- (_Bool)displaySecondsIsSet;
@property(nonatomic, getter=displaySeconds, setter=setDisplaySeconds:) short displaySeconds;
- (void)unsetDestinationUrl;
- (_Bool)destinationUrlIsSet;
@property(retain, nonatomic, getter=destinationUrl, setter=setDestinationUrl:) NSString *destinationUrl;
- (void)unsetImageUrl;
- (_Bool)imageUrlIsSet;
@property(retain, nonatomic, getter=imageUrl, setter=setImageUrl:) NSString *imageUrl;
- (void)unsetAdvertiserName;
- (_Bool)advertiserNameIsSet;
@property(retain, nonatomic, getter=advertiserName, setter=setAdvertiserName:) NSString *advertiserName;
- (void)unsetHeight;
- (_Bool)heightIsSet;
@property(nonatomic, getter=height, setter=setHeight:) short height;
- (void)unsetWidth;
- (_Bool)widthIsSet;
@property(nonatomic, getter=width, setter=setWidth:) short width;
- (void)unsetId;
- (_Bool)idIsSet;
@property(nonatomic, getter=id, setter=setId:) int id;
- (void)dealloc;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithId:(int)arg1 width:(short)arg2 height:(short)arg3 advertiserName:(id)arg4 imageUrl:(id)arg5 destinationUrl:(id)arg6 displaySeconds:(short)arg7 score:(double)arg8 image:(id)arg9 imageMime:(id)arg10 html:(id)arg11 displayFrequency:(double)arg12 openInTrunk:(_Bool)arg13;

@end

