//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCoding-Protocol.h"

@class NSString;

@interface EDAMauthenticate_args : NSObject <NSCoding>
{
    NSString *__username;
    NSString *__password;
    NSString *__consumerKey;
    NSString *__consumerSecret;
    _Bool __username_isset;
    _Bool __password_isset;
    _Bool __consumerKey_isset;
    _Bool __consumerSecret_isset;
}

- (id)description;
- (void)write:(id)arg1;
- (void)read:(id)arg1;
- (void)unsetConsumerSecret;
- (_Bool)consumerSecretIsSet;
@property(retain, nonatomic, getter=consumerSecret, setter=setConsumerSecret:) NSString *consumerSecret;
- (void)unsetConsumerKey;
- (_Bool)consumerKeyIsSet;
@property(retain, nonatomic, getter=consumerKey, setter=setConsumerKey:) NSString *consumerKey;
- (void)unsetPassword;
- (_Bool)passwordIsSet;
@property(retain, nonatomic, getter=password, setter=setPassword:) NSString *password;
- (void)unsetUsername;
- (_Bool)usernameIsSet;
@property(retain, nonatomic, getter=username, setter=setUsername:) NSString *username;
- (void)dealloc;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithUsername:(id)arg1 password:(id)arg2 consumerKey:(id)arg3 consumerSecret:(id)arg4;

@end

