//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCoding-Protocol.h"

@class NSString;

@interface EDAMlistNoteVersions_args : NSObject <NSCoding>
{
    NSString *__authenticationToken;
    NSString *__noteGuid;
    _Bool __authenticationToken_isset;
    _Bool __noteGuid_isset;
}

- (id)description;
- (void)write:(id)arg1;
- (void)read:(id)arg1;
- (void)unsetNoteGuid;
- (_Bool)noteGuidIsSet;
@property(retain, nonatomic, getter=noteGuid, setter=setNoteGuid:) NSString *noteGuid;
- (void)unsetAuthenticationToken;
- (_Bool)authenticationTokenIsSet;
@property(retain, nonatomic, getter=authenticationToken, setter=setAuthenticationToken:) NSString *authenticationToken;
- (void)dealloc;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithAuthenticationToken:(id)arg1 noteGuid:(id)arg2;

@end

