//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCoding-Protocol.h"

@class NSString;

@interface EDAMcheckVersion_args : NSObject <NSCoding>
{
    NSString *__clientName;
    short __edamVersionMajor;
    short __edamVersionMinor;
    _Bool __clientName_isset;
    _Bool __edamVersionMajor_isset;
    _Bool __edamVersionMinor_isset;
}

- (id)description;
- (void)write:(id)arg1;
- (void)read:(id)arg1;
- (void)unsetEdamVersionMinor;
- (_Bool)edamVersionMinorIsSet;
@property(nonatomic, getter=edamVersionMinor, setter=setEdamVersionMinor:) short edamVersionMinor;
- (void)unsetEdamVersionMajor;
- (_Bool)edamVersionMajorIsSet;
@property(nonatomic, getter=edamVersionMajor, setter=setEdamVersionMajor:) short edamVersionMajor;
- (void)unsetClientName;
- (_Bool)clientNameIsSet;
@property(retain, nonatomic, getter=clientName, setter=setClientName:) NSString *clientName;
- (void)dealloc;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithClientName:(id)arg1 edamVersionMajor:(short)arg2 edamVersionMinor:(short)arg3;

@end

