//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCoding-Protocol.h"

@class NSString;

@interface EDAMauthenticateToSharedNotebook_args : NSObject <NSCoding>
{
    NSString *__shareKey;
    NSString *__authenticationToken;
    _Bool __shareKey_isset;
    _Bool __authenticationToken_isset;
}

- (id)description;
- (void)write:(id)arg1;
- (void)read:(id)arg1;
- (void)unsetAuthenticationToken;
- (_Bool)authenticationTokenIsSet;
@property(retain, nonatomic, getter=authenticationToken, setter=setAuthenticationToken:) NSString *authenticationToken;
- (void)unsetShareKey;
- (_Bool)shareKeyIsSet;
@property(retain, nonatomic, getter=shareKey, setter=setShareKey:) NSString *shareKey;
- (void)dealloc;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithShareKey:(id)arg1 authenticationToken:(id)arg2;

@end

