//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "TableViewController.h"

#import "MFMailComposeViewControllerDelegate-Protocol.h"
#import "RKServiceConnectorUIDelegate-Protocol.h"
#import "RSFetchedResultsControllerDelegate-Protocol.h"

@class NSArray, NSString, RKService, RKServiceConnector, RSFetchedResultsController, SettingsViewCellButton;

@interface EditTableViewController : TableViewController <RSFetchedResultsControllerDelegate, RKServiceConnectorUIDelegate, MFMailComposeViewControllerDelegate>
{
    NSArray *__sharingServices;
    RKService *__selectedService;
    RKServiceConnector *__connector;
    SettingsViewCellButton *__signInButton;
    RSFetchedResultsController *__fetcher;
}

- (void).cxx_destruct;
- (void)done:(id)arg1;
- (void)delete:(id)arg1 user:(id)arg2;
- (void)mailComposeController:(id)arg1 didFinishWithResult:(long long)arg2 error:(id)arg3;
- (void)export:(id)arg1 user:(id)arg2;
- (void)serviceConnectorDidEndModalSession:(id)arg1 withError:(id)arg2;
- (void)serviceConnectorWillStartModalSession:(id)arg1;
- (_Bool)serviceConnector:(id)arg1 shouldOpenUrl:(id)arg2;
- (_Bool)serviceConnectorWillSaveNewUser:(id)arg1;
- (void)__failedAuthorization_delayed;
- (void)__failedAuthorization;
- (void)didSignInToSharingService:(id)arg1;
- (void)sign:(id)arg1 sharingUser:(id)arg2;
- (void)clearImageCache:(id)arg1;
- (void)clearIconCache:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (id)objectAtIndexPath:(id)arg1;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (id)tableView:(id)arg1 titleForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (void)controllerDidChangeContent:(id)arg1;
@property(readonly, nonatomic) RSFetchedResultsController *fetcher;
- (void)didReceiveMemoryWarning;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
@property(readonly, nonatomic) NSArray *sharingServices;
- (Class)cellClassForObjectAtIndexPath:(id)arg1;
- (_Bool)hasNavigationHeaderViewOnly;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

