//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class EDAMNoteStoreClient, EDAMUserStoreClient, EvernoteSession;

@interface ENAPI : NSObject
{
    EvernoteSession *_session;
}

@property(retain, nonatomic) EvernoteSession *session; // @synthesize session=_session;
- (void)invokeAsyncVoidBlock:(CDUnknownBlockType)arg1 success:(CDUnknownBlockType)arg2 failure:(CDUnknownBlockType)arg3;
- (void)invokeAsyncIdBlock:(CDUnknownBlockType)arg1 success:(CDUnknownBlockType)arg2 failure:(CDUnknownBlockType)arg3;
- (void)invokeAsyncInt32Block:(CDUnknownBlockType)arg1 success:(CDUnknownBlockType)arg2 failure:(CDUnknownBlockType)arg3;
- (void)invokeAsyncBoolBlock:(CDUnknownBlockType)arg1 success:(CDUnknownBlockType)arg2 failure:(CDUnknownBlockType)arg3;
- (id)errorFromNSException:(id)arg1;
@property(readonly, nonatomic) EDAMUserStoreClient *userStore; // @dynamic userStore;
@property(readonly, nonatomic) EDAMNoteStoreClient *noteStore; // @dynamic noteStore;
- (id)initWithSession:(id)arg1;
- (void)dealloc;

@end

