//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCoding-Protocol.h"

@class NSString;

@interface ENCredentials : NSObject <NSCoding>
{
    NSString *_host;
    NSString *_edamUserId;
    NSString *_noteStoreUrl;
    NSString *_webApiUrlPrefix;
    NSString *_authenticationToken;
}

@property(retain, nonatomic) NSString *authenticationToken; // @synthesize authenticationToken=_authenticationToken;
@property(retain, nonatomic) NSString *webApiUrlPrefix; // @synthesize webApiUrlPrefix=_webApiUrlPrefix;
@property(retain, nonatomic) NSString *noteStoreUrl; // @synthesize noteStoreUrl=_noteStoreUrl;
@property(retain, nonatomic) NSString *edamUserId; // @synthesize edamUserId=_edamUserId;
@property(retain, nonatomic) NSString *host; // @synthesize host=_host;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (void)deleteFromKeychain;
- (_Bool)saveToKeychain;
- (id)initWithHost:(id)arg1 edamUserId:(id)arg2 noteStoreUrl:(id)arg3 webApiUrlPrefix:(id)arg4 authenticationToken:(id)arg5;
- (void)dealloc;

@end

