//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class ENCredentialStore, NSMutableData, NSString, NSURLResponse;
@protocol OS_dispatch_queue;

@interface EvernoteSession : NSObject
{
    NSURLResponse *_response;
    NSMutableData *_receivedData;
    ENCredentialStore *_credentialStore;
    NSString *_host;
    NSString *_consumerKey;
    NSString *_consumerSecret;
    NSString *_tokenSecret;
    CDUnknownBlockType _completionHandler;
    NSObject<OS_dispatch_queue> *_queue;
}

+ (id)parametersFromQueryString:(id)arg1;
+ (id)queryStringFromParameters:(id)arg1;
+ (id)sharedSession;
+ (void)setSharedSessionHost:(id)arg1 consumerKey:(id)arg2 consumerSecret:(id)arg3;
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
@property(copy, nonatomic) CDUnknownBlockType completionHandler; // @synthesize completionHandler=_completionHandler;
@property(retain, nonatomic) NSString *tokenSecret; // @synthesize tokenSecret=_tokenSecret;
@property(retain, nonatomic) NSString *consumerSecret; // @synthesize consumerSecret=_consumerSecret;
@property(retain, nonatomic) NSString *consumerKey; // @synthesize consumerKey=_consumerKey;
@property(retain, nonatomic) NSString *host; // @synthesize host=_host;
@property(retain, nonatomic) ENCredentialStore *credentialStore; // @synthesize credentialStore=_credentialStore;
@property(retain, nonatomic) NSMutableData *receivedData; // @synthesize receivedData=_receivedData;
@property(retain, nonatomic) NSURLResponse *response; // @synthesize response=_response;
- (void)saveCredentialsWithEdamUserId:(id)arg1 noteStoreUrl:(id)arg2 webApiUrlPrefix:(id)arg3 authenticationToken:(id)arg4;
- (void)openBrowserWithURL:(id)arg1;
- (void)connectionDidFinishLoading:(id)arg1;
- (void)connection:(id)arg1 didReceiveData:(id)arg2;
- (void)connection:(id)arg1 didReceiveResponse:(id)arg2;
- (void)connection:(id)arg1 didFailWithError:(id)arg2;
- (_Bool)handleOpenURL:(id)arg1;
- (id)userAuthorizationURLStringWithParameters:(id)arg1;
- (id)oauthCallback;
- (id)callbackScheme;
- (void)startOauthAuthentication;
- (void)verifyCFBundleURLSchemes;
- (void)verifyConsumerKeyAndSecret;
- (void)authenticateWithCompletionHandler:(CDUnknownBlockType)arg1;
- (void)logout;
- (id)connectionWithRequest:(id)arg1;
- (id)userStore;
- (id)noteStore;
@property(readonly, nonatomic) NSString *webApiUrlPrefix; // @dynamic webApiUrlPrefix;
@property(readonly, nonatomic) NSString *noteStoreUrl; // @dynamic noteStoreUrl;
@property(readonly, nonatomic) NSString *userStoreUrl; // @dynamic userStoreUrl;
@property(readonly, nonatomic) _Bool isAuthenticated; // @dynamic isAuthenticated;
@property(readonly, nonatomic) NSString *authenticationToken; // @dynamic authenticationToken;
- (id)credentials;
- (void)commonInit;
- (id)initWithHost:(id)arg1 consumerKey:(id)arg2 consumerSecret:(id)arg3;
- (id)init;
- (void)dealloc;

@end

