//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "RSFetchedResultsControllerDelegate-Protocol.h"

@class NSArray, NSMutableDictionary, NSPredicate, NSString, RKStream, RKUser, RSFetchedResultsController;
@protocol FetchedSubscriptionsControllerDelegate;

@interface FetchedSubscriptionsController : NSObject <RSFetchedResultsControllerDelegate>
{
    RSFetchedResultsController *__fetcher;
    id <FetchedSubscriptionsControllerDelegate> __delegate;
    NSArray *__hotObjects;
    NSArray *__headerObjects;
    NSArray *__filteredObjects;
    long long __selectedPage;
    RKUser *__user;
    RKStream *__folder;
    long long __sectionHot;
    long long __sectionHeader;
    long long __sectionObjects;
    NSMutableDictionary *__headerAll;
    NSMutableDictionary *__headerUnread;
    NSMutableDictionary *__headerStarred;
    double __lastRefresh;
    long long __needsRefresh;
}

+ (id)fetcherWithUser:(id)arg1 folder:(id)arg2 selectedPage:(long long)arg3;
@property(nonatomic) long long selectedPage; // @synthesize selectedPage=__selectedPage;
@property(nonatomic) __weak id <FetchedSubscriptionsControllerDelegate> delegate; // @synthesize delegate=__delegate;
- (void).cxx_destruct;
- (id)objectAtIndexPath:(id)arg1;
- (id)indexPathForObject:(id)arg1;
- (long long)numberOfRowsInSection:(long long)arg1;
@property(readonly, nonatomic) long long numberOfSections;
- (void)setNeedsRefresh;
- (id)__filteredObjects;
@property(readonly, nonatomic) NSArray *filteredObjects;
@property(readonly, nonatomic) NSPredicate *filteredObjectsPredicate;
- (id)__headerObjects;
@property(readonly, nonatomic) NSArray *headerObjects;
@property(readonly, nonatomic) NSArray *hotObjects;
@property(readonly, nonatomic) _Bool hasSubscriptions;
@property(readonly, nonatomic) RSFetchedResultsController *fetcher;
- (void)refresh;
- (void)controllerDidChangeContent:(id)arg1;
- (void)countsDidChange:(id)arg1;
- (void)dealloc;
- (id)initWithUser:(id)arg1 folder:(id)arg2 selectedPage:(long long)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

