//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "RSFetchedResultsControllerDelegate-Protocol.h"

@class NSArray, NSString, RKDataStore, RSFetchedResultsController;
@protocol FetchedUsersControllerDelegate;

@interface FetchedUsersController : NSObject <RSFetchedResultsControllerDelegate>
{
    RSFetchedResultsController *__fetcher;
    id <FetchedUsersControllerDelegate> __delegate;
    NSArray *__headerObjects;
    NSArray *__filteredObjects;
    NSArray *__previousHeaderObjects;
    NSArray *__previousFilteredObjects;
    long long __selectedPage;
    long long __sectionHeader;
    long long __sectionObjects;
    RKDataStore *__store;
}

+ (id)fetcherWithStore:(id)arg1 selectedPage:(long long)arg2;
@property(nonatomic) long long selectedPage; // @synthesize selectedPage=__selectedPage;
@property(nonatomic) __weak id <FetchedUsersControllerDelegate> delegate; // @synthesize delegate=__delegate;
- (void).cxx_destruct;
- (id)objectAtIndexPath:(id)arg1;
- (id)indexPathForObject:(id)arg1;
- (long long)numberOfRowsInSection:(long long)arg1;
@property(readonly, nonatomic) long long numberOfSections;
@property(readonly, nonatomic) NSArray *filteredObjects;
@property(readonly, nonatomic) NSArray *headerObjects;
- (void)setNeedsRefresh;
- (void)syncDidFail:(id)arg1;
- (void)didSync:(id)arg1;
- (void)willSync:(id)arg1;
@property(readonly, nonatomic) RSFetchedResultsController *fetcher;
- (void)controllerDidChangeContent:(id)arg1;
- (void)countsDidChange:(id)arg1;
- (void)dealloc;
- (id)initWithStore:(id)arg1 selectedPage:(long long)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

