//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIButton.h>

@class Toolbar, UIImage;

@interface FilterControlButton : UIButton
{
    _Bool _active;
    UIImage *_image;
    Toolbar *_toolbar;
}

@property(nonatomic) _Bool active; // @synthesize active=_active;
@property(nonatomic) __weak Toolbar *toolbar; // @synthesize toolbar=_toolbar;
@property(retain) UIImage *image; // @synthesize image=_image;
- (void).cxx_destruct;
- (void)setImage:(id)arg1 forState:(unsigned long long)arg2;
- (void)drawRect:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

