//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class FilterControlButton;

@interface FilterControl : UIView
{
    FilterControlButton *_buttonStarred;
    FilterControlButton *_buttonUnread;
    FilterControlButton *_buttonAll;
}

@property(readonly, nonatomic) FilterControlButton *buttonAll; // @synthesize buttonAll=_buttonAll;
@property(readonly, nonatomic) FilterControlButton *buttonUnread; // @synthesize buttonUnread=_buttonUnread;
@property(readonly, nonatomic) FilterControlButton *buttonStarred; // @synthesize buttonStarred=_buttonStarred;
- (void).cxx_destruct;
- (void)filterAll:(id)arg1;
- (void)filterUnread:(id)arg1;
- (void)filterStarred:(id)arg1;
- (void)setNeedsDisplay;
- (void)painterDidChange;
@property(readonly, nonatomic) double controlWidth;
@property(readonly, nonatomic) double buttonSize;
- (void)filterDidChange:(id)arg1;
- (void)didMoveToWindow;
- (void)dealloc;
- (id)initWithToolbar:(id)arg1;

@end

