//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SubscriptionsViewController.h"

@class RKStream;

@interface FolderSubscriptionsViewController : SubscriptionsViewController
{
    RKStream *_stream;
}

@property(readonly, nonatomic) RKStream *stream; // @synthesize stream=_stream;
- (void).cxx_destruct;
- (void)collectionView:(id)arg1 didSelectItemWithRepresentedObject:(id)arg2 atIndexPath:(id)arg3;
- (void)controllerDidPerformInitialFetch:(id)arg1;
- (void)setUser:(id)arg1 stream:(id)arg2;
- (void)sync:(id)arg1;
- (id)folder;
- (void)handleToolbarNavigationPan:(id)arg1;
- (void)validateHeader;
- (void)updateHeader;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;
- (void)didDeleteUser:(id)arg1;
- (void)restore;
- (_Bool)hasHotItem;
- (_Bool)hasNavigationHeaderViewOnly;

@end

