//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UISlider.h>

@interface FontSizeSlider : UISlider
{
}

- (struct CGRect)trackRectForBounds:(struct CGRect)arg1;
- (id)maximumTrackImageForState:(unsigned long long)arg1;
- (id)minimumTrackImageForState:(unsigned long long)arg1;
- (void)drawRect:(struct CGRect)arg1;

@end

