//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "FormViewCell.h"

@interface FormViewInfoCell : FormViewCell
{
}

- (void)drawContentView:(id)arg1 rect:(struct CGRect)arg2;
@property(readonly, nonatomic) double height;

@end

