//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIButton.h>

@class NSString, RSFormTextOptionsPicker;

@interface FormViewTextPickerHeaderViewButton : UIButton
{
    NSString *__placeholder;
    RSFormTextOptionsPicker *__picker;
}

- (void).cxx_destruct;
- (void)updateState;
- (void)setSelected:(_Bool)arg1;
- (void)setHighlighted:(_Bool)arg1;
- (void)drawRect:(struct CGRect)arg1;
- (void)setPlaceholder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1 picker:(id)arg2;

@end

