//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UITextView.h>

@class UITableView;

@interface FormTextView : UITextView
{
    UITableView *__tableView;
}

@property(nonatomic) __weak UITableView *tableView; // @synthesize tableView=__tableView;
- (void).cxx_destruct;
- (void)actionInsert:(id)arg1;
- (void)actionClear:(id)arg1;
- (_Bool)becomeFirstResponder;
- (void)setScrollEnabled:(_Bool)arg1;
- (_Bool)resignFirstResponder;
- (id)initWithFrame:(struct CGRect)arg1;

@end

