//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "TableViewController.h"

#import "UITextViewDelegate-Protocol.h"

@class FormViewQuote, ModalView, NSArray, NSMutableArray, NSString, RSForm, UIBarButtonItem, UITextView, UIView;

@interface FormViewController : TableViewController <UITextViewDelegate>
{
    RSForm *__form;
    NSMutableArray *__sections;
    UIBarButtonItem *__done;
    ModalView *__modal;
    UITextView *__textView;
    FormViewQuote *__quoteView;
    UIView *__textContainer;
    double __bottomTextPadding;
    _Bool __hasActionPicker;
    double __forcePaddingBottom;
    NSString *_subtitle;
    NSString *_imageName;
}

+ (id)controllerWithForm:(id)arg1;
@property(retain, nonatomic) NSString *imageName; // @synthesize imageName=_imageName;
@property(copy, nonatomic) NSString *subtitle; // @synthesize subtitle=_subtitle;
@property(retain, nonatomic) RSForm *form; // @synthesize form=__form;
- (void).cxx_destruct;
- (void)endModal;
- (void)startModal;
- (void)setFirstResponder;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 titleForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)toggleOptions:(id)arg1;
@property(readonly, nonatomic) NSArray *sections;
- (void)scrollViewDidScroll:(id)arg1;
- (void)done:(id)arg1;
- (void)layoutTextContainer;
- (void)textViewDidChange:(id)arg1;
- (void)__keyboardDidChange;
- (void)keyboardDidChange:(id)arg1;
- (_Bool)shouldAutorotateToInterfaceOrientation:(long long)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)pop:(id)arg1;
- (void)viewDidLoad;
- (_Bool)hasNavigationHeaderViewOnly;
- (void)formDidPickTextOption:(id)arg1;
- (void)formDidChange:(id)arg1;
- (void)dealloc;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (id)initWithForm:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

