//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

#import "RSFormTextOptionPickerDelegate-Protocol.h"

@class FormViewTextPickerHeaderViewButton, NSMutableArray, NSString, RSFormTextOptionsPicker;

@interface FormViewTextPickerHeaderView : UIView <RSFormTextOptionPickerDelegate>
{
    RSFormTextOptionsPicker *__info;
    FormViewTextPickerHeaderViewButton *__button;
    NSMutableArray *__titles;
}

+ (id)sectionWithInfo:(id)arg1;
@property(readonly, nonatomic) RSFormTextOptionsPicker *info; // @synthesize info=__info;
- (void).cxx_destruct;
- (void)setTarget:(id)arg1 action:(SEL)arg2;
- (void)textOptionsPickerDidChangeCount:(id)arg1;
- (void)textOptionsPickerDidChangeSelection:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithInfo:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

