//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "FormViewCell.h"

@class UISwitch;

@interface FormViewToggleCell : FormViewCell
{
    UISwitch *__input;
}

@property(readonly, nonatomic) UISwitch *input; // @synthesize input=__input;
- (void).cxx_destruct;
- (void)didChangeValue:(id)arg1;
- (double)labelWidth;
- (id)initWithInfo:(id)arg1;

@end

