//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "FormViewCell.h"

@interface FormViewButtonCell : FormViewCell
{
}

- (_Bool)highlights;
- (void)drawContentView:(id)arg1 rect:(struct CGRect)arg2;

@end

