//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSString, UIColor, UIFont;

@interface FormViewQuote : UIView
{
    NSString *__quote;
    _Bool __multLine;
    UIFont *_textFont;
    UIFont *_smallTextFont;
    UIColor *_textColor;
}

@property(retain, nonatomic) UIColor *textColor; // @synthesize textColor=_textColor;
@property(retain, nonatomic) UIFont *smallTextFont; // @synthesize smallTextFont=_smallTextFont;
@property(retain, nonatomic) UIFont *textFont; // @synthesize textFont=_textFont;
@property(nonatomic) _Bool multiLine; // @synthesize multiLine=__multLine;
@property(copy, nonatomic) NSString *quote; // @synthesize quote=__quote;
- (void).cxx_destruct;
- (void)drawRect:(struct CGRect)arg1;
- (double)heightForWidth:(double)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

