//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "TableViewCell.h"

@class RSFormCell;

@interface FormViewCell : TableViewCell
{
    RSFormCell *__info;
}

+ (id)cellWithInfo:(id)arg1;
@property(readonly, nonatomic) RSFormCell *info; // @synthesize info=__info;
- (void).cxx_destruct;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)setHighlighted:(_Bool)arg1 animated:(_Bool)arg2;
@property(readonly, nonatomic) _Bool highlights;
- (void)drawContentView:(id)arg1 rect:(struct CGRect)arg2;
@property(readonly, nonatomic) double labelWidth;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (id)initWithInfo:(id)arg1;
@property(readonly, nonatomic) id input;

@end

