//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "FormViewCell.h"

#import "UITextViewDelegate-Protocol.h"

@class NSString, UITextView;

@interface FormViewTextAreaCell : FormViewCell <UITextViewDelegate>
{
    UITextView *__input;
}

@property(readonly, nonatomic) UITextView *input; // @synthesize input=__input;
- (void).cxx_destruct;
- (id)initWithInfo:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

