//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "FormViewCell.h"

#import "UITextFieldDelegate-Protocol.h"

@class NSString, UITextField;

@interface FormViewTextInputCell : FormViewCell <UITextFieldDelegate>
{
    UITextField *__input;
}

@property(readonly, nonatomic) UITextField *input; // @synthesize input=__input;
- (void).cxx_destruct;
- (void)checkReturnType;
- (_Bool)textFieldShouldClear:(id)arg1;
- (_Bool)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (void)textFieldDidBeginEditing:(id)arg1;
- (void)setFrame:(struct CGRect)arg1;
- (void)scrollToVisibleIfNeeded;
- (id)initWithInfo:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

