//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIViewController.h>

@interface HelpViewController : UIViewController
{
}

- (id)html;
- (void)loadView;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;

@end

