//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIImageView;

@interface ImageViewerContentView : UIView
{
    UIImageView *__imageView;
    UIView *__overlay;
    UIView *__shadowView;
}

@property(readonly, nonatomic) UIView *overlay; // @synthesize overlay=__overlay;
@property(readonly, nonatomic) UIView *shadowView; // @synthesize shadowView=__shadowView;
@property(readonly, nonatomic) UIImageView *imageView; // @synthesize imageView=__imageView;
- (void).cxx_destruct;
- (id)initWithImage:(id)arg1;

@end

