//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class ImageViewer, NSString, UIImage;

@protocol ImageViewerDelegate <NSObject>
- (void (^)(void))imageViewerWillClose:(ImageViewer *)arg1 animated:(_Bool)arg2;
- (void (^)(void))imageViewerWillOpen:(ImageViewer *)arg1 animated:(_Bool)arg2;
- (struct CGRect)imageViewer:(ImageViewer *)arg1 rectForImage:(UIImage *)arg2 withSrc:(NSString *)arg3;
@end

