//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "TableViewController.h"

#import "RKServiceConnectorUIDelegate-Protocol.h"

@class NSString, RKService, RKServiceConnector;

@interface IssuesViewController : TableViewController <RKServiceConnectorUIDelegate>
{
    RKService *__selectedService;
    RKServiceConnector *__connector;
}

- (void).cxx_destruct;
- (void)serviceConnectorDidEndModalSession:(id)arg1 withError:(id)arg2;
- (void)serviceConnectorWillStartModalSession:(id)arg1;
- (_Bool)serviceConnector:(id)arg1 shouldOpenUrl:(id)arg2;
- (_Bool)serviceConnectorWillSaveNewUser:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)__failedAuthorization_delayed;
- (void)__failedAuthorization;
- (void)done:(id)arg1;
- (void)dismiss:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (id)objectAtIndexPath:(id)arg1;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (void)viewWillAppear:(_Bool)arg1;
- (void)didChange:(id)arg1;
- (_Bool)hasNavigationHeaderViewOnly;
- (void)viewDidLoad;
- (void)dealloc;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

