//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "CoreCollectionReusableView.h"

@class NSString, UIView;

@interface ItemsSectionHeaderView : CoreCollectionReusableView
{
    UIView *_separator;
}

@property(readonly, nonatomic) UIView *separator; // @synthesize separator=_separator;
- (void).cxx_destruct;
- (void)drawContentViewRect:(struct CGRect)arg1;
- (void)layoutSubviews;
@property(readonly, nonatomic) NSString *title;
- (id)initWithReuseIdentifier:(id)arg1;

@end

