//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "CollectionViewController.h"

#import "CRFetchedItemsControllerDelegate-Protocol.h"
#import "UIGestureRecognizerDelegate-Protocol.h"
#import "UIViewControllerPreviewingDelegate-Protocol.h"

@class CRFetchedItemsController, CRStream, MarkAllReadButtonItem, NSString, RKItem, RKStream, RKUser;

@interface ItemsViewController : CollectionViewController <CRFetchedItemsControllerDelegate, UIGestureRecognizerDelegate, UIViewControllerPreviewingDelegate>
{
    MarkAllReadButtonItem *__markAllReadItem;
    _Bool __disableSelection;
    CRStream *__itemStream;
    _Bool __dragingReadAllPanel;
    _Bool __dragingReadAllPanelTriggered;
    _Bool __presentingMarkAllReadPanel;
    _Bool _hotStream;
    _Bool _archiveStream;
    _Bool _usesFullScreenWidth;
    RKStream *_stream;
    RKUser *_user;
    CRFetchedItemsController *_fetcher;
    NSString *_backButtonImage;
}

@property(copy, nonatomic) NSString *backButtonImage; // @synthesize backButtonImage=_backButtonImage;
@property(readonly, nonatomic) _Bool usesFullScreenWidth; // @synthesize usesFullScreenWidth=_usesFullScreenWidth;
@property(readonly, nonatomic) CRFetchedItemsController *fetcher; // @synthesize fetcher=_fetcher;
@property(readonly, nonatomic, getter=isArchiveStream) _Bool archiveStream; // @synthesize archiveStream=_archiveStream;
@property(readonly, nonatomic, getter=isHotStream) _Bool hotStream; // @synthesize hotStream=_hotStream;
@property(readonly, nonatomic) RKUser *user; // @synthesize user=_user;
@property(readonly, nonatomic) RKStream *stream; // @synthesize stream=_stream;
- (void).cxx_destruct;
- (void)push:(id)arg1;
- (void)pop:(id)arg1;
- (void)popOrPushToSelf:(id)arg1;
- (void)slidingController:(id)arg1 willSnapToViewController:(id)arg2;
- (void)collectionView:(id)arg1 didSelectItemWithRepresentedObject:(id)arg2 atIndexPath:(id)arg3;
- (_Bool)collectionView:(id)arg1 shouldHighlightItemWithRepresentedObject:(id)arg2 atIndexPath:(id)arg3;
- (double)collectionView:(id)arg1 heightForFooterInSection:(long long)arg2 representedObject:(id)arg3;
- (double)collectionView:(id)arg1 heightForHeaderInSection:(long long)arg2 representedObject:(id)arg3;
- (id)collectionView:(id)arg1 reuseIdentifierForHeaderInSection:(long long)arg2 representedObject:(id)arg3;
- (id)collectionView:(id)arg1 reuseIdentifierForCellAtIndexPath:(id)arg2 representedObject:(id)arg3;
- (double)collectionView:(id)arg1 heightForItemAtIndexPath:(id)arg2 representedObject:(id)arg3;
- (_Bool)collectionViewItemsRepondToHeightSelector:(id)arg1;
- (void)collectionView:(id)arg1 touchesEnded:(id)arg2 cancelled:(_Bool)arg3;
- (void)collectionView:(id)arg1 touchesBegan:(id)arg2;
- (id)collectionView:(id)arg1 borderColorForSlider:(int)arg2 forCell:(id)arg3;
- (id)collectionView:(id)arg1 backgroundColorForSlider:(int)arg2 forCell:(id)arg3;
- (_Bool)collectionView:(id)arg1 commitSlider:(int)arg2 forCell:(id)arg3;
- (void)collectionView:(id)arg1 cancelSliderForCell:(id)arg2;
- (void)collectionView:(id)arg1 endSliderForCell:(id)arg2;
- (void)collectionView:(id)arg1 beginSliderForCell:(id)arg2;
- (id)collectionView:(id)arg1 imageForSlider:(int)arg2 forCell:(id)arg3;
- (_Bool)collectionView:(id)arg1 shouldEnableSliderForCell:(id)arg2;
- (id)__actionForSlider:(int)arg1 forCell:(id)arg2;
- (void)readObjects:(id)arg1 pop:(_Bool)arg2 markAll:(_Bool)arg3;
- (void)markAllRead:(id)arg1 forceConfirmation:(_Bool)arg2;
- (void)markAllRead:(id)arg1;
- (void)scrollToItem:(id)arg1;
- (void)displayItem:(id)arg1;
- (id)previousItem:(id)arg1;
- (id)nextItem:(id)arg1;
- (long long)compareItem:(id)arg1 toItem:(id)arg2;
- (void)controllerDidChangeFilter:(id)arg1;
- (void)controllerWillChangeFilter:(id)arg1;
- (void)controller:(id)arg1 didChangeContent:(id)arg2;
- (void)controllerDidPerformInitialFetch:(id)arg1;
@property(readonly, nonatomic) RKItem *selectedItem;
- (void)scrollHeaderViewDidTriggerPull:(id)arg1;
- (id)scrollHeaderViewPullTitle:(id)arg1;
- (_Bool)scrollHeaderViewCanPull:(id)arg1;
- (void)didTapHeader:(id)arg1;
@property(readonly, nonatomic) _Bool canMarkAllAsRead;
- (void)setUser:(id)arg1 withStream:(id)arg2 hot:(_Bool)arg3 archive:(_Bool)arg4;
- (void)setItemStream:(id)arg1;
- (void)sync:(id)arg1;
- (void)didChangeSyncStatusText:(id)arg1;
- (double)widthForInterfaceOrientation:(long long)arg1;
- (void)didReceiveMemoryWarning;
- (_Bool)groupByFeed;
- (void)toggleGrouping:(id)arg1;
- (void)displayOptionChangeTextSize:(id)arg1;
- (void)displayOptions:(id)arg1;
- (void)validateHeader;
- (void)updateHeader;
- (void)painterDidChange:(id)arg1;
- (void)showOrHideFavicons:(id)arg1;
- (_Bool)gestureRecognizerShouldBegin:(id)arg1;
- (void)viewWillLayoutSubviews;
- (void)__navigationPan:(id)arg1;
- (void)handleNavigationPan:(id)arg1;
- (void)handleToolbarNavigationPan:(id)arg1;
- (void)handleReadAllPanelDrag:(id)arg1;
- (void)collectionViewDidReload:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)markAllReadButtonPositionDidChange:(id)arg1;
- (void)viewDidLoad;
- (void)viewDidLayoutSubviews;
- (void)updatePadding;
- (void)openPreviewItemInBrowser:(id)arg1;
- (void)previewingContext:(id)arg1 commitViewController:(id)arg2;
- (id)previewingContext:(id)arg1 viewControllerForLocation:(struct CGPoint)arg2;
- (_Bool)hasNavigationHeaderViewOnly;
- (void)longPressOnCell:(id)arg1 withRepresentedObject:(id)arg2;
- (void)willSync:(id)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)restore;
- (void)syncHotItemsDidChange:(id)arg1;
- (void)dealloc;
- (void)didDeleteUser:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

