//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "CollectionViewCell.h"

@class RKItem;

@interface ItemsViewCell : CollectionViewCell
{
}

- (void)drawContentViewRect:(struct CGRect)arg1;
- (void)didHighlightOrSelect:(_Bool)arg1;
@property(readonly, nonatomic) RKItem *item;
- (void)longTap:(id)arg1;
- (_Bool)slidable;
- (void)fetchedIcon:(id)arg1;
- (void)clearedIconCache:(id)arg1;
- (void)dealloc;
- (id)initWithReuseIdentifier:(id)arg1;

@end

