//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "ToolbarItem.h"

@class MarkAllReadButtonView;

@interface MarkAllReadButtonItem : ToolbarItem
{
}

+ (id)itemWithTarget:(id)arg1 action:(SEL)arg2;
- (void)createButton;
- (void)setImage:(id)arg1;
- (void)setEnabled:(_Bool)arg1;
- (void)__stopAnimating;
- (void)setEnabled:(_Bool)arg1 hidden:(_Bool)arg2;
@property(readonly, nonatomic) MarkAllReadButtonView *markView;

@end

