//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "ToolbarButton.h"

@class NSString;

@interface MobilizerButton : ToolbarButton
{
    NSString *_imageName;
}

@property(copy, nonatomic) NSString *imageName; // @synthesize imageName=_imageName;
- (void).cxx_destruct;
- (id)painter;
- (id)initWithFrame:(struct CGRect)arg1;

@end

