//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSData.h>

@interface NSData (RKit)
- (id)base64;
- (id)base64:(const char *)arg1 length:(long long)arg2;
@end

