//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSDateFormatter.h>

@interface NSDateFormatter (RKit)
+ (id)dateFromArbitraryDateString:(id)arg1;
+ (id)feedbinDateStringFromDate:(id)arg1;
+ (id)dateFromFeedbinDateString:(id)arg1;
+ (id)readabilityDateStringFromDate:(id)arg1;
+ (id)dateFromReadabilityDateString:(id)arg1;
+ (id)stringFromDay:(id)arg1;
+ (id)formattedTimeWithTimeIntervalSince1970:(double)arg1;
+ (id)formattedDateWithTimeIntervalSince1970:(double)arg1;
+ (id)formattedDateTimeWithTimeIntervalSince1970:(double)arg1;
@end

