//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSData.h>

@interface NSData (Base64)
+ (id)dataFromBase64String:(id)arg1;
- (id)base64EncodedString;
@end

