//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSNull.h>

@interface NSNull (RKit)
- (const char *)UTF8String;
- (id)stringValue;
- (unsigned long long)unsignedIntegerValue;
- (long long)integerValue;
- (_Bool)boolValue;
- (double)doubleValue;
- (float)floatValue;
- (unsigned long long)unsignedLongLongValue;
- (long long)longLongValue;
- (unsigned long long)unsignedLongValue;
- (long long)longValue;
- (unsigned int)unsignedIntValue;
- (int)intValue;
- (unsigned short)unsignedShortValue;
- (short)shortValue;
- (unsigned char)unsignedCharValue;
- (BOOL)charValue;
- (id)objectForKey:(id)arg1;
- (id)strippedHTML:(long long)arg1;
- (id)strippedHTML;
- (_Bool)notNull;
- (void)runActionForKey:(id)arg1 object:(id)arg2 arguments:(id)arg3;
@end

