//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface NSObject (RKit)
+ (_Bool)isOS11;
+ (_Bool)isOS9;
+ (_Bool)isPad8;
+ (_Bool)isPhone8;
+ (_Bool)isPad7;
+ (_Bool)isPhone7;
+ (_Bool)isOS8;
+ (_Bool)isOS7;
+ (_Bool)isMojave;
+ (_Bool)isHighSierra;
+ (_Bool)isElCapitan;
+ (_Bool)isYosemite;
+ (_Bool)isMac;
+ (_Bool)isPhone;
+ (_Bool)isPad;
+ (Class)dyniamicSubclassNamed:(id)arg1 protocols:(id *)arg2 impls:(struct selBlockPair *)arg3;
- (_Bool)isOS11;
- (_Bool)isOS9;
- (_Bool)isPad8;
- (_Bool)isPhone8;
- (_Bool)isPad7;
- (_Bool)isPhone7;
- (_Bool)isOS8;
- (_Bool)isOS7;
- (_Bool)isMojave;
- (_Bool)isHighSierra;
- (_Bool)isElCapitan;
- (_Bool)isYosemite;
- (_Bool)isMac;
- (_Bool)isPhone;
- (_Bool)isPad;
- (void)kill;
- (void)keepAlive;
- (void)delay:(double)arg1 block:(CDUnknownBlockType)arg2;
- (void)delay:(CDUnknownBlockType)arg1;
- (void)executeBlock:(CDUnknownBlockType)arg1;
- (void)block:(CDUnknownBlockType)arg1 afterDelay:(double)arg2;
- (void)syncBlockOnMainThread:(CDUnknownBlockType)arg1;
- (_Bool)notNull;
@end

