//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSString.h>

@interface NSString (RKit)
+ (id)entities;
+ (int)charCodeForEntity:(id)arg1;
+ (id)stringForEntity:(id)arg1;
- (id)entities;
- (id)strippedHTML:(long long)arg1;
- (id)strippedHTML;
- (id)stringByRemovingNewLinesAndWhitespace;
- (id)cleanedString;
- (id)decodedGoogleReaderItemId;
- (id)decodedUrlString;
- (id)encodedUrlString;
- (id)xmlEncode;
- (id)urlDecode;
- (id)urlEncode;
- (id)decodedQueryString;
- (id)hexToIntegerString;
- (long long)hexToInteger;
- (id)sha1;
- (id)md5;
- (_Bool)notEmpty;
- (id)trim;
@end

