//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSData, NSString;

@interface OAAttachment : NSObject
{
    NSString *name;
    NSString *fileName;
    NSString *contentType;
    NSData *data;
}

@property(copy, nonatomic) NSData *data; // @synthesize data;
@property(copy, nonatomic) NSString *contentType; // @synthesize contentType;
@property(copy, nonatomic) NSString *fileName; // @synthesize fileName;
@property(copy, nonatomic) NSString *name; // @synthesize name;
- (void).cxx_destruct;
- (id)initWithName:(id)arg1 filename:(id)arg2 contentType:(id)arg3 data:(id)arg4;

@end

