//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class NSError, OACall, OAProblem;

@protocol OACallDelegate
- (void)call:(OACall *)arg1 failedWithProblem:(OAProblem *)arg2;
- (void)call:(OACall *)arg1 failedWithError:(NSError *)arg2;
@end

