//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface OpenInChromeController : NSObject
{
}

+ (id)sharedInstance;
- (_Bool)openInChrome:(id)arg1 withCallbackURL:(id)arg2 createNewTab:(_Bool)arg3;
- (_Bool)openInChrome:(id)arg1;
- (_Bool)isChromeInstalled;

@end

