//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@interface OverlayPanelTransformView : UIView
{
}

+ (Class)layerClass;

@end

