//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIImage;

@interface PinchMobilizerView : UIView
{
    _Bool _enable;
    UIImage *_image;
}

+ (id)view;
@property(nonatomic) _Bool enable; // @synthesize enable=_enable;
@property(retain, nonatomic) UIImage *image; // @synthesize image=_image;
- (void).cxx_destruct;
- (void)drawRect:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

