//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "RSDataObject.h"

@class NSString;

@interface RKBackupUser : RSDataObject
{
    long long __bid;
    NSString *__oid;
    NSString *__serviceoid;
    NSString *__title;
    NSString *__username;
    int __index;
    _Bool __sync;
}

+ (void)backup:(id)arg1 transaction:(id)arg2;
+ (id)primaryKey;
+ (_Bool)caches;
- (void).cxx_destruct;
- (id)starredItems;
- (id)streams;
- (void)restore;

// Remaining properties
@property long long bid; // @dynamic bid;
@property int index; // @dynamic index;
@property(copy) NSString *oid; // @dynamic oid;
@property(copy) NSString *serviceoid; // @dynamic serviceoid;
@property _Bool sync; // @dynamic sync;
@property(copy) NSString *title; // @dynamic title;
@property(copy) NSString *username; // @dynamic username;

@end

