//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "RSDataObject.h"

@class NSString;

@interface RKBackupStarredItem : RSDataObject
{
    long long __bid;
    long long __streambid;
    long long __userbid;
    NSString *__oid;
    NSString *__title;
    NSString *__author;
    NSString *__link;
    NSString *__summary;
    NSString *__content;
    double __publishedDate;
    double __dayPublished;
}

+ (id)primaryKey;
+ (_Bool)caches;
- (void).cxx_destruct;

// Remaining properties
@property(copy) NSString *author; // @dynamic author;
@property long long bid; // @dynamic bid;
@property(copy) NSString *content; // @dynamic content;
@property double dayPublished; // @dynamic dayPublished;
@property(copy) NSString *link; // @dynamic link;
@property(copy) NSString *oid; // @dynamic oid;
@property double publishedDate; // @dynamic publishedDate;
@property long long streambid; // @dynamic streambid;
@property(copy) NSString *summary; // @dynamic summary;
@property(copy) NSString *title; // @dynamic title;
@property long long userbid; // @dynamic userbid;

@end

