//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "RSDataObject.h"

@class NSString;

@interface RKBackupStream : RSDataObject
{
    long long __bid;
    long long __userbid;
    NSString *__oid;
    NSString *__title;
    _Bool __listed;
    int __index;
    NSString *__folders;
}

+ (id)primaryKey;
+ (_Bool)caches;
- (void).cxx_destruct;

// Remaining properties
@property long long bid; // @dynamic bid;
@property(copy) NSString *folders; // @dynamic folders;
@property int index; // @dynamic index;
@property _Bool listed; // @dynamic listed;
@property(copy) NSString *oid; // @dynamic oid;
@property(copy) NSString *title; // @dynamic title;
@property long long userbid; // @dynamic userbid;

@end

