//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "RSDataStore.h"

@interface RKDataStore : RSDataStore
{
    int __countLock;
    _Bool __didRestoreFromBackup;
    _Bool __needTmpReadClear;
    _Bool __needTmpUnstarredClear;
    _Bool __needTmpTagClear;
}

+ (id)store;
+ (void)load:(CDUnknownBlockType)arg1;
@property(readonly, nonatomic) _Bool didRestoreFromBackup; // @synthesize didRestoreFromBackup=__didRestoreFromBackup;
- (void)clearTempStateOfItem:(id)arg1;
- (void)clearTempStatesExcludingItem:(id)arg1 transaction:(id)arg2;
- (void)clearTempStatesExcludingItem:(id)arg1;
- (void)setNeedsClearTempStatesIfNeededForItem:(id)arg1;
- (void)refreshNeedsClearStates;
- (void)setNeedsClearTempTags;
- (void)clearTempStates;
- (void)__updateItem:(id)arg1 setStarred:(int)arg2 transaction:(id)arg3;
- (void)__updateItem:(id)arg1 setUnread:(int)arg2 transaction:(id)arg3;
- (void)__updateAndReadItems:(id)arg1 stream:(id)arg2 user:(id)arg3 markAll:(_Bool)arg4 transaction:(id)arg5;
- (void)toggleStarred:(id)arg1 withUnstarredValue:(int)arg2;
- (void)toggleStarred:(id)arg1;
- (void)toggleUnread:(id)arg1 withReadValue:(int)arg2 clearTempState:(_Bool)arg3 exludeItem:(_Bool)arg4;
- (void)toggleUnread:(id)arg1 withReadValue:(int)arg2;
- (void)toggleUnread:(id)arg1;
- (void)unstar:(id)arg1;
- (void)star:(id)arg1;
- (void)unread:(id)arg1 postToConnector:(_Bool)arg2;
- (void)unread:(id)arg1;
- (void)readAll:(id)arg1 stream:(id)arg2 user:(id)arg3 markAll:(_Bool)arg4;
- (void)readAll:(id)arg1 stream:(id)arg2 user:(id)arg3;
- (void)read:(id)arg1;
- (void)__updStreamStarredCountForItem:(id)arg1;
- (void)__updStreamUnreadCountForItem:(id)arg1;
- (void)__updStreamZeroUnreadCount:(id)arg1;
- (void)refreshCounts;
- (void)refreshCountsForStream:(id)arg1;
- (void)refreshCountsInBackground;
- (void)lockCounts:(_Bool)arg1;
- (void)recalculateCounts:(CDUnknownBlockType)arg1;
- (id)initWithName:(id)arg1;

@end

