//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "RSDataObject.h"

@class NSString, RKUser;

@interface RKDeletedCachedItem : RSDataObject
{
    long long __itemid;
    long long __streamid;
    id __user;
}

+ (_Bool)caches;
- (void).cxx_destruct;
@property(readonly, nonatomic) NSString *offlineCacheDirectory;

// Remaining properties
@property long long itemid; // @dynamic itemid;
@property long long streamid; // @dynamic streamid;
@property(retain) RKUser *user; // @dynamic user;

@end

