//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "RSDataObject.h"

@class NSDictionary, NSString, RKUser;

@interface RKEdit : RSDataObject
{
    id __user;
    NSString *__json;
}

+ (id)pendingEditsForUser:(id)arg1;
+ (id)primaryKey;
+ (_Bool)caches;
- (void).cxx_destruct;
@property(retain) NSDictionary *infoDictionary;
- (id)executeWithTarget:(id)arg1;

// Remaining properties
@property(copy) NSString *json; // @dynamic json;
@property(retain) RKUser *user; // @dynamic user;

@end

