//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "RSDataObject.h"

@class NSString, RKItem, RKItemList, RKStream, RKUser;

@interface RKFeverLink : RSDataObject
{
    NSString *__oid;
    id __user;
    id __stream;
    id __item;
    _Bool __isItem;
    _Bool __isLocal;
    _Bool __isSaved;
    NSString *__title;
    NSString *__url;
    double __temp;
    RKItemList *__items;
    _Bool __read;
}

+ (id)primaryKey;
+ (_Bool)caches;
- (void).cxx_destruct;
@property(readonly, nonatomic) NSString *linkedUrl;

// Remaining properties
@property _Bool isItem; // @dynamic isItem;
@property _Bool isLocal; // @dynamic isLocal;
@property _Bool isSaved; // @dynamic isSaved;
@property(retain) RKItem *item; // @dynamic item;
@property(retain) RKItemList *items; // @dynamic items;
@property(copy) NSString *oid; // @dynamic oid;
@property _Bool read; // @dynamic read;
@property(retain) RKStream *stream; // @dynamic stream;
@property double temp; // @dynamic temp;
@property(copy) NSString *title; // @dynamic title;
@property(copy) NSString *url; // @dynamic url;
@property(retain) RKUser *user; // @dynamic user;

@end

