//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSError, NSString, RKFeedStream;

@protocol RKFeedStreamDelegate <NSObject>
- (void)feedStream:(RKFeedStream *)arg1 didFail:(NSError *)arg2;
- (void)feedStreamDidFinish:(RKFeedStream *)arg1;
- (void)feedStream:(RKFeedStream *)arg1 didReceiveBytes:(unsigned long long)arg2;
- (void)feedStream:(RKFeedStream *)arg1 didReceiveEtag:(NSString *)arg2;
@end

