//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSInputStream.h>

#import "NSURLConnectionDataDelegate-Protocol.h"

@class NSData, NSMutableData, NSObject, NSString, NSURLConnection;
@protocol OS_dispatch_semaphore, RKFeedStreamDelegate;

@interface RKFeedStream : NSInputStream <NSURLConnectionDataDelegate>
{
    NSURLConnection *__connection;
    NSMutableData *__bufferedData;
    _Bool __finished;
    NSObject<OS_dispatch_semaphore> *__semaphore;
    unsigned long long __bytes;
    id <RKFeedStreamDelegate> __streamingDelegate;
    NSString *__etag;
    NSString *__textEncodingName;
    unsigned long long __encoding;
    _Bool __didReceiveData;
    _Bool __callOnMainThread;
    NSMutableData *__data;
}

@property(readonly, nonatomic) unsigned long long encoding; // @synthesize encoding=__encoding;
@property(readonly, nonatomic) unsigned long long bytes; // @synthesize bytes=__bytes;
- (void).cxx_destruct;
- (void)connection:(id)arg1 didFailWithError:(id)arg2;
- (void)connectionDidFinishLoading:(id)arg1;
- (void)connection:(id)arg1 didReceiveData:(id)arg2;
- (void)connection:(id)arg1 didReceiveResponse:(id)arg2;
- (long long)read:(char *)arg1 maxLength:(unsigned long long)arg2;
- (void)close;
- (void)open;
@property(readonly, nonatomic) _Bool finished;
@property(nonatomic) _Bool cachesData;
@property(readonly, nonatomic) NSData *data;
- (_Bool)hasBufferedData;
- (void)dealloc;
- (id)initWithContentsOfURL:(id)arg1 etag:(id)arg2 streamingDelegate:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

