//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSXMLParserDelegate-Protocol.h"
#import "RKFeedStreamDelegate-Protocol.h"

@class NSError, NSString, NSXMLParser, RKFeedChannel, RKFeedStream;

@interface RKFeedParser : NSObject <NSXMLParserDelegate, RKFeedStreamDelegate>
{
    NSXMLParser *__xmlParser;
    NSString *__urlString;
    RKFeedStream *__stream;
    int __depth;
    int __itemDepth;
    int __channelDepth;
    RKFeedChannel *__channel;
    id __target;
    SEL __selector;
    NSString *__etag;
    NSError *__error;
}

+ (id)parserWithUrlString:(id)arg1 etag:(id)arg2;
@property(readonly, nonatomic) NSString *urlString; // @synthesize urlString=__urlString;
- (void).cxx_destruct;
- (id)parser:(id)arg1 resolveExternalEntityName:(id)arg2 systemID:(id)arg3;
- (void)parser:(id)arg1 parseErrorOccurred:(id)arg2;
- (void)parser:(id)arg1 foundCharacters:(id)arg2;
- (void)parser:(id)arg1 foundCDATA:(id)arg2;
- (void)parser:(id)arg1 didEndElement:(id)arg2 namespaceURI:(id)arg3 qualifiedName:(id)arg4;
- (void)parser:(id)arg1 didStartElement:(id)arg2 namespaceURI:(id)arg3 qualifiedName:(id)arg4 attributes:(id)arg5;
- (void)parserDidEndDocument:(id)arg1;
- (void)parserDidStartDocument:(id)arg1;
- (void)feedStream:(id)arg1 didFail:(id)arg2;
- (void)feedStreamDidFinish:(id)arg1;
- (void)feedStream:(id)arg1 didReceiveBytes:(unsigned long long)arg2;
- (void)feedStream:(id)arg1 didReceiveEtag:(id)arg2;
- (id)parseJSON;
- (id)parse;
- (id)initWithUrlString:(id)arg1 etag:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

