//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSError, NSMutableArray, NSString;

@interface RKFeedChannel : NSObject
{
    NSString *__url;
    NSString *__title;
    NSString *__subtitle;
    NSString *__link;
    NSMutableArray *__items;
    unsigned long long __bytes;
    NSString *__etag;
    _Bool __completed;
    NSError *__error;
    _Bool _completed;
    NSError *_error;
}

@property(copy, nonatomic) NSError *error; // @synthesize error=_error;
@property(nonatomic) _Bool completed; // @synthesize completed=_completed;
@property(copy, nonatomic) NSString *etag; // @synthesize etag=__etag;
@property(readonly, nonatomic) NSArray *items; // @synthesize items=__items;
@property(copy, nonatomic) NSString *link; // @synthesize link=__link;
@property(copy, nonatomic) NSString *subtitle; // @synthesize subtitle=__subtitle;
@property(copy, nonatomic) NSString *title; // @synthesize title=__title;
@property(copy, nonatomic) NSString *url; // @synthesize url=__url;
@property(nonatomic) unsigned long long bytes; // @synthesize bytes=__bytes;
- (void).cxx_destruct;
- (void)closeItem;
- (id)openItem;
- (id)initWithUrl:(id)arg1;

@end

