//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSMutableArray;
@protocol RKIssuesManagerDelegate;

@interface RKIssuesManager : NSObject
{
    NSMutableArray *__issues;
    id <RKIssuesManagerDelegate> __delegate;
}

+ (id)sharedManager;
@property(nonatomic) __weak id <RKIssuesManagerDelegate> delegate; // @synthesize delegate=__delegate;
@property(readonly, nonatomic) NSArray *issues; // @synthesize issues=__issues;
- (void).cxx_destruct;
- (void)dealloc;
- (_Bool)userHasIssues:(id)arg1;
@property(readonly, nonatomic) _Bool hasIssues;
- (void)createNewIssueFromServiceNotification:(id)arg1;
- (void)removeIssueFromServiceNotification:(id)arg1;
- (void)userDidDelete:(id)arg1;
- (id)init;

@end

