//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class RKIssuesManager, RKUser;

@protocol RKIssuesManagerDelegate <NSObject>
- (void)issuesManager:(RKIssuesManager *)arg1 didReceiveNewIssue:(RKUser *)arg2;
@end

