//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "RSDataObject.h"

@class NSString, RKItem;

@interface RKItemLinks : RSDataObject
{
    id __item;
    int __type;
    NSString *__link;
}

+ (void)parseItem:(id)arg1 withHTML:(id)arg2 link:(id)arg3 transaction:(id)arg4;
+ (void)createTableWithStore:(id)arg1;
+ (id)primaryKey;
+ (_Bool)caches;
- (void).cxx_destruct;

// Remaining properties
@property(retain) RKItem *item; // @dynamic item;
@property(copy) NSString *link; // @dynamic link;
@property int type; // @dynamic type;

@end

