//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "RSDataObject.h"

@class NSString, RKItem;

@interface RKItemData : RSDataObject
{
    NSString *__title;
    NSString *__author;
    NSString *__link;
    NSString *__content;
    NSString *__readabilityContent;
    id __item;
}

+ (id)primaryKey;
- (void).cxx_destruct;

// Remaining properties
@property(copy) NSString *author; // @dynamic author;
@property(copy) NSString *content; // @dynamic content;
@property(retain) RKItem *item; // @dynamic item;
@property(copy) NSString *link; // @dynamic link;
@property(copy) NSString *readabilityContent; // @dynamic readabilityContent;
@property(copy) NSString *title; // @dynamic title;

@end

