//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "RSDataObject.h"

@class CorePrimitiveArray, NSArray, NSDictionary, NSMutableDictionary, NSString, RKItemData, RKStream;

@interface RKItem : RSDataObject
{
    NSString *__oid;
    id __stream;
    long long __userid;
    NSString *__title;
    NSString *__summary;
    int __unread;
    int __starred;
    int __cached;
    double __publishedDate;
    double __starredDate;
    double __dayPublished;
    double __dayStarred;
    NSString *__data1;
    NSString *__data2;
    RKItemData *__data;
    CorePrimitiveArray *_heights;
    NSMutableDictionary *_heightsForFontSize;
    double _floatData1;
    double _floatData2;
    double _currentlyUsedFontSize;
}

+ (long long)endTrackingSaves;
+ (void)beginTrackingSaves;
+ (void)setCurrentFontSize:(double)arg1;
+ (id)fetch:(id)arg1 fromStore:(id)arg2 limit:(long long)arg3 sortDescriptors:(id)arg4 cancelDelegate:(id)arg5;
+ (void)updateTo3:(id)arg1;
+ (void)createTableWithStore:(id)arg1;
+ (id)primaryKey;
+ (_Bool)caches;
@property(readonly, nonatomic) double currentlyUsedFontSize; // @synthesize currentlyUsedFontSize=_currentlyUsedFontSize;
@property(nonatomic) double floatData2; // @synthesize floatData2=_floatData2;
@property(nonatomic) double floatData1; // @synthesize floatData1=_floatData1;
- (void).cxx_destruct;
- (void)willSave;
@property(copy, nonatomic) NSDictionary *heightsForFontSize;
@property(readonly, nonatomic) CorePrimitiveArray *heights;
@property(readonly, nonatomic) NSString *streamTitle;
@property(readonly, nonatomic) _Bool prefReadsOnOpen;
@property(readonly, nonatomic) NSArray *tagStreams;
@property(readonly, nonatomic) NSArray *tagItems;
@property(readonly, nonatomic) NSString *linkedUrl;
@property(readonly, nonatomic) NSArray *similarItems;
@property(readonly, nonatomic) _Bool isReadLaterItem;
@property(readonly, nonatomic) _Bool isInstapaperItem;
@property(readonly, nonatomic) _Bool isReadabilityItem;
@property(readonly, nonatomic) NSString *offlineCacheDirectory;
- (void)createObjectID;
- (void)fetchFromStatement:(id)arg1;
@property(readonly) __weak RKItemData *data;
- (void)markDestroyed;
- (double)CoreCollectionViewCellRowHeight;
- (long long)titleNumberOfLines;
- (double)titleHeight;

// Remaining properties
@property int cached; // @dynamic cached;
@property(copy) NSString *data1; // @dynamic data1;
@property(copy) NSString *data2; // @dynamic data2;
@property double dayPublished; // @dynamic dayPublished;
@property double dayStarred; // @dynamic dayStarred;
@property(copy) NSString *oid; // @dynamic oid;
@property double publishedDate; // @dynamic publishedDate;
@property int starred; // @dynamic starred;
@property double starredDate; // @dynamic starredDate;
@property(retain) RKStream *stream; // @dynamic stream;
@property(copy) NSString *summary; // @dynamic summary;
@property(copy) NSString *title; // @dynamic title;
@property int unread; // @dynamic unread;
@property long long userid; // @dynamic userid;

@end

