//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSMutableArray, NSString;

@interface RKOPMLItem : NSObject
{
    NSMutableArray *__items;
    _Bool _isFolder;
    NSString *_title;
    NSString *_xmlUrl;
    NSString *_htmlUrl;
}

@property(copy, nonatomic) NSString *htmlUrl; // @synthesize htmlUrl=_htmlUrl;
@property(copy, nonatomic) NSString *xmlUrl; // @synthesize xmlUrl=_xmlUrl;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(nonatomic) _Bool isFolder; // @synthesize isFolder=_isFolder;
@property(readonly, nonatomic) NSArray *items; // @synthesize items=__items;
- (void).cxx_destruct;
- (void)add:(id)arg1;
- (id)init;

@end

