//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SafariServices/SFSafariViewController.h>

@interface RKSafariViewController : SFSafariViewController
{
    struct UIEdgeInsets _asai;
}

- (void)dismiss;
- (void)dismissViewControllerAnimated:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;

@end

