//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "RKServiceBaseAuthConnector.h"

@interface RKServiceFever : RKServiceBaseAuthConnector
{
}

+ (_Bool)canSync;
- (void)syncLinks;
- (void)sync:(id)arg1;
- (void)updateNewestItemOid;
- (id)newestItemOid;
- (void)__processLinks:(id)arg1;
- (void)refreshOnServer:(CDUnknownBlockType)arg1;
- (id)refreshOnServer;
- (id)opmlEntryForFeed:(id)arg1;
- (_Bool)canExportSubscriptions;
- (id)markWithDictionary:(id)arg1;
- (void)setStarred:(int)arg1 forItem:(id)arg2;
- (void)setUnread:(int)arg1 forItem:(id)arg2;
- (void)setReadForItems:(id)arg1 stream:(id)arg2 markAll:(_Bool)arg3;
- (_Bool)serviceResponseShouldValidateResponse:(id)arg1;
- (id)requestWithTarget:(id)arg1 parameters:(id)arg2 method:(id)arg3;
- (_Bool)verifyAuthorization:(id *)arg1;
- (void)authFormDidSubmit:(id)arg1;
- (void)setupAuthForm;
- (void)didDeleteUser;
- (void)willDeleteUser:(id)arg1;

@end

