//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "RKServiceXAuth2Connector.h"

@interface RKServiceQuoteFM : RKServiceXAuth2Connector
{
}

+ (_Bool)canHandleObject:(id)arg1;
+ (_Bool)canShare;
- (void)prepareShareForm:(id)arg1 forObject:(id)arg2;
- (id)shareWithDictionary:(id)arg1;
- (void)shareFormDidSubmit:(id)arg1;
- (_Bool)shouldShareObject:(id)arg1;
- (void)authFormDidSubmit:(id)arg1;
- (id)categories;
- (void)fetchCategeries:(CDUnknownBlockType)arg1;
- (id)fetchCategeries;
- (void)fetchUserInfo;
- (id)authHeader;
- (_Bool)serviceResponseShouldValidateResponse:(id)arg1;
- (id)requestWithTarget:(id)arg1 parameters:(id)arg2 method:(id)arg3;
- (_Bool)verifyAuthorization:(id *)arg1;
- (void)setupShareForm;
- (_Bool)flashBezelOnShare;
- (id)initWithService:(id)arg1 user:(id)arg2;

@end

