//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "RKServiceConnector.h"

@interface RKServiceEvernote : RKServiceConnector
{
}

+ (_Bool)canHandleObject:(id)arg1;
+ (_Bool)canShare;
+ (_Bool)needsUser;
+ (void)initialize;
- (id)shareWithDictionary:(id)arg1;
- (void)share:(id)arg1;
- (_Bool)recoverFromError:(id)arg1;
- (_Bool)prepare;
- (_Bool)verifyAuthorization:(id *)arg1;
- (void)authorize;
- (void)authFormDidSubmit:(id)arg1;
- (void)authFormDidSubmitWithButtonCell:(id)arg1;
- (void)setupAuthForm;
- (_Bool)authorized;
- (_Bool)flashBezelOnShare;
- (void)didDeleteUser;
- (void)handleAuthUrl:(id)arg1;
- (void)dealloc;
- (id)initWithService:(id)arg1 user:(id)arg2;

@end

