//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "RKServiceXAuthConnector.h"

@interface RKServiceReadability : RKServiceXAuthConnector
{
}

+ (_Bool)isUrlBlocked:(id)arg1;
+ (void)fetch:(id)arg1 handler:(CDUnknownBlockType)arg2;
+ (_Bool)canDeleteItems;
+ (_Bool)canEditItemTags;
+ (_Bool)canHandleObject:(id)arg1;
+ (_Bool)canSync;
+ (_Bool)canShare;
+ (_Bool)isReadLaterService;
- (void)syncDidFail:(id)arg1;
- (void)sync:(id)arg1;
- (_Bool)serviceResponseShouldValidateResponse:(id)arg1;
- (void)getJSON:(id)arg1 params:(id)arg2 handler:(CDUnknownBlockType)arg3;
- (void)getJSON:(id)arg1 handler:(CDUnknownBlockType)arg2;
- (id)getJSON:(id)arg1 params:(id)arg2;
- (id)getJSON:(id)arg1;
- (void)getArticle:(id)arg1 handler:(CDUnknownBlockType)arg2;
- (void)getBookmarksWithParams:(id)arg1 handler:(CDUnknownBlockType)arg2;
- (void)getBookmarks:(CDUnknownBlockType)arg1;
- (void)getUserInfo:(CDUnknownBlockType)arg1;
- (id)getArticle:(id)arg1;
- (id)getBookmarksWithParams:(id)arg1;
- (id)getBookmarks;
- (id)getUserInfo;
- (id)removeTagWithDictionary:(id)arg1;
- (void)removeTag:(id)arg1 forItem:(id)arg2;
- (id)addTagWithDictionary:(id)arg1;
- (void)addTag:(id)arg1 forItem:(id)arg2;
- (void)createTag:(id)arg1;
- (id)addBookmarkWithDictionary:(id)arg1;
- (id)deleteItemWithDictionary:(id)arg1;
- (void)deleteItem:(id)arg1;
- (id)editBookmarkWithDictionary:(id)arg1;
- (void)setStarred:(int)arg1 forItem:(id)arg2;
- (void)setUnread:(int)arg1 forItem:(id)arg2;
- (void)setReadForItems:(id)arg1 stream:(id)arg2 markAll:(_Bool)arg3;
- (_Bool)verifyAuthorization:(id *)arg1;
- (void)fetchUserInfo;
- (void)share:(id)arg1;
- (id)imageNameForFolderStream:(id)arg1;
- (_Bool)flashBezelOnShare;
- (id)titleForDidUnread;
- (id)titleForDidRead;
- (id)titleForToggleRead;
- (id)titleForUnread;
- (id)titleForRead;
- (id)initWithService:(id)arg1 user:(id)arg2;

@end

