//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "RKServiceQuoteFM.h"

@interface RKServiceQuoteFMRead : RKServiceQuoteFM
{
}

+ (_Bool)canShare;
+ (_Bool)canHandleObject:(id)arg1;
- (id)shareWithDictionary:(id)arg1;
- (void)share:(id)arg1;
- (_Bool)shouldShareObject:(id)arg1;
- (void)fetchUserInfo;
- (void)setupShareForm;

@end

