//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSSortDescriptor.h>

@class NSMutableDictionary, NSString, RKUser;

@interface RKServiceGoogleReaderStreamSortDescriptor : NSSortDescriptor
{
    id __parentObject;
    NSString *__key;
    NSMutableDictionary *__cache;
    NSString *__cachedString;
    RKUser *__user;
}

@property(retain, nonatomic) RKUser *user; // @synthesize user=__user;
@property(copy) NSString *key; // @synthesize key=__key;
@property(retain, nonatomic) id parentObject; // @synthesize parentObject=__parentObject;
- (void).cxx_destruct;
- (long long)compareObject:(id)arg1 toObject:(id)arg2;
- (void)reset;
- (id)initWithKey:(id)arg1 ascending:(_Bool)arg2 selector:(SEL)arg3;

@end

