//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSError, RKServiceConnector;

@protocol RKServiceConnectorDelegate <NSObject>

@optional
- (void)serviceConnectorDidResaveUserInfo:(RKServiceConnector *)arg1;
- (void)serviceConnector:(RKServiceConnector *)arg1 didFailToAuthorize:(NSError *)arg2;
- (void)serviceConnectorDidAuthorize:(RKServiceConnector *)arg1;
@end

