//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDictionary, NSMutableDictionary, NSString, OAToken;

@interface RKServiceConnectorUser : NSObject
{
    NSString *__serviceName;
    NSString *__title;
    NSString *__username;
    NSString *__userid;
    NSMutableDictionary *__info;
    NSMutableDictionary *__auth;
    OAToken *__oauthToken;
}

@property(readonly, nonatomic) NSString *serviceName; // @synthesize serviceName=__serviceName;
@property(copy, nonatomic) NSString *userid; // @synthesize userid=__userid;
@property(copy, nonatomic) NSString *username; // @synthesize username=__username;
@property(copy, nonatomic) NSString *title; // @synthesize title=__title;
@property(retain, nonatomic) OAToken *oauthToken; // @synthesize oauthToken=__oauthToken;
@property(copy, nonatomic) NSDictionary *auth; // @synthesize auth=__auth;
@property(copy, nonatomic) NSDictionary *info; // @synthesize info=__info;
- (void).cxx_destruct;
- (id)authValueForKey:(id)arg1;
- (void)setAuthValue:(id)arg1 forKey:(id)arg2;
- (id)customValueForKey:(id)arg1;
- (void)setCustomValue:(id)arg1 forKey:(id)arg2;
- (void)destroy;
- (void)save;
- (void)restore;
- (id)initWithServiceName:(id)arg1 userid:(id)arg2;

@end

