//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "RKServiceConnector.h"

@interface RKServiceReadItLater : RKServiceConnector
{
}

+ (_Bool)canDeleteItems;
+ (_Bool)canEditItemTags;
+ (_Bool)canSync;
+ (_Bool)isReadLaterService;
+ (_Bool)canHandleObject:(id)arg1;
+ (_Bool)canShare;
+ (void)initialize;
- (void)didFetchAll;
- (void)sync:(id)arg1;
- (id)deleteItemWithDictionary:(id)arg1;
- (void)deleteItem:(id)arg1;
- (id)editBookmarkWithDictionary:(id)arg1;
- (void)setStarred:(int)arg1 forItem:(id)arg2;
- (void)setUnread:(int)arg1 forItem:(id)arg2;
- (void)setReadForItems:(id)arg1 stream:(id)arg2 markAll:(_Bool)arg3;
- (void)fetchUserInfo;
- (id)imageNameForFolderStream:(id)arg1;
- (id)titleForDidUnread;
- (id)titleForDidRead;
- (id)titleForToggleRead;
- (id)titleForUnread;
- (id)titleForRead;
- (id)shareWithDictionary:(id)arg1;
- (void)share:(id)arg1;
- (_Bool)recoverFromError:(id)arg1;
- (_Bool)prepare;
- (_Bool)verifyAuthorization:(id *)arg1;
- (void)authorize;
- (void)authFormDidSubmit:(id)arg1;
- (void)authFormDidSubmitWithButtonCell:(id)arg1;
- (void)setupAuthForm;
- (_Bool)authorized;
- (_Bool)flashBezelOnShare;
- (void)didDeleteUser;
- (void)handleAuthUrl:(id)arg1;
- (id)initWithService:(id)arg1 user:(id)arg2;

@end

