//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "RKServiceBaseAuthConnector.h"

@interface RKServiceFeedWrangler : RKServiceBaseAuthConnector
{
    double __sinceStamp;
}

+ (_Bool)canEditFolderTags;
+ (_Bool)canEditFolders;
+ (_Bool)canUnsubscribe;
+ (_Bool)canSubscribe;
+ (_Bool)canSync;
- (id)unsubscribe:(id)arg1;
- (id)subscribe:(id)arg1 title:(id)arg2 folders:(id)arg3;
- (void)didSubscribe;
- (id)feedUrlStringForStream:(id)arg1;
- (id)opmlEntryForFeed:(id)arg1;
- (_Bool)canExportSubscriptions;
- (id)markWithDictionary:(id)arg1;
- (void)setReadForItems:(id)arg1 stream:(id)arg2 markAll:(_Bool)arg3;
- (void)markItem:(id)arg1 key:(id)arg2 value:(id)arg3;
- (void)setStarred:(int)arg1 forItem:(id)arg2;
- (void)setUnread:(int)arg1 forItem:(id)arg2;
- (void)syncSmartStreams:(id)arg1;
- (void)sync:(id)arg1;
- (id)processItemDataWithStore:(id)arg1 transaction:(id)arg2 data:(id)arg3 dayDateFormatter:(id)arg4;
- (id)requestWithTarget:(id)arg1 parameters:(id)arg2 method:(id)arg3;
- (_Bool)verifyAuthorization:(id *)arg1;
- (_Bool)serviceResponseShouldValidateResponse:(id)arg1;
- (void)authFormDidSubmit:(id)arg1;
- (void)setupAuthForm;
- (void)didDeleteUser;
- (void)willDeleteUser:(id)arg1;
- (id)initWithService:(id)arg1 user:(id)arg2;

@end

