//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "RKServiceLocalConnector.h"

@interface RKServiceFacebook : RKServiceLocalConnector
{
    _Bool __needsOfficialApp;
}

+ (_Bool)canHandleObject:(id)arg1;
+ (_Bool)unsupported;
+ (_Bool)canShare;
+ (void)initialize;
- (void)share:(id)arg1;
- (id)initWithService:(id)arg1 user:(id)arg2;

@end

