//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "RKServiceOAuth2Connector.h"

@interface RKServiceFeedly : RKServiceOAuth2Connector
{
}

+ (_Bool)canEditItemTags;
+ (_Bool)canDeleteFolders;
+ (_Bool)canEditFolderTags;
+ (_Bool)canEditFolders;
+ (_Bool)canUnsubscribe;
+ (_Bool)canSubscribe;
+ (_Bool)canSync;
- (id)removeTagWithDictionary:(id)arg1;
- (void)removeTag:(id)arg1 forItem:(id)arg2;
- (id)addTagWithDictionary:(id)arg1;
- (void)addTag:(id)arg1 forItem:(id)arg2;
- (void)createTag:(id)arg1;
- (id)starStateMarkerWithDictionary:(id)arg1;
- (id)readStateMarkerWithDictionary:(id)arg1;
- (void)setStarred:(int)arg1 forItem:(id)arg2;
- (void)setUnread:(int)arg1 forItem:(id)arg2;
- (void)setReadForItems:(id)arg1 stream:(id)arg2 markAll:(_Bool)arg3;
- (void)sync:(id)arg1;
- (void)fetchUserInfo;
- (id)requestWithTarget:(id)arg1 parameters:(id)arg2 method:(id)arg3;
- (_Bool)verifyAuthorization:(id *)arg1;
- (_Bool)recoverFromError:(id)arg1;
- (id)createFolder:(id)arg1 error:(id *)arg2;
- (id)unsubscribe:(id)arg1;
- (id)removeStream:(id)arg1 fromFolder:(id)arg2;
- (id)moveStream:(id)arg1 toFolder:(id)arg2;
- (id)subscribe:(id)arg1 title:(id)arg2 folders:(id)arg3;
- (id)feedUrlStringForStream:(id)arg1;
- (id)opmlEntryForFeed:(id)arg1;
- (void)clearAdditionalCookies;
- (_Bool)canExportSubscriptions;
- (_Bool)authNeedsSafari;
- (_Bool)authNeedsWebView;
- (id)imageNameForFolderStream:(id)arg1;
- (id)initWithService:(id)arg1 user:(id)arg2;

@end

