//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "RKServiceOAuth2Connector.h"

@class NSString;

@interface RKServiceGoogleReader : RKServiceOAuth2Connector
{
    NSString *__editToken;
}

+ (_Bool)canDeleteFolders;
+ (_Bool)canEditFolderTags;
+ (_Bool)canEditFolders;
+ (_Bool)canUnsubscribe;
+ (_Bool)canSubscribe;
+ (_Bool)canSync;
- (void).cxx_destruct;
- (id)unstarWithDictionary:(id)arg1;
- (id)starWithDictionary:(id)arg1;
- (id)readWithDictionary:(id)arg1;
- (id)unreadWithDictionary:(id)arg1;
- (void)setStarred:(int)arg1 forItem:(id)arg2;
- (void)setUnread:(int)arg1 forItem:(id)arg2;
- (void)setReadForItems:(id)arg1 stream:(id)arg2 markAll:(_Bool)arg3;
- (void)sync:(id)arg1;
- (void)getStreamPrefs:(CDUnknownBlockType)arg1;
- (void)getTagList:(CDUnknownBlockType)arg1;
- (void)getFriendList:(CDUnknownBlockType)arg1;
- (void)getSubscriptionList:(CDUnknownBlockType)arg1;
- (void)getUserInfo:(CDUnknownBlockType)arg1;
- (void)getJSON:(id)arg1 handler:(CDUnknownBlockType)arg2;
- (id)getStreamPrefs;
- (id)getTagList;
- (id)getFriendList;
- (id)getSubscriptionList;
- (id)getUserInfo;
- (id)getJSON:(id)arg1;
- (void)fetchUserInfo;
- (double)dateForStarItemOperation:(id)arg1;
- (id)requestWithTarget:(id)arg1 parameters:(id)arg2 method:(id)arg3;
- (_Bool)verifyAuthorization:(id *)arg1;
- (_Bool)recoverFromError:(id)arg1;
@property(readonly, nonatomic) NSString *editToken;
- (id)sortDescriptorForFolder:(id)arg1 ofUser:(id)arg2;
- (id)deleteFolder:(id)arg1;
- (id)createFolder:(id)arg1 error:(id *)arg2;
- (id)unsubscribe:(id)arg1;
- (id)removeStream:(id)arg1 fromFolder:(id)arg2;
- (id)moveStream:(id)arg1 toFolder:(id)arg2;
- (id)subscribe:(id)arg1 title:(id)arg2 folders:(id)arg3;
- (id)feedUrlStringForStream:(id)arg1;
- (id)opmlEntryForFeed:(id)arg1;
- (_Bool)canExportSubscriptions;
- (id)initWithService:(id)arg1 user:(id)arg2;

@end

