//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "RKServiceOAuth2Connector.h"

@class RSFormTextOption;

@interface RKServiceAppNet : RKServiceOAuth2Connector
{
    RSFormTextOption *__actionTitle;
    RSFormTextOption *__actionLink;
    RSFormTextOption *__actionClear;
}

+ (_Bool)canHandleObject:(id)arg1;
+ (_Bool)canShare;
- (void).cxx_destruct;
- (id)shareWithDictionary:(id)arg1;
- (void)shareFormDidSubmit:(id)arg1;
- (id)requestWithTarget:(id)arg1 parameters:(id)arg2 method:(id)arg3;
- (void)prepareShareForm:(id)arg1 forObject:(id)arg2;
- (void)shareForm:(id)arg1 didPickTextOption:(id)arg2;
- (void)shareFormTextDidChange:(id)arg1;
- (void)updateCountForForm:(id)arg1;
- (_Bool)verifyAuthorization:(id *)arg1;
- (void)setupShareForm;
- (void)fetchUserInfo;
- (_Bool)refreshToken:(id *)arg1;
- (_Bool)flashBezelOnShare;
- (id)serviceSheetSaveTitle;
- (id)initWithService:(id)arg1 user:(id)arg2;

@end

