//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "RKServiceLocalConnector.h"

@interface RKServiceCopyLink : RKServiceLocalConnector
{
}

+ (_Bool)canHandleObject:(id)arg1;
+ (_Bool)canShare;
- (_Bool)flashBezelOnShare;
- (void)share:(id)arg1;

@end

