//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "RKServiceOAuthConnector.h"

@interface RKServiceXAuthConnector : RKServiceOAuthConnector
{
}

- (void)setReadForItems:(id)arg1 stream:(id)arg2 markAll:(_Bool)arg3;
- (void)setStarred:(int)arg1 forItem:(id)arg2;
- (void)setUnread:(int)arg1 forItem:(id)arg2;
- (void)sync:(id)arg1;
- (_Bool)recoverFromError:(id)arg1;
- (_Bool)prepare;
- (_Bool)verifyAuthorization:(id *)arg1;
- (void)authorize;
- (void)authFormDidSubmit:(id)arg1;
- (_Bool)authNeedsWebView;
- (void)setupAuthForm;
- (id)initWithService:(id)arg1 user:(id)arg2;

@end

