//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "RKServiceLocalConnector.h"

@class UIPopoverController;

@interface RKServiceMore : RKServiceLocalConnector
{
    UIPopoverController *_activityPopover;
}

+ (_Bool)canHandleObject:(id)arg1;
+ (_Bool)canShare;
+ (id)sharedConnector;
@property(retain, nonatomic) UIPopoverController *activityPopover; // @synthesize activityPopover=_activityPopover;
- (void).cxx_destruct;
- (void)__share:(id)arg1;
- (void)share:(id)arg1;

@end

