//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "RSDataObject.h"

@class NSString, RSSettings;

@interface RKService : RSDataObject
{
    NSString *__oid;
    NSString *__title;
    NSString *__link;
    int __index;
    RSSettings *__sharingSettings;
}

+ (void)createInStore:(id)arg1 oid:(id)arg2 title:(id)arg3 link:(id)arg4 index:(int)arg5;
+ (id)primaryKey;
+ (_Bool)caches;
- (void).cxx_destruct;
@property(readonly, nonatomic) NSString *displayTitle;
@property(readonly, nonatomic) RSSettings *sharingSettings;
- (void)loadSharingSettings;
- (id)connectorForUser:(id)arg1;
@property(readonly, nonatomic) _Bool canShare;
@property(readonly, nonatomic) _Bool canSync;

// Remaining properties
@property int index; // @dynamic index;
@property(copy) NSString *link; // @dynamic link;
@property(copy) NSString *oid; // @dynamic oid;
@property(copy) NSString *title; // @dynamic title;

@end

