//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "RKServiceLocalConnector.h"

@class NSMutableSet;

@interface RKServiceRSS : RKServiceLocalConnector
{
    int __syncingFeed;
    _Bool __syncingAll;
    NSMutableSet *__syncingFeeds;
    NSMutableSet *__syncingFolders;
}

+ (_Bool)canImportOPML;
+ (_Bool)canRenameSubscriptions;
+ (_Bool)canEditItemTags;
+ (_Bool)canDeleteFolders;
+ (_Bool)supportsMultipleUsers;
+ (_Bool)canEditFolderTags;
+ (_Bool)canEditFolders;
+ (_Bool)canUnsubscribe;
+ (_Bool)canSubscribe;
+ (_Bool)canSync;
- (void).cxx_destruct;
- (id)createFolder:(id)arg1 error:(id *)arg2;
- (id)deleteFolder:(id)arg1;
- (void)didDeleteFolder:(id)arg1 withStreams:(id)arg2;
- (id)removeStream:(id)arg1 fromFolder:(id)arg2;
- (id)moveStream:(id)arg1 toFolder:(id)arg2;
- (id)unsubscribe:(id)arg1;
- (void)importFromOPML:(id)arg1;
- (id)subscribe:(id)arg1 title:(id)arg2 folders:(id)arg3 fromOPML:(_Bool)arg4;
- (id)subscribe:(id)arg1 title:(id)arg2 folders:(id)arg3;
- (id)renameSubscription:(id)arg1 withTitle:(id)arg2;
- (void)didImportStarredItems:(id)arg1;
- (void)didImportSubscriptions:(id)arg1;
- (void)didSubscribe;
- (id)feedUrlStringForStream:(id)arg1;
- (id)opmlEntryForFeed:(id)arg1;
- (_Bool)canExportSubscriptions;
- (void)authorize;
- (void)didAuthorize;
- (void)proccessChannel:(id)arg1 forStream:(id)arg2;
- (void)sync:(id)arg1;
- (void)addToSync:(id)arg1;
- (_Bool)syncing:(id)arg1;
- (_Bool)canQueueSync;
- (void)syncDidFail:(id)arg1;
- (void)syncDidSucceed;
- (void)syncDidStart:(id)arg1;
- (void)setStarred:(int)arg1 forItem:(id)arg2;
- (void)backupStarredItems:(id)arg1;
- (void)backupStreams:(id)arg1;
- (id)stringSyncing;
- (id)stringNotSyncedYet;
- (_Bool)authorized;
- (id)imageNameForFolderStream:(id)arg1;
- (int)maxConcurrentOperations;
- (id)initWithService:(id)arg1 user:(id)arg2;

@end

