//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "RKServiceXAuthConnector.h"

@interface RKServiceInstapaper : RKServiceXAuthConnector
{
}

+ (_Bool)canHandleObject:(id)arg1;
+ (_Bool)canDeleteItems;
+ (_Bool)hasMutlipleItemTags;
+ (_Bool)canEditItemTags;
+ (_Bool)canSync;
+ (_Bool)canShare;
+ (_Bool)isReadLaterService;
- (void)sync:(id)arg1;
- (id)removeTagWithDictionary:(id)arg1;
- (void)removeTag:(id)arg1 forItem:(id)arg2;
- (id)addTagWithDictionary:(id)arg1;
- (void)addTag:(id)arg1 forItem:(id)arg2;
- (id)createTagWithDictionary:(id)arg1;
- (void)createTag:(id)arg1;
- (id)deleteItemWithDictionary:(id)arg1;
- (void)deleteItem:(id)arg1;
- (id)editBookmarkWithDictionary:(id)arg1;
- (void)setStarred:(int)arg1 forItem:(id)arg2;
- (void)setUnread:(int)arg1 forItem:(id)arg2;
- (void)setReadForItems:(id)arg1 stream:(id)arg2 markAll:(_Bool)arg3;
- (id)shareWithDictionary:(id)arg1;
- (void)share:(id)arg1;
- (void)checkSubscriptionStatusWithResponse:(id)arg1;
- (void)checkSubscriptionStatus;
- (_Bool)verifyAuthorization:(id *)arg1;
- (void)fetchUserInfo;
- (_Bool)checkUserWithUserInfo;
- (id)imageNameForFolderStream:(id)arg1;
- (_Bool)flashBezelOnShare;
- (id)titleForDidUnread;
- (id)titleForDidRead;
- (id)titleForToggleRead;
- (id)titleForUnread;
- (id)titleForRead;
- (id)initWithService:(id)arg1 user:(id)arg2;

@end

