//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSError, NSString, RKServiceConnector;

@protocol RKServiceConnectorUIDelegate <NSObject>
- (_Bool)serviceConnector:(RKServiceConnector *)arg1 shouldOpenUrl:(NSString *)arg2;
- (void)serviceConnectorDidEndModalSession:(RKServiceConnector *)arg1 withError:(NSError *)arg2;
- (void)serviceConnectorWillStartModalSession:(RKServiceConnector *)arg1;
- (_Bool)serviceConnectorWillSaveNewUser:(RKServiceConnector *)arg1;
@end

