//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface RKServiceController : NSObject
{
}

+ (id)defaultController;
- (id)usersForServiceConnectorClass:(Class)arg1;
- (id)usersForService:(id)arg1;
- (id)enabledSharingServicesForObject:(id)arg1;
- (id)enabledSharingServices;
- (id)allSharingServices:(_Bool)arg1;
- (id)allSharingServices;
- (void)updateSystemSharingServicesWithStore:(id)arg1;
- (id)allSyncingServices;

@end

