//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "RKServiceOAuth2Connector.h"

@interface RKServiceBuffer : RKServiceOAuth2Connector
{
}

+ (_Bool)canHandleObject:(id)arg1;
+ (_Bool)canShare;
- (void)prepareShareForm:(id)arg1 forObject:(id)arg2;
- (void)shareForm:(id)arg1 didPickTextOption:(id)arg2;
- (void)shareFormTextDidChange:(id)arg1;
- (void)updateCountForForm:(id)arg1;
- (id)shareWithDictionary:(id)arg1;
- (void)shareFormDidSubmit:(id)arg1;
- (id)requestWithTarget:(id)arg1 parameters:(id)arg2 method:(id)arg3;
- (void)fetchUserInfo;
- (_Bool)verifyAuthorization:(id *)arg1;
- (id)profiles;
- (void)fetchProfiles:(CDUnknownBlockType)arg1;
- (id)fetchProfiles;
- (void)setupShareForm;
- (_Bool)flashBezelOnShare;
- (id)serviceSheetSaveTitle;
- (id)initWithService:(id)arg1 user:(id)arg2;

@end

