//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, RKItem, RKItemData, UIImage;

@interface RKShareObject : NSObject
{
    RKItem *item;
    RKItemData *__itemData;
    UIImage *__image;
    NSString *__imageSrc;
    NSString *__imageLink;
    NSString *srcUrl;
    NSString *srcTitle;
    NSString *url;
    NSString *title;
    NSString *summary;
    _Bool isGoogleMobilized;
    _Bool isInstapaperMobilized;
    int __type;
    NSString *content;
    id __delegate;
    _Bool __isLinkOnly;
}

+ (id)shareObjectWithItem:(id)arg1;
@property(copy, nonatomic) NSString *content; // @synthesize content;
@property(readonly, nonatomic) _Bool isInstapaperMobilized; // @synthesize isInstapaperMobilized;
@property(readonly, nonatomic) _Bool isGoogleMobilized; // @synthesize isGoogleMobilized;
@property(copy, nonatomic) NSString *summary; // @synthesize summary;
@property(copy, nonatomic) NSString *title; // @synthesize title;
@property(copy, nonatomic) NSString *url; // @synthesize url;
@property(copy, nonatomic) NSString *srcTitle; // @synthesize srcTitle;
@property(copy, nonatomic) NSString *srcUrl; // @synthesize srcUrl;
@property(copy, nonatomic) NSString *imageLink; // @synthesize imageLink=__imageLink;
@property(copy, nonatomic) NSString *imageSrc; // @synthesize imageSrc=__imageSrc;
@property(retain, nonatomic) UIImage *image; // @synthesize image=__image;
@property(retain, nonatomic) RKItem *item; // @synthesize item;
@property(nonatomic) int type; // @synthesize type=__type;
@property(nonatomic) _Bool isLinkOnly; // @synthesize isLinkOnly=__isLinkOnly;
@property(nonatomic) __weak id delegate; // @synthesize delegate=__delegate;
- (void).cxx_destruct;
@property(readonly, nonatomic) NSString *sentWithReeder;
@property(readonly, nonatomic) NSString *titleButtonHeader;
@property(readonly, nonatomic) NSString *titleButtonFooter;
- (id)description;
@property(readonly, nonatomic) _Bool isArticle;
@property(readonly, nonatomic) RKItemData *itemData;
- (_Bool)isEqual:(id)arg1;
- (void)useItem:(id)arg1;
- (id)initWithItem:(id)arg1;
- (id)init;

@end

