//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "RSDataObject.h"

@class RKItem, RKStream, RKUser;

@interface RKSmartStreamItem : RSDataObject
{
    id __stream;
    id __item;
    id __user;
    double __publishedDate;
    double __dayPublished;
    int __unread;
    int __starred;
    int __d;
}

+ (id)primaryKey;
+ (void)createTableWithStore:(id)arg1;
+ (_Bool)caches;
- (void).cxx_destruct;
- (void)markForDeletion;

// Remaining properties
@property int d; // @dynamic d;
@property double dayPublished; // @dynamic dayPublished;
@property(retain, nonatomic) RKItem *item; // @dynamic item;
@property double publishedDate; // @dynamic publishedDate;
@property int starred; // @dynamic starred;
@property(retain, nonatomic) RKStream *stream; // @dynamic stream;
@property int unread; // @dynamic unread;
@property(retain, nonatomic) RKUser *user; // @dynamic user;

@end

