//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "RSDataObject.h"

@class NSString, RKStream, RKUser;

@interface RKStreamTag : RSDataObject
{
    id __feed;
    id __folder;
    id __user;
    long long __longLongValue;
    NSString *__stringValue;
}

+ (id)primaryKey;
+ (_Bool)caches;
- (void).cxx_destruct;

// Remaining properties
@property(retain, nonatomic) RKStream *feed; // @dynamic feed;
@property(retain, nonatomic) RKStream *folder; // @dynamic folder;
@property(nonatomic) long long longLongValue; // @dynamic longLongValue;
@property(copy, nonatomic) NSString *stringValue; // @dynamic stringValue;
@property(retain, nonatomic) RKUser *user; // @dynamic user;

@end

