//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "RSDataObject.h"

#import "RKServiceConnectorDelegate-Protocol.h"

@class NSMutableArray, NSMutableSet, NSString, RKService, RKServiceConnector, RSSettings;

@interface RKUser : RSDataObject <RKServiceConnectorDelegate>
{
    NSString *__oid;
    id __service;
    NSString *__title;
    NSString *__username;
    int __unreadCount;
    int __starredCount;
    int __itemCount;
    NSString *__data1;
    NSString *__data2;
    double __lastSyncDate;
    int __index;
    _Bool __sync;
    RKServiceConnector *__connector;
    _Bool __editing;
    _Bool __needsEdit;
    NSMutableArray *__editHandlers;
    RSSettings *__settings;
    NSString *__syncStatusText;
    NSMutableSet *__localUnread;
    NSMutableSet *__localRead;
    NSMutableSet *__localStarred;
    NSMutableSet *__localUnstarred;
    NSString *__offlineCacheDirectoryPath;
    NSString *__deletedOfflineCacheDirectoryPath;
    _Bool _needsSync;
    NSString *_destroyedUserDisplayTitle;
    double _destroyedUserLastSyncDate;
}

+ (void)refreshCountsForStore:(id)arg1 withChangeSet:(id)arg2;
+ (void)clearUsersInStore:(id)arg1;
+ (void)clearDeletedCache;
+ (void)clearCache;
+ (id)primaryKey;
+ (_Bool)caches;
@property(nonatomic) double destroyedUserLastSyncDate; // @synthesize destroyedUserLastSyncDate=_destroyedUserLastSyncDate;
@property(copy, nonatomic) NSString *destroyedUserDisplayTitle; // @synthesize destroyedUserDisplayTitle=_destroyedUserDisplayTitle;
@property(nonatomic) _Bool needsSync; // @synthesize needsSync=_needsSync;
- (void).cxx_destruct;
@property(readonly, nonatomic) _Bool syncOnStart;
@property(readonly, nonatomic) _Bool prefReadsArticleOnOpen;
@property(readonly, nonatomic) NSString *displayTitle;
@property(readonly, nonatomic) RSSettings *settings;
- (void)loadSettings;
- (void)edit:(id)arg1;
- (void)__didFinishEditing;
- (void)dequeueEditor:(CDUnknownBlockType)arg1;
- (int)starred:(int)arg1 item:(id)arg2;
- (int)unread:(int)arg1 item:(id)arg2;
- (id)offlineCacheDirectoryPathForDeletedItem:(id)arg1;
- (id)offlineCacheDirectoryPathForItem:(id)arg1;
- (id)deletedOfflineCacheDirectoryPath;
- (id)offlineCacheDirectoryPath;
- (void)emptyLocalStateCache;
- (void)localUnstarred:(id)arg1;
- (void)localStarred:(id)arg1;
- (void)localUnread:(id)arg1;
- (void)localReads:(id)arg1;
- (void)localRead:(id)arg1;
@property(readonly, nonatomic) _Bool editing;
- (_Bool)hasSubscriptionWithUrl:(id)arg1;
@property(readonly, nonatomic) _Bool hasStarredItems;
@property(readonly, nonatomic) _Bool hasUnreadItems;
@property(readonly, nonatomic) int currentItemCount;
@property(readonly, nonatomic) int currentStarredCount;
@property(readonly, nonatomic) int currentUnreadCount;
- (void)__updStarredCount:(int)arg1 withChangeSet:(id)arg2;
- (void)__updUnreadCount:(int)arg1 withChangeSet:(id)arg2;
- (void)refreshCountsWithChangeSet:(id)arg1;
@property(copy, nonatomic) NSString *syncStatusText; // @synthesize syncStatusText=__syncStatusText;
- (id)sortDescriptorForFolder:(id)arg1;
- (void)cancelSyncing;
- (_Bool)syncing:(id)arg1;
- (_Bool)syncing;
- (void)sync:(id)arg1 handler:(CDUnknownBlockType)arg2;
- (void)sync:(CDUnknownBlockType)arg1;
- (void)serviceConnector:(id)arg1 didFailToAuthorize:(id)arg2;
- (void)serviceConnectorDidAuthorize:(id)arg1;
@property(retain, nonatomic) RKServiceConnector *connector; // @synthesize connector=__connector;
- (void)dealloc;
- (void)deleteAccount:(CDUnknownBlockType)arg1;
- (void)replaceOidWith:(id)arg1;
- (id)initWithObjectID:(id)arg1 store:(id)arg2;

// Remaining properties
@property(copy) NSString *data1; // @dynamic data1;
@property(copy) NSString *data2; // @dynamic data2;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property int index; // @dynamic index;
@property(readonly) int itemCount; // @dynamic itemCount;
@property double lastSyncDate; // @dynamic lastSyncDate;
@property(copy) NSString *oid; // @dynamic oid;
@property(retain) RKService *service; // @dynamic service;
@property(readonly) int starredCount; // @dynamic starredCount;
@property(readonly) Class superclass;
@property _Bool sync; // @dynamic sync;
@property(copy) NSString *title; // @dynamic title;
@property(readonly) int unreadCount; // @dynamic unreadCount;
@property(copy) NSString *username; // @dynamic username;

@end

