//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "RSDataObjectList.h"

@interface RKUserList : RSDataObjectList
{
}

- (Class)contentsEntity;

@end

