//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@protocol RootViewDelegate;

@interface RootView : UIView
{
    id <RootViewDelegate> _rootViewDelegate;
}

@property(nonatomic) __weak id <RootViewDelegate> rootViewDelegate; // @synthesize rootViewDelegate=_rootViewDelegate;
- (void).cxx_destruct;
- (void)setFrame:(struct CGRect)arg1;
- (void)removeFromSuperview;
- (id)initWithFrame:(struct CGRect)arg1;

@end

