//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SlidingViewController.h"

#import "RootViewDelegate-Protocol.h"

@class ArticleViewController, BrowserViewController, FolderSubscriptionsViewController, ItemsViewController, NSString, SubscriptionsViewController, UIView, UsersViewController;

@interface RootViewController : SlidingViewController <RootViewDelegate>
{
    long long _baseSubviewCount;
    _Bool keyDown;
    _Bool markArticleOnKeyUp;
    long long __preferredStatusBarStyle;
    _Bool __prefersStatusBarHidden;
    long long __preferredStatusBarUpdateAnimation;
    _Bool __forceStatusBarHidden;
    _Bool __showingIntro;
    _Bool __viewIsDisappeared;
    _Bool __viewIsDisappearing;
    UsersViewController *_usersViewController;
    SubscriptionsViewController *_subscriptionsViewController;
    FolderSubscriptionsViewController *_folderViewController;
    ItemsViewController *_itemsViewController;
    ArticleViewController *_articleViewController;
    BrowserViewController *_webViewController;
    UIView *_blackStatusBarView;
}

@property(readonly, nonatomic) UIView *blackStatusBarView; // @synthesize blackStatusBarView=_blackStatusBarView;
@property(readonly, nonatomic) BrowserViewController *webViewController; // @synthesize webViewController=_webViewController;
@property(readonly, nonatomic) ArticleViewController *articleViewController; // @synthesize articleViewController=_articleViewController;
@property(readonly, nonatomic) ItemsViewController *itemsViewController; // @synthesize itemsViewController=_itemsViewController;
@property(readonly, nonatomic) FolderSubscriptionsViewController *folderViewController; // @synthesize folderViewController=_folderViewController;
@property(readonly, nonatomic) SubscriptionsViewController *subscriptionsViewController; // @synthesize subscriptionsViewController=_subscriptionsViewController;
@property(readonly, nonatomic) UsersViewController *usersViewController; // @synthesize usersViewController=_usersViewController;
- (void).cxx_destruct;
- (void)didSnapToViewController:(id)arg1;
- (void)willSnapToViewController:(id)arg1;
- (void)presentSafariViewController:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)presentViewController:(id)arg1 animated:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;
- (long long)preferredStatusBarStyle;
- (_Bool)prefersStatusBarHidden;
- (void)__setStatusBarHidden:(_Bool)arg1;
- (void)setStatusBarHidden:(_Bool)arg1;
- (long long)preferredStatusBarUpdateAnimation;
- (void)__updateStatusBarStyle:(id)arg1;
- (void)__updatePadStatusBar;
- (void)layoutViewControllers:(_Bool)arg1 forInterfaceOrientation:(long long)arg2;
- (void)setPreferesHiddenStatusBar:(_Bool)arg1;
- (void)setPreferesHiddenStatusBarIfAllowed:(_Bool)arg1;
- (void)handleRightNavigationPan:(id)arg1;
- (void)handleLeftNavigationPan:(id)arg1;
- (id)proposedSnapController:(id)arg1 forRotationToInterfaceOrientation:(long long)arg2;
- (void)hideFolderViewController:(_Bool)arg1;
- (void)showFolderViewController:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)didRotateFromInterfaceOrientation:(long long)arg1;
- (void)willAnimateRotationToInterfaceOrientation:(long long)arg1 duration:(double)arg2;
- (void)willRotateToInterfaceOrientation:(long long)arg1 duration:(double)arg2;
- (void)rootViewFrameDidChange:(struct CGRect)arg1;
@property(readonly, nonatomic) _Bool isProPortrait;
- (_Bool)shouldAutorotate;
- (void)helpDone:(id)arg1;
- (void)viewDidLoad;
- (void)loadView;
- (void)painterDidChange:(id)arg1;
- (void)dealloc;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)snapToArticleViewer;
- (_Bool)isSnappedToArticleViewer;
- (void)viewInBrowserExternal:(_Bool)arg1;
- (void)viewInBrowser:(id)arg1;
- (void)navForward:(id)arg1;
- (void)navBack:(id)arg1;
- (void)scrollUp:(id)arg1;
- (void)scrollDown:(id)arg1;
- (void)prev:(id)arg1;
- (void)next:(id)arg1;
- (void)toggleStarred:(id)arg1;
- (void)toggleUnread:(id)arg1;
- (void)toggleReadability:(id)arg1;
- (void)showAccounts:(id)arg1;
- (void)settings:(_Bool)arg1;
- (void)filterAll:(id)arg1;
- (void)filterUnread:(id)arg1;
- (void)filterStarred:(id)arg1;
- (void)syncCurrent:(id)arg1;
- (void)syncAll:(id)arg1;
- (id)keyCommands;
- (long long)numberOfSubviews;
- (_Bool)canBecomeFirstResponder;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

