//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSString;

@protocol RSAlert <NSObject>

@optional
+ (void)presentInput:(NSString *)arg1 withTitle:(NSString *)arg2 placeholder:(NSString *)arg3 description:(NSString *)arg4 buttonTitle:(NSString *)arg5 cancelButtonTitle:(NSString *)arg6 handler:(void (^)(NSString *))arg7;
+ (void)presentSheetWithTitle:(NSString *)arg1 buttonTitle:(NSString *)arg2 cancelButtonTitle:(NSString *)arg3 handler:(void (^)(void))arg4 inView:(id)arg5;
+ (void)presentSheetWithTitle:(NSString *)arg1 buttonTitle:(NSString *)arg2 cancelButtonTitle:(NSString *)arg3 handler:(void (^)(void))arg4;
+ (void)presentWithTitle:(NSString *)arg1 message:(NSString *)arg2 buttonTitle:(NSString *)arg3 handler:(void (^)(void))arg4;
+ (void)presentWithImage:(id)arg1 buttonTitle:(NSString *)arg2 handler:(void (^)(void))arg3;
@end

