//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableDictionary, NSMutableSet, RSDataSQLiteStatement;
@protocol OS_dispatch_queue;

@interface RSDataObjectCache : NSObject
{
    Class __entity;
    NSMutableDictionary *__objectID;
    NSMutableDictionary *__rowID;
    RSDataSQLiteStatement *__stmtInsert;
    RSDataSQLiteStatement *__stmtUpdate;
    RSDataSQLiteStatement *__stmtDestroy;
    RSDataSQLiteStatement *__stmtFindByObjectID;
    RSDataSQLiteStatement *__stmtFindByRowId;
    RSDataSQLiteStatement *__stmtRowIdExists;
    CDUnknownBlockType __fetchBlock;
    NSMutableSet *__cache;
    NSMutableSet *__weakCache;
    NSObject<OS_dispatch_queue> *__lock;
}

@property(copy, nonatomic) CDUnknownBlockType fetchBlock; // @synthesize fetchBlock=__fetchBlock;
@property(retain, nonatomic) RSDataSQLiteStatement *stmtRowIdExists; // @synthesize stmtRowIdExists=__stmtRowIdExists;
@property(retain, nonatomic) RSDataSQLiteStatement *stmtFindByRowId; // @synthesize stmtFindByRowId=__stmtFindByRowId;
@property(retain, nonatomic) RSDataSQLiteStatement *stmtFindByObjectID; // @synthesize stmtFindByObjectID=__stmtFindByObjectID;
@property(retain, nonatomic) RSDataSQLiteStatement *stmtDestroy; // @synthesize stmtDestroy=__stmtDestroy;
@property(retain, nonatomic) RSDataSQLiteStatement *stmtUpdate; // @synthesize stmtUpdate=__stmtUpdate;
@property(retain, nonatomic) RSDataSQLiteStatement *stmtInsert; // @synthesize stmtInsert=__stmtInsert;
@property(readonly, nonatomic) Class entity; // @synthesize entity=__entity;
- (void).cxx_destruct;
- (id)fetch:(id)arg1;
- (void)empty;
- (void)batchUpdate:(id)arg1;
- (void)update:(id)arg1;
- (void)forceRemove:(id)arg1;
- (void)remove:(id)arg1;
- (void)removeObjectWithRowID:(id)arg1 objectID:(id)arg2;
- (void)add:(id)arg1;
- (id)objectWithObjectID:(id)arg1;
- (id)objectWithRowID:(id)arg1;
- (id)objectWithRowId:(long long)arg1;
- (void)dealloc;
- (id)initWithEntity:(Class)arg1;

@end

