//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSNumber, RSDataObjectCache, RSDataObjectID, RSDataObjectInfo, RSDataSQLiteStatement, RSDataStore, RSWeakObject;

@interface RSDataObject : NSObject
{
    RSDataObjectID *__objectID;
    long long __rowId;
    _Bool __isDestroyed;
    RSDataStore *__store;
    long long __changes;
    RSDataObjectCache *__cache;
    RSWeakObject *__wrappedObject;
}

+ (id)objectID:(id)arg1;
+ (id)recordWithStore:(id)arg1;
+ (void)loadWithStore:(id)arg1;
+ (void)dropIndex:(id)arg1 withStore:(id)arg2;
+ (void)createUniqueIndex:(id)arg1 withStore:(id)arg2;
+ (void)createIndex:(id)arg1 withStore:(id)arg2;
+ (void)createTableWithStore:(id)arg1;
+ (id)stmtRowIdExistsWithStore:(id)arg1;
+ (id)stmtFindByRowIdWithStore:(id)arg1;
+ (id)stmtFindByObjectIDWithStore:(id)arg1;
+ (id)stmtDestroyWithStore:(id)arg1;
+ (id)stmtUpdateWithStore:(id)arg1;
+ (id)stmtInsertWithStore:(id)arg1;
+ (_Bool)resolveInstanceMethod:(SEL)arg1;
+ (id)cachedObjectWithObjectID:(id)arg1 inStore:(id)arg2;
+ (id)cachedObjectWithRowID:(id)arg1 inStore:(id)arg2;
+ (id)cachedObjectWithRowId:(long long)arg1 inStore:(id)arg2;
+ (id)cacheForStore:(id)arg1;
+ (_Bool)caches;
+ (id)tableName;
+ (id)primaryKey;
+ (id)info;
+ (id)fetch:(id)arg1 fromStore:(id)arg2 limit:(long long)arg3 sortDescriptors:(id)arg4 cancelDelegate:(id)arg5 forceReadFromStore:(_Bool)arg6;
+ (id)fetch:(id)arg1 fromStore:(id)arg2 limit:(long long)arg3 sortDescriptors:(id)arg4 cancelDelegate:(id)arg5;
+ (id)fetch:(id)arg1 fromStore:(id)arg2 limit:(long long)arg3 sortDescriptors:(id)arg4;
+ (id)fetch:(id)arg1 fromStore:(id)arg2;
+ (id)existingObjectWithObjectID:(id)arg1 inStore:(id)arg2 create:(_Bool)arg3;
+ (id)existingObjectWithObjectID:(id)arg1 inStore:(id)arg2;
+ (id)existingObjectWithRowID:(id)arg1 inStore:(id)arg2;
+ (id)existingObjectWithRowId:(long long)arg1 inStore:(id)arg2;
- (void).cxx_destruct;
@property(readonly, nonatomic) RSWeakObject *wrappedObject;
- (void)markDestroyed;
- (void)clearChanges;
@property(readonly, nonatomic) _Bool isDestroyed;
@property(readonly, nonatomic) _Bool hasChanges;
@property(readonly, nonatomic) _Bool isNew;
- (void)createObjectID;
@property(readonly, nonatomic) RSDataObjectID *objectID;
@property(readonly, nonatomic) NSNumber *rowID;
@property(nonatomic) long long rowId;
- (long long)id;
- (long long)compare:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)dealloc;
- (_Bool)allowsWeakReference;
- (id)init;
- (id)initWithObjectID:(id)arg1 store:(id)arg2;
- (id)initWithStore:(id)arg1;
@property(readonly, nonatomic) RSDataSQLiteStatement *stmtRowIdExists;
@property(readonly, nonatomic) RSDataSQLiteStatement *stmtFindByRowId;
@property(readonly, nonatomic) RSDataSQLiteStatement *stmtFindByObjectID;
@property(readonly, nonatomic) RSDataSQLiteStatement *stmtDestroy;
@property(readonly, nonatomic) RSDataSQLiteStatement *stmtUpdate;
@property(readonly, nonatomic) RSDataSQLiteStatement *stmtInsert;
- (void)bindColumns:(id)arg1;
- (void)bindColumn:(id)arg1 toStatement:(id)arg2;
@property(readonly, nonatomic) RSDataObjectCache *cache;
@property(readonly, nonatomic) RSDataObjectInfo *info;
- (void)didDestroy;
- (void)willDestroy;
- (void)didSave;
- (void)willSave;
- (void)destroyWhere:(id)arg1;
- (void)update:(id)arg1 where:(id)arg2;
- (void)destroy;
- (void)save:(CDUnknownBlockType)arg1;
- (void)save;
- (void)fetchFromStatement:(id)arg1;
- (void)fetch;
@property(readonly, nonatomic) RSDataStore *store;

@end

