//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, RSDataSQLite;

@interface RSDataSQLiteStatement : NSObject
{
    struct sqlite3_stmt *__stmt;
    RSDataSQLite *__db;
    NSString *__sql;
    int __column;
}

+ (void)finalizeAll;
+ (void)setCancelled:(_Bool)arg1;
+ (_Bool)cancelled;
@property(readonly, nonatomic) NSString *sql; // @synthesize sql=__sql;
- (void).cxx_destruct;
- (long long)rowIdValue;
- (void)setRowId:(long long)arg1;
- (double)doubleValue;
- (float)floatValue;
- (unsigned long long)unsignedLongLongValue;
- (unsigned long long)unsignedLongValue;
- (unsigned int)unsignedIntValue;
- (unsigned short)unsignedShortValue;
- (unsigned char)unsignedCharValue;
- (long long)longLongValue;
- (long long)longValue;
- (int)intValue;
- (short)shortValue;
- (BOOL)charValue;
- (id)textValue;
- (void)resetFetchColumn;
- (void)setDouble:(double)arg1;
- (void)setFloat:(float)arg1;
- (void)setUnsignedLongLong:(unsigned long long)arg1;
- (void)setUnsignedLong:(unsigned long long)arg1;
- (void)setUnsignedInt:(unsigned int)arg1;
- (void)setUnsignedShort:(unsigned short)arg1;
- (void)setUnsignedChar:(unsigned char)arg1;
- (void)setLongLong:(long long)arg1;
- (void)setLong:(long long)arg1;
- (void)setInt:(int)arg1;
- (void)setShort:(short)arg1;
- (void)setChar:(BOOL)arg1;
- (void)setText:(id)arg1;
- (long long)changes;
- (long long)lastInsertId;
- (void)execute:(CDUnknownBlockType)arg1 step:(CDUnknownBlockType)arg2 finalize:(CDUnknownBlockType)arg3;
- (long long)execute:(CDUnknownBlockType)arg1 finalizeWithLastId:(CDUnknownBlockType)arg2;
- (long long)execute:(CDUnknownBlockType)arg1 finalize:(CDUnknownBlockType)arg2;
- (void)execute:(CDUnknownBlockType)arg1 step:(CDUnknownBlockType)arg2;
- (long long)execute:(CDUnknownBlockType)arg1;
- (_Bool)next;
- (long long)execute;
- (void)reset;
- (void)finalizeStatement;
@property(readonly, nonatomic) _Bool cancelled;
- (void)dealloc;
- (_Bool)allowsWeakReference;
- (id)initWithSQL:(id)arg1 db:(id)arg2;
- (void)setColumn:(id)arg1 withValue:(id)arg2;

@end

