//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface RSDataSQLite : NSObject
{
    struct sqlite3 *__handle;
    NSString *__name;
}

+ (id)errorDescriptionForCode:(int)arg1;
+ (void)log:(int)arg1;
- (void).cxx_destruct;
- (long long)changes;
- (long long)lastInsertId;
- (int)execute:(id)arg1;
- (id)statementWithSQL:(id)arg1;
- (void)close;
@property(readonly, nonatomic) struct sqlite3 *handle;
- (void)dealloc;
- (_Bool)allowsWeakReference;
- (id)initWithName:(id)arg1;

@end

