//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSDictionary, NSMutableDictionary, NSString;

@interface RSDataObjectInfo : NSObject
{
    NSArray *__columns;
    NSArray *__columnNames;
    NSString *__tableName;
    NSArray *__primaryKey;
    NSMutableDictionary *__columnsMap;
}

@property(copy, nonatomic) NSArray *primaryKey; // @synthesize primaryKey=__primaryKey;
@property(copy, nonatomic) NSArray *columns; // @synthesize columns=__columns;
@property(copy, nonatomic) NSString *tableName; // @synthesize tableName=__tableName;
- (void).cxx_destruct;
- (id)propertyWithName:(id)arg1;
@property(readonly, nonatomic) unsigned long long countOfColumns;
@property(readonly, nonatomic) NSDictionary *columnsMap;
@property(readonly, nonatomic) NSArray *columnNames;
- (id)description;
- (id)init;

@end

