//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "RSDataStoring-Protocol.h"

@class NSMutableDictionary, NSString, RSDataSQLite, RSQueue;

@interface RSDataStore : NSObject <RSDataStoring>
{
    RSQueue *__writeQueue;
    NSString *__name;
    RSDataSQLite *__db;
    NSMutableDictionary *__entityCaches;
}

+ (id)storeWithName:(id)arg1;
+ (id)existingStoreWithName:(id)arg1;
@property(readonly, nonatomic) NSString *name; // @synthesize name=__name;
@property(readonly, nonatomic) RSDataSQLite *db; // @synthesize db=__db;
@property(readonly, nonatomic) RSQueue *writeQueue; // @synthesize writeQueue=__writeQueue;
- (void).cxx_destruct;
- (void)destroy:(Class)arg1 where:(id)arg2;
- (void)update:(Class)arg1 set:(id)arg2 where:(id)arg3 postChangesBeforeCommit:(_Bool)arg4;
- (void)update:(Class)arg1 set:(id)arg2 where:(id)arg3;
- (void)destroy:(id)arg1;
- (void)save:(id)arg1 handler:(CDUnknownBlockType)arg2;
- (void)save:(id)arg1;
- (void)execute:(id)arg1;
- (void)doDestroy:(Class)arg1 where:(id)arg2 withChangeSet:(id)arg3;
- (void)doUpdate:(Class)arg1 set:(id)arg2 where:(id)arg3 withChangeSet:(id)arg4 postChangesBeforeCommit:(_Bool)arg5;
- (void)doDestroy:(id)arg1 withChangeSet:(id)arg2;
- (void)doSave:(id)arg1 withChangeSet:(id)arg2;
- (void)doExecute:(id)arg1;
- (void)writePrioritized:(CDUnknownBlockType)arg1;
- (void)write:(CDUnknownBlockType)arg1;
- (id)begin;
- (id)executeFetchRequest:(id)arg1 sort:(_Bool)arg2 cancelDelegate:(id)arg3;
- (id)executeFetchRequest:(id)arg1 sort:(_Bool)arg2;
- (id)executeFetchRequest:(id)arg1;
- (id)existingObjectWithObjectID:(id)arg1 create:(_Bool)arg2;
- (id)existingObjectWithObjectID:(id)arg1;
- (id)cachedObjectWithObjectID:(id)arg1;
- (id)cacheForEntity:(Class)arg1;
- (id)initWithName:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

