//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface RSDataSQLiteQuery : NSObject
{
}

+ (id)list:(id)arg1 separator:(id)arg2;
+ (id)set:(id)arg1;
+ (id)destroy:(id)arg1 where:(id)arg2;
+ (id)update:(id)arg1 preparedColumns:(id)arg2 where:(id)arg3;
+ (id)update:(id)arg1 columns:(id)arg2 values:(id)arg3 where:(id)arg4;
+ (id)update:(id)arg1 set:(id)arg2 where:(id)arg3;
+ (id)insert:(id)arg1 preparedColumns:(id)arg2;
+ (id)insert:(id)arg1 columns:(id)arg2 values:(id)arg3;
+ (id)select:(id)arg1 columns:(id)arg2 where:(id)arg3;

@end

