//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCopying-Protocol.h"

@class NSDictionary, NSMutableDictionary, RSDataObjectInfo;

@interface RSDataObjectID : NSObject <NSCopying>
{
    Class __entity;
    NSMutableDictionary *__keys;
    long long __hash;
}

@property(readonly) NSDictionary *keys; // @synthesize keys=__keys;
@property __weak Class entity; // @synthesize entity=__entity;
- (void).cxx_destruct;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (void)setObject:(id)arg1 forKey:(id)arg2;
- (id)description;
@property(readonly) RSDataObjectInfo *info;
- (void)clear;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)init;

@end

