//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDictionary, NSMutableDictionary, RSDataStore;

@interface RSDataChangeSet : NSObject
{
    NSMutableDictionary *__changes;
    RSDataStore *__store;
}

@property(readonly, nonatomic) NSDictionary *changesDictionary; // @synthesize changesDictionary=__changes;
@property(readonly, nonatomic) __weak RSDataStore *store; // @synthesize store=__store;
- (void).cxx_destruct;
- (void)post;
- (void)destroy:(Class)arg1 withPredicate:(id)arg2;
- (void)update:(Class)arg1 withPredicate:(id)arg2;
- (void)destroy:(id)arg1;
- (void)update:(id)arg1;
- (void)insert:(id)arg1;
- (id)__destroySetForEntity:(Class)arg1;
- (id)__updateSetForEntity:(Class)arg1;
- (id)__insertSetForEntity:(Class)arg1;
- (id)__changeSetForEntity:(Class)arg1;
- (id)initWithStore:(id)arg1;

@end

