//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface RSEventHandler : NSObject
{
}

+ (id)defaultHandler;
- (void)handleUrl:(id)arg1;
- (id)init;

@end

