//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSMutableArray;

@interface RSFetchedResultsChanges : NSObject
{
    NSMutableArray *__inserts;
    NSMutableArray *__updates;
    NSMutableArray *__deletes;
    NSMutableArray *__sectionInserts;
    NSMutableArray *__sectionUpdates;
    NSMutableArray *__sectionDeletes;
    NSMutableArray *__insertedObjects;
    NSMutableArray *__updatedObjects;
    NSMutableArray *__deletedObjects;
    NSMutableArray *__insertedSections;
    NSMutableArray *__updatedSections;
    NSMutableArray *__deletedSections;
}

@property(readonly, nonatomic) NSArray *deletedObjects; // @synthesize deletedObjects=__deletedObjects;
@property(readonly, nonatomic) NSArray *updatedObjects; // @synthesize updatedObjects=__updatedObjects;
@property(readonly, nonatomic) NSArray *insertedObjects; // @synthesize insertedObjects=__insertedObjects;
@property(readonly, nonatomic) NSArray *deletedSections; // @synthesize deletedSections=__deletedSections;
@property(readonly, nonatomic) NSArray *updatedSections; // @synthesize updatedSections=__updatedSections;
@property(readonly, nonatomic) NSArray *insertedSections; // @synthesize insertedSections=__insertedSections;
@property(readonly, nonatomic) NSArray *sectionDeletes; // @synthesize sectionDeletes=__sectionDeletes;
@property(readonly, nonatomic) NSArray *sectionUpdates; // @synthesize sectionUpdates=__sectionUpdates;
@property(readonly, nonatomic) NSArray *sectionInserts; // @synthesize sectionInserts=__sectionInserts;
@property(readonly, nonatomic) NSArray *deletes; // @synthesize deletes=__deletes;
@property(readonly, nonatomic) NSArray *updates; // @synthesize updates=__updates;
@property(readonly, nonatomic) NSArray *inserts; // @synthesize inserts=__inserts;
- (void).cxx_destruct;
- (void)addRecordInserts:(id)arg1;
- (void)addRecordUpdates:(id)arg1;
- (void)addRecordDeletes:(id)arg1;
- (void)addSection:(id)arg1 from:(long long)arg2 to:(long long)arg3;
- (void)add:(id)arg1 from:(id)arg2 to:(id)arg3;
- (id)init;

@end

