//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface RSFetchedResultsSectionChange : NSObject
{
    long long __fromIndex;
    long long __toIndex;
    id __record;
}

@property(nonatomic) long long toIndex; // @synthesize toIndex=__toIndex;
@property(nonatomic) long long fromIndex; // @synthesize fromIndex=__fromIndex;
@property(retain, nonatomic) id record; // @synthesize record=__record;
- (void).cxx_destruct;
- (id)init;

@end

