//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSXMLParserDelegate-Protocol.h"

@class NSDictionary, NSString, NSXMLParser, RSFeedParserResult;

@interface RSFeedParser : NSObject <NSXMLParserDelegate>
{
    NSXMLParser *__parser;
    NSDictionary *__json;
    RSFeedParserResult *__result;
    long long __depth;
    _Bool __item;
    id __target;
    SEL __action;
    _Bool __parseItems;
}

+ (id)parserWithData:(id)arg1;
- (void).cxx_destruct;
- (void)parser:(id)arg1 foundCharacters:(id)arg2;
- (void)parser:(id)arg1 foundCDATA:(id)arg2;
- (void)parser:(id)arg1 didEndElement:(id)arg2 namespaceURI:(id)arg3 qualifiedName:(id)arg4;
- (void)parser:(id)arg1 didStartElement:(id)arg2 namespaceURI:(id)arg3 qualifiedName:(id)arg4 attributes:(id)arg5;
- (void)parserDidEndDocument:(id)arg1;
- (void)parserDidStartDocument:(id)arg1;
- (id)parse:(_Bool)arg1;
- (id)parse;
- (id)initWithData:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

