//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSArray, NSIndexPath, RSFetchedResultsChanges, RSFetchedResultsController, RSSection, RSSectionList;

@protocol RSFetchedResultsControllerDelegate <NSObject>

@optional
- (void)controller:(RSFetchedResultsController *)arg1 didChangeContent:(RSFetchedResultsChanges *)arg2;
- (void)controllerDidChangeContent:(RSFetchedResultsController *)arg1 inserts:(NSArray *)arg2 updates:(NSArray *)arg3 deletes:(NSArray *)arg4;
- (void)controllerDidChangeContent:(RSFetchedResultsController *)arg1;
- (void)controllerWillChangeContent:(RSFetchedResultsController *)arg1;
- (void)controller:(RSFetchedResultsController *)arg1 inBackground:(_Bool)arg2 willSetSectionList:(RSSectionList *)arg3;
- (void)controller:(RSFetchedResultsController *)arg1 didChangeSection:(RSSection *)arg2 atIndex:(unsigned long long)arg3 forChangeType:(unsigned long long)arg4;
- (void)controller:(RSFetchedResultsController *)arg1 didChangeObject:(id)arg2 atIndexPath:(NSIndexPath *)arg3 forChangeType:(unsigned long long)arg4 newIndexPath:(NSIndexPath *)arg5;
@end

