//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface RSFeedLinkChecker : NSObject
{
}

+ (id)checkWebView:(id)arg1;
+ (id)checkUrl:(id)arg1 response:(id *)arg2;

@end

