//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSMutableArray, NSString, RSFeedParserItem;

@interface RSFeedParserResult : NSObject
{
    NSMutableArray *__items;
    NSString *__title;
    NSString *__link;
    RSFeedParserItem *__currentItem;
    _Bool __valid;
}

@property(readonly, nonatomic) RSFeedParserItem *currentItem; // @synthesize currentItem=__currentItem;
@property(readonly, nonatomic) NSArray *items; // @synthesize items=__items;
@property(copy, nonatomic) NSString *link; // @synthesize link=__link;
@property(copy, nonatomic) NSString *title; // @synthesize title=__title;
@property(readonly, nonatomic) _Bool valid; // @synthesize valid=__valid;
- (void).cxx_destruct;
- (id)addItem;
- (void)setValid:(_Bool)arg1;
- (id)init;

@end

