//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSMutableArray, NSString, RSForm, UIImage;

@interface RSFormSection : NSObject
{
    NSMutableArray *__cells;
    NSString *__name;
    NSString *__title;
    UIImage *__icon;
    RSForm *__form;
    CDUnknownBlockType __validationBlock;
}

+ (id)sectionWithName:(id)arg1 title:(id)arg2 icon:(id)arg3;
@property(copy, nonatomic) CDUnknownBlockType validationBlock; // @synthesize validationBlock=__validationBlock;
@property(retain, nonatomic) UIImage *icon; // @synthesize icon=__icon;
@property(copy, nonatomic) NSString *title; // @synthesize title=__title;
@property(copy, nonatomic) NSString *name; // @synthesize name=__name;
@property(copy, nonatomic) NSArray *cells; // @synthesize cells=__cells;
@property(nonatomic) __weak RSForm *form; // @synthesize form=__form;
- (void).cxx_destruct;
- (void)clear;
- (_Bool)validate;
- (id)addCellWithType:(int)arg1 name:(id)arg2 title:(id)arg3 placeholder:(id)arg4;
- (id)addCellWithType:(int)arg1 name:(id)arg2 title:(id)arg3;
- (id)addCellWithType:(int)arg1 name:(id)arg2;
- (id)initWithName:(id)arg1 title:(id)arg2 icon:(id)arg3;

@end

