//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class RSFormTextOption;

@protocol RSFormTextOptionDelegate <NSObject>
- (void)formTextOption:(RSFormTextOption *)arg1 didChangeSelection:(_Bool)arg2;
@end

