//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "RSFormCell.h"

@class NSString;
@protocol RSFormTextOptionDelegate;

@interface RSFormTextOption : RSFormCell
{
    _Bool __selected;
    NSString *__description;
    _Bool __isActionButton;
    SEL __actionSelector;
    id __actionParameter;
    id <RSFormTextOptionDelegate> __delegate;
    id actionParameter;
}

+ (id)optionWithTitle:(id)arg1 value:(id)arg2;
@property(nonatomic) __weak id <RSFormTextOptionDelegate> delegate; // @synthesize delegate=__delegate;
@property(copy, nonatomic) NSString *description; // @synthesize description=__description;
@property(retain, nonatomic) id actionParameter; // @synthesize actionParameter;
@property(nonatomic) SEL actionSelector; // @synthesize actionSelector=__actionSelector;
@property(nonatomic) _Bool isActionButton; // @synthesize isActionButton=__isActionButton;
@property(nonatomic) _Bool selected; // @synthesize selected=__selected;
- (void).cxx_destruct;
- (void)setValue:(id)arg1;
- (void)setInitialValue:(id)arg1;
- (id)initWithTitle:(id)arg1 value:(id)arg2;

@end

