//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class RSForm, RSFormCell, RSFormTextOptionsPicker;

@protocol RSFormDelegate <NSObject>

@optional
- (void)form:(RSForm *)arg1 didPickTextOption:(RSFormTextOptionsPicker *)arg2;
- (void)form:(RSForm *)arg1 cellDidChange:(RSFormCell *)arg2;
- (void)formTextDidChange:(RSForm *)arg1;
- (void)formDidCancel:(RSForm *)arg1;
- (void)formDidSubmit:(RSForm *)arg1;
@end

