//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, RSFormSection;

@interface RSFormCell : NSObject
{
    int __type;
    NSString *__name;
    NSString *__title;
    NSString *__placeholder;
    RSFormSection *__section;
    CDUnknownBlockType __validationBlock;
    id __value;
    id __initialValue;
    id __target;
    SEL __action;
}

+ (id)buttonCellWithTitle:(id)arg1 target:(id)arg2 action:(SEL)arg3;
+ (id)cellWithType:(int)arg1 name:(id)arg2 title:(id)arg3 placeholder:(id)arg4;
+ (id)cellWithType:(int)arg1 name:(id)arg2 title:(id)arg3;
+ (id)cellWithType:(int)arg1 name:(id)arg2;
@property(copy, nonatomic) CDUnknownBlockType validationBlock; // @synthesize validationBlock=__validationBlock;
@property(nonatomic) SEL action; // @synthesize action=__action;
@property(nonatomic) __weak id target; // @synthesize target=__target;
@property(copy, nonatomic) NSString *placeholder; // @synthesize placeholder=__placeholder;
@property(copy, nonatomic) NSString *title; // @synthesize title=__title;
@property(copy, nonatomic) NSString *name; // @synthesize name=__name;
@property(nonatomic) int type; // @synthesize type=__type;
@property(copy, nonatomic) id initialValue; // @synthesize initialValue=__initialValue;
@property(copy, nonatomic) id value; // @synthesize value=__value;
@property(nonatomic) __weak RSFormSection *section; // @synthesize section=__section;
- (void).cxx_destruct;
- (void)postDidChange;
- (_Bool)validate;
- (id)initButtonWithTitle:(id)arg1 target:(id)arg2 action:(SEL)arg3;
- (id)initWithType:(int)arg1 name:(id)arg2 title:(id)arg3 placeholder:(id)arg4;
- (id)initWithType:(int)arg1 name:(id)arg2 title:(id)arg3;
- (id)initWithType:(int)arg1 name:(id)arg2;

@end

