//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "RSFormSection.h"

#import "RSFormTextOptionDelegate-Protocol.h"

@class NSArray, NSString;
@protocol RSFormTextOptionPickerDelegate;

@interface RSFormTextOptionsPicker : RSFormSection <RSFormTextOptionDelegate>
{
    NSString *__placeholder;
    _Bool __allowsMutlipleSelection;
    _Bool __allowsEmptySelection;
    _Bool __showsCount;
    _Bool __optionsAreActions;
    long long __count;
    id <RSFormTextOptionPickerDelegate> __delegate;
}

+ (id)pickerWithName:(id)arg1 title:(id)arg2 placeholder:(id)arg3;
@property(nonatomic) _Bool optionsAreActions; // @synthesize optionsAreActions=__optionsAreActions;
@property(nonatomic) long long count; // @synthesize count=__count;
@property(nonatomic) _Bool showsCount; // @synthesize showsCount=__showsCount;
@property(nonatomic) _Bool allowsEmptySelection; // @synthesize allowsEmptySelection=__allowsEmptySelection;
@property(nonatomic) _Bool allowsMultipleSelection; // @synthesize allowsMultipleSelection=__allowsMutlipleSelection;
@property(copy, nonatomic) NSString *placeholder; // @synthesize placeholder=__placeholder;
@property(nonatomic) __weak id <RSFormTextOptionPickerDelegate> delegate; // @synthesize delegate=__delegate;
- (void).cxx_destruct;
- (void)postDidChange;
- (void)clear;
- (_Bool)validate;
- (id)addOptionWithTitle:(id)arg1 value:(id)arg2;
- (void)formTextOption:(id)arg1 didChangeSelection:(_Bool)arg2;
@property(readonly, nonatomic) NSArray *selectedOptions;
- (void)setValues:(id)arg1;
- (id)values;
- (void)setValue:(id)arg1;
- (id)value;
- (id)initWithName:(id)arg1 title:(id)arg2 placeholder:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

