//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSMutableArray, NSString;
@protocol RSFormDelegate;

@interface RSForm : NSObject
{
    NSMutableArray *__sections;
    id <RSFormDelegate> __delegate;
    id __userInfo;
    int __type;
    NSString *__quote;
    _Bool __multiLineQuote;
    NSString *__text;
    CDUnknownBlockType __validationBlock;
}

@property(copy, nonatomic) CDUnknownBlockType validationBlock; // @synthesize validationBlock=__validationBlock;
@property(copy, nonatomic) NSString *text; // @synthesize text=__text;
@property(nonatomic) _Bool multiLineQuote; // @synthesize multiLineQuote=__multiLineQuote;
@property(copy, nonatomic) NSString *quote; // @synthesize quote=__quote;
@property(readonly, nonatomic) int type; // @synthesize type=__type;
@property(retain, nonatomic) id userInfo; // @synthesize userInfo=__userInfo;
@property(nonatomic) __weak id <RSFormDelegate> delegate; // @synthesize delegate=__delegate;
@property(copy, nonatomic) NSArray *sections; // @synthesize sections=__sections;
- (void).cxx_destruct;
- (void)clear;
- (id)sectionForKey:(id)arg1;
- (id)cellForKey:(id)arg1;
- (id)formValueForKey:(id)arg1;
- (void)didPickTextOption:(id)arg1;
- (void)didChangeCell:(id)arg1;
- (void)postDidChange;
- (void)cancel;
- (void)done;
- (_Bool)validate;
- (id)addTextOptionsPicker:(id)arg1 title:(id)arg2 placeholder:(id)arg3;
- (id)addSectionWithName:(id)arg1 title:(id)arg2 icon:(id)arg3;
- (id)initWithType:(int)arg1;
- (id)init;

@end

