//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class RSQueue;

@interface RSIconFetcher : NSObject
{
    RSQueue *__queue;
}

+ (id)sharedFetcher;
- (void).cxx_destruct;
- (void)fetch:(id)arg1;
- (double)scale;
- (id)init;

@end

