//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSMutableURLRequest.h>

@class NSMutableDictionary;

@interface RSMutableURLRequest : NSMutableURLRequest
{
    NSMutableDictionary *__parameters;
    _Bool __bodyAsJSON;
}

@property(nonatomic) _Bool bodyAsJSON; // @synthesize bodyAsJSON=__bodyAsJSON;
- (void).cxx_destruct;
- (void)prepare;
- (id)parameters;
- (id)parameterForKey:(id)arg1;
- (void)setParametersFromDictionary:(id)arg1;
- (void)addParametersFromDictionary:(id)arg1;
- (void)removeParameterForKey:(id)arg1;
- (void)setParameter:(id)arg1 forKey:(id)arg2;
- (void)addParameter:(id)arg1 forKey:(id)arg2;

@end

