//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface RSPathUtil : NSObject
{
}

+ (id)deletedOfflineCacheDirectory;
+ (id)offlineCacheDirectory;
+ (id)touchIconDirectory;
+ (id)favIconDirectory;
+ (id)iconDirectory;
+ (id)exportDirectory;
+ (void)createUserIconDirectoryIfNeeded;
+ (id)userIconDirectory;
+ (id)__dataStoreDirectory;
+ (id)dataStoreDirectory;
+ (id)backupDirectory;
+ (void)setDoNotBackUpForDataStoreDirectory;
+ (void)createDataStoreDirectoryIfNeeded;

@end

