//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface RSPropertyInfo : NSObject
{
    Class __entity;
    _Bool __copies;
    _Bool __readonly;
    NSString *__name;
    struct objc_ivar *__ivar;
    int __type;
    NSString *__sqlType;
    Class __recordTypeEntity;
    Class __recordListTypeEntity;
}

+ (id)infoForProperty:(id)arg1 ofEntity:(Class)arg2;
+ (id)dynamicPropertiesOfEntity:(Class)arg1;
@property(readonly, nonatomic) Class recordListTypeEntity; // @synthesize recordListTypeEntity=__recordListTypeEntity;
@property(readonly, nonatomic) Class recordTypeEntity; // @synthesize recordTypeEntity=__recordTypeEntity;
@property(readonly, nonatomic) NSString *sqlType; // @synthesize sqlType=__sqlType;
@property(readonly, nonatomic) int type; // @synthesize type=__type;
@property(readonly, nonatomic) struct objc_ivar *ivar; // @synthesize ivar=__ivar;
@property(readonly, nonatomic) _Bool readonly; // @synthesize readonly=__readonly;
@property(readonly, nonatomic) _Bool copies; // @synthesize copies=__copies;
@property(readonly, nonatomic) NSString *name; // @synthesize name=__name;
@property(readonly, nonatomic) Class entity; // @synthesize entity=__entity;
- (void).cxx_destruct;
- (id)description;
- (id)initWithProperty:(id)arg1 ofEntity:(Class)arg2;

@end

