//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSPredicate, NSString;

@interface RSPredicate : NSObject
{
    NSString *__sql;
    NSPredicate *__predicate;
    NSPredicate *__sqlPredicate;
}

+ (id)predicateWithString:(id)arg1;
+ (id)predicateWithSQL:(id)arg1 SQLPredicate:(id)arg2 NSPredicate:(id)arg3;
+ (id)predicateWithSQL:(id)arg1 NSPredicate:(id)arg2;
+ (id)predicateWithPredicate:(id)arg1;
@property(readonly, nonatomic) NSPredicate *NSPredicate; // @synthesize NSPredicate=__predicate;
@property(readonly, nonatomic) NSPredicate *SQLPredicate; // @synthesize SQLPredicate=__sqlPredicate;
@property(readonly, nonatomic) NSString *SQL; // @synthesize SQL=__sql;
- (void).cxx_destruct;
- (id)description;
- (id)initWithSQL:(id)arg1 SQLPredicate:(id)arg2 NSPredicate:(id)arg3;
- (id)initWithSQL:(id)arg1 NSPredicate:(id)arg2;
- (id)initWithString:(id)arg1;
- (id)initWithPredicate:(id)arg1;

@end

