//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSMutableArray, NSString, RSSettings;

@interface RSSettingsSection : NSObject
{
    NSMutableArray *__items;
    NSString *__title;
    NSString *__footer;
    RSSettings *__settings;
}

+ (id)sectionWithSettings:(id)arg1 fromDictionary:(id)arg2;
@property(readonly, nonatomic) NSArray *items; // @synthesize items=__items;
@property(readonly, nonatomic) NSString *footer; // @synthesize footer=__footer;
@property(readonly, nonatomic) NSString *title; // @synthesize title=__title;
@property(readonly, nonatomic) __weak RSSettings *settings; // @synthesize settings=__settings;
- (void).cxx_destruct;
- (id)itemAtIndex:(long long)arg1;
@property(readonly, nonatomic) long long numberOfItems;
- (id)description;
- (id)initWithSettings:(id)arg1 fromDictionary:(id)arg2;

@end

