//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface RSSelector : NSObject
{
    SEL __selector;
}

+ (id)wrap:(SEL)arg1;
@property(nonatomic) SEL selector; // @synthesize selector=__selector;
- (id)performOnTarget:(id)arg1 withObject:(id)arg2;

@end

