//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSData, NSDictionary, NSError, NSString, NSURLRequest, NSURLResponse;
@protocol RSServiceResponseDelegate;

@interface RSServiceResponse : NSObject
{
    NSURLRequest *__request;
    NSURLResponse *__response;
    NSData *__data;
    NSError *__error;
    long long __statusCode;
    id <RSServiceResponseDelegate> __delegate;
}

+ (id)responseWithRequest:(id)arg1 response:(id)arg2 data:(id)arg3 error:(id)arg4 delegate:(id)arg5;
+ (id)fail;
+ (id)success;
@property(nonatomic) __weak id <RSServiceResponseDelegate> delegate; // @synthesize delegate=__delegate;
@property(readonly, nonatomic) NSError *error; // @synthesize error=__error;
@property(readonly, nonatomic) NSData *data; // @synthesize data=__data;
@property(readonly, nonatomic) NSURLResponse *response; // @synthesize response=__response;
@property(readonly, nonatomic) NSURLRequest *request; // @synthesize request=__request;
- (void).cxx_destruct;
@property(readonly, nonatomic) NSString *etag;
@property(readonly, nonatomic) _Bool notConnectedToInternetError;
@property(readonly, nonatomic) NSDictionary *JSONDictionary;
@property(readonly, nonatomic) NSArray *JSONArray;
@property(readonly, nonatomic) _Bool didSucceed;
@property(readonly, nonatomic) long long statusCode;
- (id)stringUsingEncoding:(unsigned long long)arg1;
- (id)string;
- (void)overwriteStatusCode:(int)arg1;
- (id)initWithRequest:(id)arg1 response:(id)arg2 data:(id)arg3 error:(id)arg4 delegate:(id)arg5;

@end

