//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class RSServiceResponse;

@protocol RSServiceResponseDelegate <NSObject>

@optional
- (_Bool)serviceResponseShouldValidateResponse:(RSServiceResponse *)arg1;
@end

