//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCopying-Protocol.h"

@class NSArray, NSMutableArray, NSMutableDictionary, NSMutableSet, NSString, RSSection;

@interface RSSectionList : NSObject <NSCopying>
{
    NSMutableSet *__objects;
    NSMutableArray *__sectionsArr;
    NSMutableDictionary *__sectionsDict;
    NSString *__sectionNameKeyPath;
    NSArray *__sortDescriptors;
    NSMutableArray *__flatList;
    _Bool __sortSections;
    RSSection *__defaultSection;
    NSMutableArray *__insertedSections;
    NSMutableArray *__deletedSections;
    id strongSelf;
}

@property(readonly, nonatomic) NSArray *deletedSections; // @synthesize deletedSections=__deletedSections;
@property(readonly, nonatomic) NSArray *insertedSections; // @synthesize insertedSections=__insertedSections;
@property(retain, nonatomic) NSArray *sortDescriptors; // @synthesize sortDescriptors=__sortDescriptors;
@property(readonly, nonatomic) NSString *sectionKeyNamePath; // @synthesize sectionKeyNamePath=__sectionNameKeyPath;
@property(readonly, nonatomic) NSMutableSet *objects; // @synthesize objects=__objects;
- (void).cxx_destruct;
- (id)flattenedObjectAtIndex:(unsigned long long)arg1;
@property(readonly, nonatomic) unsigned long long flattenedListNumberOfObjects;
- (void)deleteObject:(id)arg1;
- (void)updateObject:(id)arg1;
- (void)insertObject:(id)arg1;
- (void)appendObject:(id)arg1;
- (id)indexPathForObject:(id)arg1;
- (unsigned long long)indexOfSectionWithName:(id)arg1;
- (unsigned long long)indexOfSection:(id)arg1;
- (id)objectAtIndexPath:(id)arg1;
- (id)sectionAtIndex:(unsigned long long)arg1;
- (void)__deleteSectionIfEmpty:(id)arg1;
- (id)sectionForObject:(id)arg1 create:(_Bool)arg2;
- (id)sectionForObject:(id)arg1;
- (id)sectionNameForObject:(id)arg1;
@property(readonly, nonatomic) unsigned long long numberOfSections;
@property(readonly, nonatomic) NSArray *orderedObjects;
@property(readonly, nonatomic) NSArray *flatList;
- (void)endUpdates;
- (void)beginUpdates;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithSectionNameKeyPath:(id)arg1;

@end

