//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableDictionary, NSString, RSSettingsSection;

@interface RSSettingsItem : NSObject
{
    int __type;
    NSString *__label;
    NSString *__key;
    NSString *__placeholder;
    id __value;
    id __defaultValue;
    NSMutableDictionary *__set;
    NSString *__setFooter;
    RSSettingsSection *__section;
    _Bool __readonly;
    _Bool __hidden;
    NSString *__twitterHandle;
    NSString *__notificationName;
}

+ (id)itemWithType:(int)arg1;
+ (id)itemWithSection:(id)arg1 fromDictionary:(id)arg2;
@property(copy, nonatomic) NSString *notificationName; // @synthesize notificationName=__notificationName;
@property(copy, nonatomic) NSString *twitterHandle; // @synthesize twitterHandle=__twitterHandle;
@property(nonatomic) _Bool hidden; // @synthesize hidden=__hidden;
@property(nonatomic) _Bool readonly; // @synthesize readonly=__readonly;
@property(copy, nonatomic) NSString *setFooter; // @synthesize setFooter=__setFooter;
@property(copy, nonatomic) NSMutableDictionary *set; // @synthesize set=__set;
@property(copy, nonatomic) id defaultValue; // @synthesize defaultValue=__defaultValue;
@property(copy, nonatomic) NSString *placeholder; // @synthesize placeholder=__placeholder;
@property(copy, nonatomic) NSString *key; // @synthesize key=__key;
@property(copy, nonatomic) NSString *label; // @synthesize label=__label;
@property(nonatomic) int type; // @synthesize type=__type;
@property(readonly, nonatomic) __weak RSSettingsSection *section; // @synthesize section=__section;
- (void).cxx_destruct;
@property(copy, nonatomic) NSString *stringValue;
@property(nonatomic) long long integerValue;
@property(nonatomic) _Bool boolValue;
- (void)setDefaultValue;
@property(copy, nonatomic) id value; // @synthesize value=__value;
@property(readonly, nonatomic) NSString *defaultsKeyPath;
- (id)description;

@end

