//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSURLConnectionDataDelegate-Protocol.h"
#import "NSURLConnectionDelegate-Protocol.h"

@class NSData, NSError, NSMutableData, NSString, NSURLResponse;
@protocol OS_dispatch_semaphore;

@interface RSURLConnectionSynchronousDelegate : NSObject <NSURLConnectionDelegate, NSURLConnectionDataDelegate>
{
    NSMutableData *__data;
    NSURLResponse *__response;
    NSObject<OS_dispatch_semaphore> *__semaphore;
    NSError *__error;
}

@property(readonly, nonatomic) NSError *error; // @synthesize error=__error;
@property(readonly, nonatomic) NSURLResponse *response; // @synthesize response=__response;
@property(readonly, nonatomic) NSData *data; // @synthesize data=__data;
- (void).cxx_destruct;
- (void)wait;
- (void)connection:(id)arg1 didFailWithError:(id)arg2;
- (void)connectionDidFinishLoading:(id)arg1;
- (void)connection:(id)arg1 didReceiveResponse:(id)arg2;
- (void)connection:(id)arg1 didReceiveData:(id)arg2;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

