//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "CoreViewController.h"

#import "SFSafariViewControllerDelegate-Protocol.h"

@class ModalView, NSString, SFSafariViewController;

@interface SafariAuthViewController : CoreViewController <SFSafariViewControllerDelegate>
{
    SFSafariViewController *browserController;
    _Bool __handled;
    ModalView *__modal;
    _Bool __isLoading;
}

- (void).cxx_destruct;
- (void)safariViewControllerDidFinish:(id)arg1;
- (void)pop:(id)arg1;
- (void)endModal;
- (void)startModal;
- (void)loadRequest:(id)arg1;
- (void)viewDidLayoutSubviews;
- (_Bool)shouldAutorotateToInterfaceOrientation:(long long)arg1;
- (void)dealloc;
- (id)loadContentView;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

