//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class CRPainterShadowItem;

@interface ScrollHeaderSeparatorView : UIView
{
    CRPainterShadowItem *_shadow;
}

@property(retain, nonatomic) CRPainterShadowItem *shadow; // @synthesize shadow=_shadow;
- (void).cxx_destruct;
- (void)drawRect:(struct CGRect)arg1;
- (id)initWithHeaderView:(id)arg1;

@end

