//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class CRPainterHeaderGroup, CoreAnimator, NSString, ScrollHeaderBarView, ScrollHeaderImageView, ScrollHeaderSeparatorView, ScrollHeaderTitleView, UIButton, UIImage, UILongPressGestureRecognizer, UIScrollView;
@protocol ScrollHeaderViewDelegate;

@interface ScrollHeaderView : UIView
{
    UILongPressGestureRecognizer *__leftLongPress;
    UILongPressGestureRecognizer *__rightLongPress;
    struct {
        double scrollOffset;
        double panOffset;
    } __pull;
    CoreAnimator *__panAnimator;
    UIScrollView *__pullScrollView;
    _Bool __trigger;
    _Bool __triggered;
    _Bool _pulling;
    _Bool _leftButtonSupportsLongPress;
    _Bool _rightButtonSupportsLongPress;
    _Bool _borderedImage;
    _Bool _longPress;
    int _panning;
    int _imageStyle;
    id <ScrollHeaderViewDelegate> _delegate;
    CRPainterHeaderGroup *_painter;
    ScrollHeaderSeparatorView *_separatorView;
    ScrollHeaderBarView *_barView;
    UIView *_topFillView;
    double _height;
    UIButton *_leftButton;
    UIButton *_rightButton;
    NSString *_imageName;
    UIImage *_image;
    ScrollHeaderImageView *_imageView;
    NSString *_title;
    NSString *_text;
    NSString *_pullText;
    ScrollHeaderTitleView *_titleView;
    NSString *_leftButtonImageName;
    NSString *_rightButtonImageName;
    id _target;
    SEL _action;
    double _offsetY;
    double _fullHeight;
}

+ (double)barHeight;
+ (double)fullHeight;
@property(readonly, nonatomic) double fullHeight; // @synthesize fullHeight=_fullHeight;
@property(readonly, nonatomic) double offsetY; // @synthesize offsetY=_offsetY;
@property(readonly, nonatomic) SEL action; // @synthesize action=_action;
@property(readonly, nonatomic) __weak id target; // @synthesize target=_target;
@property(readonly, nonatomic) NSString *rightButtonImageName; // @synthesize rightButtonImageName=_rightButtonImageName;
@property(readonly, nonatomic) NSString *leftButtonImageName; // @synthesize leftButtonImageName=_leftButtonImageName;
@property(readonly, nonatomic, getter=isLongPress) _Bool longPress; // @synthesize longPress=_longPress;
@property(retain, nonatomic) ScrollHeaderTitleView *titleView; // @synthesize titleView=_titleView;
@property(copy, nonatomic) NSString *pullText; // @synthesize pullText=_pullText;
@property(copy, nonatomic) NSString *text; // @synthesize text=_text;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(retain, nonatomic) ScrollHeaderImageView *imageView; // @synthesize imageView=_imageView;
@property(nonatomic) _Bool borderedImage; // @synthesize borderedImage=_borderedImage;
@property(retain, nonatomic) UIImage *image; // @synthesize image=_image;
@property(retain, nonatomic) NSString *imageName; // @synthesize imageName=_imageName;
@property(nonatomic) int imageStyle; // @synthesize imageStyle=_imageStyle;
@property(nonatomic) _Bool rightButtonSupportsLongPress; // @synthesize rightButtonSupportsLongPress=_rightButtonSupportsLongPress;
@property(nonatomic) _Bool leftButtonSupportsLongPress; // @synthesize leftButtonSupportsLongPress=_leftButtonSupportsLongPress;
@property(readonly, nonatomic) UIButton *rightButton; // @synthesize rightButton=_rightButton;
@property(readonly, nonatomic) UIButton *leftButton; // @synthesize leftButton=_leftButton;
@property(readonly, nonatomic) double height; // @synthesize height=_height;
@property(readonly, nonatomic) UIView *topFillView; // @synthesize topFillView=_topFillView;
@property(readonly, nonatomic) ScrollHeaderBarView *barView; // @synthesize barView=_barView;
@property(readonly, nonatomic) ScrollHeaderSeparatorView *separatorView; // @synthesize separatorView=_separatorView;
@property(readonly, nonatomic, getter=isPanning) int panning; // @synthesize panning=_panning;
@property(readonly, nonatomic, getter=isPulling) _Bool pulling; // @synthesize pulling=_pulling;
@property(readonly, nonatomic) CRPainterHeaderGroup *painter; // @synthesize painter=_painter;
@property(nonatomic) __weak id <ScrollHeaderViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)__setContainerOffsetY:(double)arg1;
- (void)setContainerOffsetY:(double)arg1;
- (void)setRightButtonImageName:(id)arg1 target:(id)arg2 selector:(SEL)arg3;
- (void)setLeftButtonImageName:(id)arg1 target:(id)arg2 selector:(SEL)arg3;
- (void)setRightButtonImageName:(id)arg1;
- (void)setLeftButtonImageName:(id)arg1;
- (void)setRightButtonImage;
- (void)setLeftButtonImage;
- (void)updateButton:(id)arg1 withImageName:(id)arg2;
- (void)longPressRight:(id)arg1;
- (void)longPressLeft:(id)arg1;
- (void)tap:(id)arg1;
- (void)setHeaderTapTarget:(id)arg1 action:(SEL)arg2;
- (void)drawImageViewInRect:(struct CGRect)arg1;
- (void)drawPullTextInRect:(struct CGRect)arg1;
- (void)drawTextInRect:(struct CGRect)arg1;
- (void)drawTitleInRect:(struct CGRect)arg1;
- (void)drawBarViewInRect:(struct CGRect)arg1;
- (void)setNeedsDisplay;
- (void)painterDidChange;
- (void)__panDidComplete;
- (void)pan:(id)arg1;
- (void)setFrame:(struct CGRect)arg1;
- (void)layoutSubviews;
- (id)initWithWidth:(double)arg1 fullHeight:(double)arg2;
- (id)initWithWidth:(double)arg1 navigationOnly:(_Bool)arg2;

@end

