//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@interface ScrollHeaderTitleView : UIView
{
    _Bool _hasText;
    _Bool _hasPullText;
    UIView *_titleLabel;
    UIView *_textLabel;
    UIView *_pullTextLabel;
    double _offsetY;
    double _titleFontHeight;
    double _textFontHeight;
}

@property(nonatomic) _Bool hasPullText; // @synthesize hasPullText=_hasPullText;
@property(nonatomic) _Bool hasText; // @synthesize hasText=_hasText;
@property(nonatomic) double textFontHeight; // @synthesize textFontHeight=_textFontHeight;
@property(nonatomic) double titleFontHeight; // @synthesize titleFontHeight=_titleFontHeight;
@property(nonatomic) double offsetY; // @synthesize offsetY=_offsetY;
@property(retain, nonatomic) UIView *pullTextLabel; // @synthesize pullTextLabel=_pullTextLabel;
@property(retain, nonatomic) UIView *textLabel; // @synthesize textLabel=_textLabel;
@property(retain, nonatomic) UIView *titleLabel; // @synthesize titleLabel=_titleLabel;
- (void).cxx_destruct;
- (void)layout;
- (void)setNeedsDisplay;
- (id)initWithFrame:(struct CGRect)arg1;

@end

