//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSString, ScrollHeaderView, UIScrollView;

@protocol ScrollHeaderViewDelegate <NSObject>
- (void)scrollHeaderViewDidTriggerPull:(ScrollHeaderView *)arg1;
- (UIScrollView *)scrollHeaderViewScrollView:(ScrollHeaderView *)arg1;
- (NSString *)scrollHeaderViewPullTitle:(ScrollHeaderView *)arg1;
- (_Bool)scrollHeaderViewCanPull:(ScrollHeaderView *)arg1;
@end

