//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SettingsViewCell.h"

#import "UITextFieldDelegate-Protocol.h"

@class NSString, UITextField;

@interface SettingsViewCellText : SettingsViewCell <UITextFieldDelegate>
{
    UITextField *__input;
    double __inputTextHeight;
    double __labelWidth;
}

@property(readonly, nonatomic) UITextField *input; // @synthesize input=__input;
- (void).cxx_destruct;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (_Bool)textFieldShouldClear:(id)arg1;
- (_Bool)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (double)labelWidth;
- (void)setFrame:(struct CGRect)arg1;
- (void)layoutSubviews;
- (id)initWithItem:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

