//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SettingsViewCell.h"

@class UISwitch;

@interface SettingsViewCellBoolean : SettingsViewCell
{
    UISwitch *__input;
}

@property(readonly, nonatomic) UISwitch *input; // @synthesize input=__input;
- (void).cxx_destruct;
- (void)valueChanged:(id)arg1;
- (id)initWithItem:(id)arg1;

@end

