//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "TableViewCell.h"

@class RSSettingsItem;

@interface SettingsViewCell : TableViewCell
{
    RSSettingsItem *__item;
}

+ (id)cellWithItem:(id)arg1;
@property(retain, nonatomic) RSSettingsItem *item; // @synthesize item=__item;
- (void).cxx_destruct;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)setHighlighted:(_Bool)arg1 animated:(_Bool)arg2;
- (void)drawContentView:(id)arg1 rect:(struct CGRect)arg2;
- (double)labelWidth;
@property(readonly, nonatomic) id input;
- (id)initWithItem:(id)arg1;

@end

