//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "TableViewController.h"

@class NSArray, NSMutableArray, NSString, RSSettings;

@interface SettingsViewController : TableViewController
{
    RSSettings *__settings;
    NSMutableArray *__sections;
    NSMutableArray *__titles;
    CDUnknownBlockType __onDone;
    CDUnknownBlockType __onCancel;
    NSString *_headerImageName;
}

@property(copy, nonatomic) NSString *headerImageName; // @synthesize headerImageName=_headerImageName;
@property(copy, nonatomic) CDUnknownBlockType onCancel; // @synthesize onCancel=__onCancel;
@property(copy, nonatomic) CDUnknownBlockType onDone; // @synthesize onDone=__onDone;
@property(retain, nonatomic) RSSettings *settings; // @synthesize settings=__settings;
- (void).cxx_destruct;
- (void)openTwitterHandle:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (id)tableView:(id)arg1 titleForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (void)addSectionWithItems:(id)arg1 title:(id)arg2;
- (void)addSectionWithItems:(id)arg1;
@property(readonly, nonatomic) NSArray *sections;
- (void)dealloc;
- (void)cancel:(id)arg1;
- (void)done:(id)arg1;
- (void)pop:(id)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (_Bool)hasNavigationHeaderViewOnly;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

