//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "TableViewCell.h"

@interface SettingsSelectViewCell : TableViewCell
{
}

@property(nonatomic) _Bool on;
- (id)labelColor;
- (void)drawContentView:(id)arg1 rect:(struct CGRect)arg2;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

