//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "TableViewCell.h"

@class NSString;

@interface SettingsViewCellFooter : TableViewCell
{
    NSString *__text;
}

+ (id)footerWithText:(id)arg1;
- (void).cxx_destruct;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)setHighlighted:(_Bool)arg1 animated:(_Bool)arg2;
- (void)drawContentView:(id)arg1 rect:(struct CGRect)arg2;
@property(readonly, nonatomic) double height;
- (id)initWithText:(id)arg1;

@end

