//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SettingsViewCell.h"

@interface SettingsViewCellSelect : SettingsViewCell
{
}

- (void)drawContentView:(id)arg1 rect:(struct CGRect)arg2;
- (void)refresh;
- (id)initWithItem:(id)arg1;

@end

