//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "CoreCollectionViewCell.h"

@class RKService;

@interface SharePanelCell : CoreCollectionViewCell
{
}

- (void)didHighlightOrSelect:(_Bool)arg1;
- (void)drawContentViewRect:(struct CGRect)arg1;
@property(readonly, nonatomic) RKService *service;
- (id)initWithReuseIdentifier:(id)arg1;

@end

