//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSArray, NSString;

@interface SharePanel : UIView
{
    NSArray *_buttons;
    NSString *_label;
    double _panelSpacing;
    double _width;
    long long _numberOfRows;
    long long _numberOfColumns;
}

@property(readonly, nonatomic) long long numberOfColumns; // @synthesize numberOfColumns=_numberOfColumns;
@property(readonly, nonatomic) long long numberOfRows; // @synthesize numberOfRows=_numberOfRows;
@property(readonly, nonatomic) double width; // @synthesize width=_width;
@property(readonly, nonatomic) double panelSpacing; // @synthesize panelSpacing=_panelSpacing;
@property(copy, nonatomic) NSString *label; // @synthesize label=_label;
@property(readonly, nonatomic) NSArray *buttons; // @synthesize buttons=_buttons;
- (void).cxx_destruct;
- (void)__setupButtons;
- (id)initWithButtons:(id)arg1;

@end

