//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "CoreCollectionViewDelegate-Protocol.h"
#import "MFMailComposeViewControllerDelegate-Protocol.h"
#import "SharePostControllerDelegate-Protocol.h"

@class CoreAnimator, CoreCollectionView, NSString, RKShareObject, UITapGestureRecognizer, UIView;

@interface ShareController : UIViewController <MFMailComposeViewControllerDelegate, SharePostControllerDelegate, CoreCollectionViewDelegate>
{
    id __self;
    UITapGestureRecognizer *__tapClose;
    struct {
        struct CGPoint from;
        struct CGPoint to;
    } __appearPan;
    int __state;
    CoreAnimator *__appearDragAnimator;
    CoreAnimator *__appearAnimator;
    double _yPortrait;
    double _yLandscape;
    RKShareObject *_object;
    UIView *_backView;
    UIView *_shadowView;
    CoreCollectionView *_serviceListView;
}

+ (id)controller;
@property(readonly, nonatomic) CoreCollectionView *serviceListView; // @synthesize serviceListView=_serviceListView;
@property(readonly, nonatomic) UIView *shadowView; // @synthesize shadowView=_shadowView;
@property(readonly, nonatomic) UIView *backView; // @synthesize backView=_backView;
@property(readonly, nonatomic) RKShareObject *object; // @synthesize object=_object;
@property(nonatomic) int state; // @synthesize state=__state;
- (void).cxx_destruct;
- (void)sharePostControllerIsDone:(id)arg1;
- (void)collectionView:(id)arg1 didSelectItemWithRepresentedObject:(id)arg2 atIndexPath:(id)arg3;
- (double)collectionView:(id)arg1 heightForFooterInSection:(long long)arg2 representedObject:(id)arg3;
- (double)collectionView:(id)arg1 heightForHeaderInSection:(long long)arg2 representedObject:(id)arg3;
- (id)collectionView:(id)arg1 reuseIdentifierForFooterInSection:(long long)arg2 representedObject:(id)arg3;
- (id)collectionView:(id)arg1 reuseIdentifierForHeaderInSection:(long long)arg2 representedObject:(id)arg3;
- (id)collectionView:(id)arg1 reuseIdentifierForCellAtIndexPath:(id)arg2 representedObject:(id)arg3;
- (void)done;
- (void)__didClose;
- (void)close:(_Bool)arg1;
- (void)cancel;
- (void)tapClose:(id)arg1;
- (void)handleAppearPan:(id)arg1;
- (void)appear;
- (void)share:(id)arg1 inView:(id)arg2;
- (void)prepareInView:(id)arg1;
- (void)registerListCellClasses;
- (id)createDataSource;
- (void)__layoutForRotationTo:(long long)arg1;
- (void)willAnimateRotationToInterfaceOrientation:(long long)arg1 duration:(double)arg2;
- (void)willRotateToInterfaceOrientation:(long long)arg1 duration:(double)arg2;
- (double)listWidth;
@property(readonly, nonatomic) struct CGRect bounds;
- (void)viewDidLoad;
- (void)dealloc;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

