//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SharePanelCell.h"

@interface SharePanelFooterCell : SharePanelCell
{
}

- (void)didHighlightOrSelect:(_Bool)arg1;
- (void)drawContentViewRect:(struct CGRect)arg1;
- (id)initWithReuseIdentifier:(id)arg1;

@end

