//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "CRState.h"

@class CRStream, RKItem, RKUser, RootViewController;

@interface State : CRState
{
    RootViewController *__root;
    _Bool _ready;
    RKUser *_user;
    CRStream *_folder;
    CRStream *_stream;
    RKItem *_item;
}

@property(retain, nonatomic) RKItem *item; // @synthesize item=_item;
@property(retain, nonatomic) CRStream *stream; // @synthesize stream=_stream;
@property(retain, nonatomic) CRStream *folder; // @synthesize folder=_folder;
@property(retain, nonatomic) RKUser *user; // @synthesize user=_user;
@property(nonatomic, getter=isReady) _Bool ready; // @synthesize ready=_ready;
- (void).cxx_destruct;
- (void)save;
- (void)didSnapToViewController:(id)arg1;
- (void)didChangeSelectedObject:(id)arg1;
- (void)setRootViewController:(id)arg1;
- (void)dealloc;
- (id)init;

@end

