//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "CollectionViewController.h"

#import "CRFetchedSubscriptionsControllerDelegate-Protocol.h"
#import "UIGestureRecognizerDelegate-Protocol.h"

@class CRFetchedSubscriptionsController, NSString, RKUser, ToolbarItem;

@interface SubscriptionsViewController : CollectionViewController <CRFetchedSubscriptionsControllerDelegate, UIGestureRecognizerDelegate>
{
    RKUser *_user;
    ToolbarItem *__issuesButtonItem;
    _Bool __disableSelection;
    _Bool _showIcons;
    _Bool _usesFullScreenWidth;
    CRFetchedSubscriptionsController *_fetcher;
    NSString *_backButtonImage;
}

@property(copy, nonatomic) NSString *backButtonImage; // @synthesize backButtonImage=_backButtonImage;
@property(readonly, nonatomic) CRFetchedSubscriptionsController *fetcher; // @synthesize fetcher=_fetcher;
@property(readonly, nonatomic) _Bool usesFullScreenWidth; // @synthesize usesFullScreenWidth=_usesFullScreenWidth;
@property(retain, nonatomic) RKUser *user; // @synthesize user=_user;
- (void).cxx_destruct;
- (void)pop:(id)arg1;
- (void)popOrPushToSelf:(id)arg1;
- (void)slidingController:(id)arg1 willSnapToViewController:(id)arg2;
- (void)slidingController:(id)arg1 didSnapToViewController:(id)arg2;
- (void)longPressOnCell:(id)arg1 withRepresentedObject:(id)arg2;
- (void)addSubscriptionWithUrlString:(id)arg1;
- (void)addSubscription:(id)arg1;
- (id)folder;
- (void)didTapHeader:(id)arg1;
- (double)collectionView:(id)arg1 heightForHeaderInSection:(long long)arg2 representedObject:(id)arg3;
- (double)collectionView:(id)arg1 heightForItemAtIndexPath:(id)arg2 representedObject:(id)arg3;
- (void)collectionView:(id)arg1 didSelectItemWithRepresentedObject:(id)arg2 atIndexPath:(id)arg3;
- (void)__openAsArticles:(id)arg1;
- (void)__openAsFeeds:(id)arg1;
- (id)collectionView:(id)arg1 imageForSlider:(int)arg2 forCell:(id)arg3;
- (id)collectionView:(id)arg1 borderColorForSlider:(int)arg2 forCell:(id)arg3;
- (id)collectionView:(id)arg1 backgroundColorForSlider:(int)arg2 forCell:(id)arg3;
- (void)collectionView:(id)arg1 endSliderForCell:(id)arg2;
- (_Bool)collectionView:(id)arg1 commitSlider:(int)arg2 forCell:(id)arg3;
- (void)collectionView:(id)arg1 beginSliderForCell:(id)arg2;
- (_Bool)collectionView:(id)arg1 shouldHighlightItemWithRepresentedObject:(id)arg2 atIndexPath:(id)arg3;
- (id)collectionView:(id)arg1 reuseIdentifierForCellAtIndexPath:(id)arg2 representedObject:(id)arg3;
- (void)scrollHeaderViewDidTriggerPull:(id)arg1;
- (id)scrollHeaderViewPullTitle:(id)arg1;
- (_Bool)scrollHeaderViewCanPull:(id)arg1;
- (void)controller:(id)arg1 didChangeContent:(id)arg2;
- (void)controllerDidPerformInitialFetch:(id)arg1;
@property(readonly, nonatomic) _Bool canAddSubscriptions;
- (void)sync:(id)arg1;
- (void)didChangeSyncStatusText:(id)arg1;
- (void)validateHeader;
- (void)updateHeader;
- (double)widthForInterfaceOrientation:(long long)arg1;
- (void)didReceiveMemoryWarning;
- (void)painterDidChange:(id)arg1;
- (void)showOrHideFavicons:(id)arg1;
- (_Bool)gestureRecognizerShouldBegin:(id)arg1;
- (void)handleToolbarNavigationPan:(id)arg1;
- (void)collectionViewDidReload:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)viewDidLoad;
- (void)viewDidLayoutSubviews;
- (void)updatePadding;
- (_Bool)hasNavigationHeaderViewOnly;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)didDeleteUser:(id)arg1;
- (void)issuesManagerDidUpdate:(id)arg1;
- (void)restore;
@property(readonly, nonatomic) _Bool hasHotItem;
- (void)dealloc;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

