//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "CollectionViewCell.h"

@class CRStream;

@interface SubscriptionsViewTopCell : CollectionViewCell
{
}

- (void)didHighlightOrSelect:(_Bool)arg1;
- (void)drawContentViewRect:(struct CGRect)arg1;
@property(readonly, nonatomic) CRStream *item;
- (void)dealloc;
- (id)initWithReuseIdentifier:(id)arg1;

@end

