//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "TableViewController.h"

@class NSArray, RKStream, UIWindow;

@interface SubscriptionInfoViewController : TableViewController
{
    RKStream *__stream;
    UIWindow *__window;
    long long __infoSection;
    long long __folderSection;
    long long __unsubscribeSection;
    long long __renameSection;
    NSArray *__folders;
}

@property(retain, nonatomic) RKStream *stream; // @synthesize stream=__stream;
- (void).cxx_destruct;
- (long long)tableView:(id)arg1 editingStyleForRowAtIndexPath:(id)arg2;
- (_Bool)tableView:(id)arg1 canEditRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 commitEditingStyle:(long long)arg2 forRowAtIndexPath:(id)arg3;
- (void)deleteFolder:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)createFolder:(id)arg1;
- (void)rename:(id)arg1;
- (void)removeFromFolder:(id)arg1;
- (void)addToFolder:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 titleForHeaderInSection:(long long)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)cancel:(id)arg1;
- (void)pop:(id)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidUnload;
- (void)removeFolder:(id)arg1;
- (void)addFolder:(id)arg1;
- (void)fetchFolders;
- (_Bool)hasNavigationHeaderViewOnly;
- (void)viewDidLoad;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

