//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "TableViewCell.h"

@class RKStream;

@interface SubscriptionInfoTableViewCell : TableViewCell
{
    RKStream *__stream;
}

@property(retain, nonatomic) RKStream *stream; // @synthesize stream=__stream;
- (void).cxx_destruct;
- (void)drawContentView:(id)arg1 rect:(struct CGRect)arg2;
- (id)initWithFrame:(struct CGRect)arg1;

@end

