//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

#import "TableViewCellContentViewDelegate-Protocol.h"

@class NSString, TableViewCellContentView, UIColor, UIFont, UIImage;

@interface TableViewCell : UITableViewCell <TableViewCellContentViewDelegate>
{
    TableViewCellContentView *__contentView;
    _Bool __didSetup;
    NSString *_title;
    NSString *_text;
    UIImage *_image;
    double _imageWidth;
    long long _textAlignment;
}

@property(nonatomic) long long textAlignment; // @synthesize textAlignment=_textAlignment;
@property(nonatomic) double imageWidth; // @synthesize imageWidth=_imageWidth;
@property(retain, nonatomic) UIImage *image; // @synthesize image=_image;
@property(copy, nonatomic) NSString *text; // @synthesize text=_text;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
- (void).cxx_destruct;
- (void)drawContentView:(id)arg1 rect:(struct CGRect)arg2;
- (void)setHighlighted:(_Bool)arg1 animated:(_Bool)arg2;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)__setBackgroundColor:(_Bool)arg1 animated:(_Bool)arg2;
- (void)setContentViewNeedsDisplay;
@property(readonly, nonatomic) UIColor *tintColor;
@property(readonly, nonatomic) UIColor *selectedImageColor;
@property(readonly, nonatomic) UIColor *disabledImageColor;
@property(readonly, nonatomic) UIColor *imageColor;
@property(readonly, nonatomic) UIColor *selectedInputColor;
@property(readonly, nonatomic) UIColor *disabledInputColor;
@property(readonly, nonatomic) UIColor *inputColor;
@property(readonly, nonatomic) UIFont *inputFont;
@property(readonly, nonatomic) UIColor *selectedLabelColor;
@property(readonly, nonatomic) UIColor *disabledLabelColor;
@property(readonly, nonatomic) UIColor *labelColor;
@property(readonly, nonatomic) UIFont *labelFont;
@property(readonly, nonatomic) UIColor *selectedTextColor;
@property(readonly, nonatomic) UIColor *disabledTextColor;
@property(readonly, nonatomic) UIColor *textColor;
@property(readonly, nonatomic) UIFont *textFont;
@property(readonly, nonatomic) UIColor *selectedTitleColor;
@property(readonly, nonatomic) UIColor *disabledTitleColor;
@property(readonly, nonatomic) UIColor *titleColor;
@property(readonly, nonatomic) UIFont *titleFont;
@property(readonly, nonatomic) UIColor *cellSelectedBackgroundColor;
@property(readonly, nonatomic) UIColor *cellBackgroundColor;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

