//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@protocol TableViewCellContentViewDelegate;

@interface TableViewCellContentView : UIView
{
    id <TableViewCellContentViewDelegate> __delegate;
}

@property(nonatomic) __weak id <TableViewCellContentViewDelegate> delegate; // @synthesize delegate=__delegate;
- (void).cxx_destruct;
- (void)drawRect:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

