//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "TException.h"

@interface TApplicationException : TException
{
    int mType;
}

+ (id)exceptionWithType:(int)arg1 reason:(id)arg2;
+ (id)read:(id)arg1;
- (void)write:(id)arg1;
- (id)initWithType:(int)arg1 reason:(id)arg2;

@end

