//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSMutableArray;

@interface ThemeSwitcher : UIView
{
    NSMutableArray *__buttons;
}

+ (id)defaultSwitcher;
- (void).cxx_destruct;
- (void)switchTheme:(id)arg1;
- (id)initWithThemeNames:(id)arg1;

@end

