//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIButton.h>

@class NSString;

@interface ThemeSwitcherButton : UIButton
{
    NSString *_themeName;
}

+ (id)buttonWithThemeName:(id)arg1;
@property(copy, nonatomic) NSString *themeName; // @synthesize themeName=_themeName;
- (void).cxx_destruct;
- (void)drawRect:(struct CGRect)arg1;
- (id)initWithThemeName:(id)arg1;

@end

