//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableDictionary;

@interface TitleSizeCache : NSObject
{
    NSMutableDictionary *_cache;
}

+ (id)sharedCache;
+ (void)initialize;
@property(readonly, nonatomic) NSMutableDictionary *cache; // @synthesize cache=_cache;
- (void).cxx_destruct;
- (long long)numberOfLinesForWidth:(double)arg1 withFramesetter:(struct __CTFramesetter *)arg2;
- (void)cacheItem:(id)arg1 withFont:(id)arg2 withTransaction:(id)arg3;
- (void)cacheItem:(id)arg1 withTransaction:(id)arg2;
- (_Bool)isItemCached:(id)arg1;
- (id)interfaceFontName;
- (id)init;

@end

