//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "TTransport-Protocol.h"

@class NSFileHandle, NSString;

@interface TNSFileHandleTransport : NSObject <TTransport>
{
    NSFileHandle *mInputFileHandle;
    NSFileHandle *mOutputFileHandle;
}

- (void)flush;
- (void)write:(char *)arg1 offset:(unsigned int)arg2 length:(unsigned int)arg3;
- (int)readAll:(char *)arg1 offset:(int)arg2 length:(int)arg3;
- (void)dealloc;
- (id)initWithInputFileHandle:(id)arg1 outputFileHandle:(id)arg2;
- (id)initWithFileHandle:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

