//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIButton.h>

@class NSString, ToolbarItem, UIColor, UIImage;

@interface ToolbarButton : UIButton
{
    UIColor *__tintColor;
    ToolbarItem *_item;
    UIImage *_image;
    NSString *_text;
}

@property(copy, nonatomic) NSString *text; // @synthesize text=_text;
@property(retain, nonatomic) UIImage *image; // @synthesize image=_image;
@property(nonatomic) __weak ToolbarItem *item; // @synthesize item=_item;
- (void).cxx_destruct;
- (void)drawRect:(struct CGRect)arg1;
- (void)painterDidChange;
- (id)painter;
@property(retain, nonatomic) UIColor *tintColor; // @synthesize tintColor=__tintColor;
- (void)didMoveToWindow;
- (id)initWithFrame:(struct CGRect)arg1;

@end

