//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, Toolbar, ToolbarButton, UIImage, UIView;

@interface ToolbarItem : NSObject
{
    UIView *__view;
    double __width;
    _Bool _enabled;
    _Bool _hidden;
    Toolbar *_toolbar;
    UIImage *_image;
    NSString *_text;
    id _target;
    SEL _action;
    UIView *_customView;
}

+ (id)flexibleSpaceItem;
+ (id)itemWithText:(id)arg1 target:(id)arg2 action:(SEL)arg3;
+ (id)itemWithImage:(id)arg1 target:(id)arg2 action:(SEL)arg3;
+ (id)itemWithCustomView:(id)arg1;
@property(nonatomic) _Bool hidden; // @synthesize hidden=_hidden;
@property(nonatomic) _Bool enabled; // @synthesize enabled=_enabled;
@property(readonly, nonatomic) UIView *customView; // @synthesize customView=_customView;
@property(nonatomic) SEL action; // @synthesize action=_action;
@property(nonatomic) __weak id target; // @synthesize target=_target;
@property(copy, nonatomic) NSString *text; // @synthesize text=_text;
@property(retain, nonatomic) UIImage *image; // @synthesize image=_image;
@property(nonatomic) __weak Toolbar *toolbar; // @synthesize toolbar=_toolbar;
@property(nonatomic) double width; // @synthesize width=__width;
- (void).cxx_destruct;
- (void)setNeedsDisplay;
- (void)remove;
- (id)createButton;
@property(readonly, nonatomic) __weak ToolbarButton *button;
@property(readonly, nonatomic) __weak UIView *view; // @synthesize view=__view;
@property(readonly, nonatomic, getter=isFlexibleSpaceItem) _Bool flexibleSpaceItem;
- (id)init;

@end

