//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@protocol TProtocol, TTransport;

@protocol TProtocolFactory <NSObject>
- (id <TProtocol>)newProtocolOnTransport:(id <TTransport>)arg1;
@end

