//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@protocol TProtocol;

@protocol TProcessor <NSObject>
- (_Bool)processOnInputProtocol:(id <TProtocol>)arg1 outputProtocol:(id <TProtocol>)arg2;
@end

