//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface TProtocolUtil : NSObject
{
}

+ (void)skipType:(int)arg1 onProtocol:(id)arg2;

@end

