//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@protocol TProcessor, TTransport;

@protocol TProcessorFactory <NSObject>
- (id <TProcessor>)processorForTransport:(id <TTransport>)arg1;
@end

