//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSFileHandle;
@protocol TProcessorFactory, TProtocolFactory;

@interface TSocketServer : NSObject
{
    NSFileHandle *mSocketFileHandle;
    id <TProtocolFactory> mInputProtocolFactory;
    id <TProtocolFactory> mOutputProtocolFactory;
    id <TProcessorFactory> mProcessorFactory;
}

- (void)handleClientConnection:(id)arg1;
- (void)connectionAccepted:(id)arg1;
- (void)dealloc;
- (id)initWithPort:(int)arg1 protocolFactory:(id)arg2 processorFactory:(id)arg3;

@end

