//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIColor.h>

@interface UIColor (CoreKit)
+ (id)wa:(double)arg1:(double)arg2;
+ (id)w:(double)arg1;
+ (id)rgba:(double)arg1:(double)arg2:(double)arg3:(double)arg4;
+ (id)rgb:(double)arg1:(double)arg2:(double)arg3;
- (id)rgbaString;
@end

