//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIImage.h>

@interface UIImage (iPad)
+ (id)touchIconForStream:(id)arg1;
+ (id)favIconForStream:(id)arg1;
+ (void)clearIconCache;
+ (id)favIconCache;
- (void)setAsTouchIconForHost:(id)arg1;
- (void)__setAsFavIconForHost:(id)arg1;
- (void)setAsFavIconForHost:(id)arg1;
@end

