//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@interface UIView (CoreKitCompatibility)
@property(nonatomic) double originY;
@property(nonatomic) double originX;
@property(nonatomic) struct CGPoint origin;
@end

