//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class CoreViewAnimator;

@interface UIView (Animator)
+ (id)beginAnimatorGroup;
- (void)animatorDidCancel:(id)arg1;
- (void)animatorDidFinish:(id)arg1;
- (id)beginAnimator;
- (void)setAnimator:(id)arg1;
@property(readonly, nonatomic) CoreViewAnimator *animator;
@property(readonly, nonatomic) struct CGRect targetFrame;
@property(readonly, nonatomic) struct CGRect currentFrame;
@end

