//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSString;

@interface UIView (iPad)
- (id)UIImageLowRes;
- (id)UIImage:(_Bool)arg1;
- (id)UIImageWithFrame:(struct CGRect)arg1 opaque:(_Bool)arg2;
- (id)UIImageWithFrame:(struct CGRect)arg1;
- (id)UIImage;
- (void)painterDidChange;
@property(copy, nonatomic) NSString *painterKeyPath;
@property(readonly, nonatomic) _Bool paintable;
- (id)findAndResignFirstResponder;
@end

