//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class WebViewNavigationBarTitleView;

@interface WebViewNavigationBar : UIView
{
    WebViewNavigationBarTitleView *_titleView;
}

@property(readonly, nonatomic) WebViewNavigationBarTitleView *titleView; // @synthesize titleView=_titleView;
- (void).cxx_destruct;
- (void)painterDidChange;
- (void)setTitleInsetLeft:(double)arg1 right:(double)arg2;
- (id)initWithFrameView:(id)arg1;

@end

