//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class UITouch, Window;

@protocol WindowTapDelegate <NSObject>
- (void)window:(Window *)arg1 didReceiveTap:(UITouch *)arg2;
@end

